/*
Omada Open API

Testing OLTGemMappingAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package omada

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/Tohaker/omada-go-sdk/omada"
)

func Test_omada_OLTGemMappingAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test OLTGemMappingAPIService AddGemMapping", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var omadacId string
		var siteId string
		var deviceMac string
		var lineProfileId string

		resp, httpRes, err := apiClient.OLTGemMappingAPI.AddGemMapping(context.Background(), omadacId, siteId, deviceMac, lineProfileId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OLTGemMappingAPIService DeleteGemMapping", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var omadacId string
		var siteId string
		var deviceMac string
		var lineProfileId string

		resp, httpRes, err := apiClient.OLTGemMappingAPI.DeleteGemMapping(context.Background(), omadacId, siteId, deviceMac, lineProfileId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OLTGemMappingAPIService EditGemMapping", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var omadacId string
		var siteId string
		var deviceMac string
		var lineProfileId string

		resp, httpRes, err := apiClient.OLTGemMappingAPI.EditGemMapping(context.Background(), omadacId, siteId, deviceMac, lineProfileId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OLTGemMappingAPIService GetGemMappingList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var omadacId string
		var siteId string
		var deviceMac string
		var lineProfileId string

		resp, httpRes, err := apiClient.OLTGemMappingAPI.GetGemMappingList(context.Background(), omadacId, siteId, deviceMac, lineProfileId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OLTGemMappingAPIService GetGemMappingPage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var omadacId string
		var siteId string
		var deviceMac string
		var lineProfileId string

		resp, httpRes, err := apiClient.OLTGemMappingAPI.GetGemMappingPage(context.Background(), omadacId, siteId, deviceMac, lineProfileId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
