/*
Omada Open API

Testing CLITemplateAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package omada

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/Tohaker/omada-go-sdk/omada"
)

func Test_omada_CLITemplateAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CLITemplateAPIService ApplyCliConfigTemplate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var omadacId string
		var siteTemplateId string
		var configId string

		resp, httpRes, err := apiClient.CLITemplateAPI.ApplyCliConfigTemplate(context.Background(), omadacId, siteTemplateId, configId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CLITemplateAPIService CreateCliConfigTemplate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var omadacId string
		var siteTemplateId string
		var cliType string

		resp, httpRes, err := apiClient.CLITemplateAPI.CreateCliConfigTemplate(context.Background(), omadacId, siteTemplateId, cliType).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CLITemplateAPIService DeleteCliConfigTemplate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var omadacId string
		var siteTemplateId string
		var cliType string

		resp, httpRes, err := apiClient.CLITemplateAPI.DeleteCliConfigTemplate(context.Background(), omadacId, siteTemplateId, cliType).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CLITemplateAPIService GetCliConfigTemplate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var omadacId string
		var siteTemplateId string
		var cliType string
		var configId string

		resp, httpRes, err := apiClient.CLITemplateAPI.GetCliConfigTemplate(context.Background(), omadacId, siteTemplateId, cliType, configId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CLITemplateAPIService GetGridCliTemplate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var omadacId string
		var siteTemplateId string
		var cliType string
		var deviceType string

		resp, httpRes, err := apiClient.CLITemplateAPI.GetGridCliTemplate(context.Background(), omadacId, siteTemplateId, cliType, deviceType).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CLITemplateAPIService ModifyCliConfigTemplate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var omadacId string
		var siteTemplateId string
		var cliType string
		var configId string

		resp, httpRes, err := apiClient.CLITemplateAPI.ModifyCliConfigTemplate(context.Background(), omadacId, siteTemplateId, cliType, configId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
