site_name: Omada Go SDK
site_url: https://tohaker.github.io/omada-go-sdk
repo_url: https://github.com/Tohaker/omada-go-sdk
repo_name: Tohaker/omada-go-sdk
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
docs_dir: omada
plugins:
  - search
  - awesome-nav
  - exclude:
      glob:
        - /.openapi-generator
        - /test
        - "*.go"
        - .openapi-generator-ignore