site_name: Omada Go SDK
site_url: https://tohaker.github.io/omada-go-sdk
repo_url: https://github.com/Tohaker/omada-go-sdk
repo_name: Tohaker/omada-go-sdk
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
docs_dir: omada
nav:
  - Home: README.md
  - SDK Reference:
    - Abnormal Detect: docs/AbnormalDetectAPI.md
    - Access Control: docs/AccessControlAPI.md
    - Access Control Template: docs/AccessControlTemplateAPI.md
    - ACL: docs/ACLAPI.md
    - ACL Template: docs/ACLTemplateAPI.md
    - AP: docs/ApAPI.md
    - Application Control: docs/ApplicationControlAPI.md
    - ARP Detection: docs/ArpDetectionAPI.md
    - Attack Defense: docs/AttackDefenseAPI.md
    - Attack Defense Template: docs/AttackDefenseTemplateAPI.md
    - Authentication: docs/AuthenticationAPI.md
    - Authentication Template: docs/AuthenticationTemplateAPI.md
    - Authorize: docs/AuthorizeAPI.md
    - Authorized Client: docs/AuthorizedClientAPI.md
    - Backup and Restore: docs/BackupAndRestoreAPI.md
    - Bandwidth Control: docs/BandwidthControlAPI.md
    - Bandwidth Control Template: docs/BandwidthControlTemplateAPI.md
    - Batch OpenAPI: docs/BatchOpenAPIAPI.md
    - Bluetooth: docs/BluetoothAPI.md
    - Bluetooth Template: docs/BluetoothTemplateAPI.md
    - Cert Profiles: docs/CertProfilesAPI.md
    - Cert Profiles Template: docs/CertProfilesTemplateAPI.md
    - CLI: docs/CLIAPI.md
    - CLI Template: docs/CLITemplateAPI.md
    - Client: docs/ClientAPI.md
    - Client Insight: docs/ClientInsightAPI.md
    - Cloud User: docs/CloudUserAPI.md
    - Controller Settings: docs/ControllerSettingsAPI.md
    - Customer: docs/CustomerAPI.md
    - Dashboard: docs/DashboardAPI.md
    - Data Export: docs/DataExportAPI.md
    - Device: docs/DeviceAPI.md
    - Device Management Setting: docs/DeviceManagementSettingAPI.md
    - DHCP Snooping: docs/DhcpSnoopingAPI.md
    - Disable NAT: docs/DisableNatAPI.md
    - EoGRE Tunnel: docs/EoGRETunnelAPI.md
    - Firewall: docs/FirewallAPI.md
    - Firewall Template: docs/FirewallTemplateAPI.md
    - Firmware: docs/FirmwareAPI.md
    - Form Auth Data: docs/FormAuthDataAPI.md
    - Gateway: docs/GatewayAPI.md
    - Gateway QoS: docs/GatewayQoSAPI.md
    - Gateway QoS Template: docs/GatewayQOSTemplateAPI.md
    - Global Dashboard Overview: docs/GlobalDashboardOverviewAPI.md
    - Global Security: docs/GlobalSecurityAPI.md
    - Health: docs/HealthAPI.md
    - History Data Retention: docs/HistoryDataRetentionAPI.md
    - Hotspot Operators: docs/HotspotOperatorsAPI.md
    - IDSIPS: docs/IDSIPSAPI.md
    - IDSIPS Template: docs/IDSIPSTemplateAPI.md
    - Insight: docs/InsightAPI.md
    - IntelliRecover Client: docs/IntelliRecoverClientAPI.md
    - IntelliRecover Device: docs/IntelliRecoverDeviceAPI.md
    - IP-MAC Binding: docs/IPMACBindingAPI.md
    - IP-MAC Binding Template: docs/IPMACBindingTemplateAPI.md
    - LAN Multicast: docs/LanMulticastAPI.md
    - LAN Multicast Template: docs/LanMulticastTemplateAPI.md
    - License: docs/LicenseAPI.md
    - Local User: docs/LocalUserAPI.md
    - Log: docs/LogAPI.md
    - Log Template: docs/LogTemplateAPI.md
    - MAC Filtering: docs/MACFilteringAPI.md
    - MAC Filtering Template: docs/MACFilteringTemplateAPI.md
    - MLAG: docs/MlagAPI.md
    - MSP Batch OpenAPI: docs/MSPBatchOpenAPIAPI.md
    - MSP Device: docs/MSPDeviceAPI.md
    - MSP History Data Retention: docs/MSPHistoryDataRetentionAPI.md
    - MSP License: docs/MspLicenseAPI.md
    - MSP Log: docs/MspLogAPI.md
    - MSP Setting: docs/MspSettingAPI.md
    - MSP Site: docs/MSPSiteAPI.md
    - MSP SSO: docs/MSPSSOAPI.md
    - MSP User and Role: docs/MSPUserAndRoleAPI.md
    - MSP Webhook Setting: docs/MspWebhookSettingAPI.md
    - NAT: docs/NATAPI.md
    - NAT Template: docs/NATTemplateAPI.md
    - Network Analyze: docs/NetworkAnalyzeAPI.md
    - Network Report: docs/NetworkReportAPI.md
    - OLT: docs/OLTAPI.md
    - OLT DBA: docs/OLTDBAAPI.md
    - OLT GEM Mapping: docs/OLTGemMappingAPI.md
    - OLT GEM Port: docs/OLTGemPortAPI.md
    - OLT Line Profile: docs/OLTLineProfileAPI.md
    - OLT ONT Port: docs/OLTONTPortAPI.md
    - OLT ONU Management: docs/OLTONUManagementAPI.md
    - OLT ONU Register: docs/OLTONURegisterAPI.md
    - OLT PON Port: docs/OLTPonPortAPI.md
    - OLT Service Port: docs/OLTServicePortAPI.md
    - OLT Service Port Profile: docs/OLTServicePortProfileAPI.md
    - OLT Service Profile: docs/OLTServiceProfileAPI.md
    - OLT TCont: docs/OLTTContAPI.md
    - OLT Traffic Profile: docs/OLTTrafficProfileAPI.md
    - OSPF: docs/OSPFAPI.md
    - OUI-Based VLAN: docs/OUIBasedVLANAPI.md
    - OUI-Based VLAN Template: docs/OUIBasedVLANTemplateAPI.md
    - Profiles: docs/ProfilesAPI.md
    - Profiles Template: docs/ProfilesTemplateAPI.md
    - Quick Action: docs/QuickActionAPI.md
    - Report V2: docs/ReportV2API.md
    - Routing: docs/RoutingAPI.md
    - Routing Template: docs/RoutingTemplateAPI.md
    - RRM: docs/RrmAPI.md
    - Schedule: docs/ScheduleAPI.md
    - Schedule Template: docs/ScheduleTemplateAPI.md
    - SD-WAN: docs/SDWANAPI.md
    - Service: docs/ServiceAPI.md
    - Service Template: docs/ServiceTemplateAPI.md
    - Session Limit: docs/SessionLimitAPI.md
    - Session Limit Template: docs/SessionLimitTemplateAPI.md
    - SIM: docs/SIMAPI.md
    - SIM Template: docs/SIMTemplateAPI.md
    - Site: docs/SiteAPI.md
    - Site Configuration: docs/SiteConfigurationAPI.md
    - Site Template: docs/SiteTemplateAPI.md
    - Site Template Configuration: docs/SiteTemplateConfigurationAPI.md
    - SSL VPN: docs/SSLVPNAPI.md
    - SSO: docs/SSOAPI.md
    - Stack: docs/StackAPI.md
    - Statistic: docs/StatisticAPI.md
    - Switch: docs/SwitchAPI.md
    - Switch QoS: docs/SwitchQoSAPI.md
    - Switch Template: docs/SwitchTemplateAPI.md
    - System Settings: docs/SystemSettingsAPI.md
    - Threat Management: docs/ThreatManagementAPI.md
    - Topology: docs/TopologyAPI.md
    - URL Filtering: docs/URLFilteringAPI.md
    - URL Filtering Template: docs/URLFilteringTemplateAPI.md
    - User and Role: docs/UserAndRoleAPI.md
    - VoIP: docs/VoIPAPI.md
    - VoIP Template: docs/VoIPTemplateAPI.md
    - Voucher: docs/VoucherAPI.md
    - VPN: docs/VPNAPI.md
    - VRRP: docs/VRRPAPI.md
    - Webhook Setting: docs/WebhookSettingAPI.md
    - Wired Network: docs/WiredNetworkAPI.md
    - Wired Network Template: docs/WiredNetworkTemplateAPI.md
    - WireGuard VPN: docs/WireguardVPNAPI.md
    - Wireless IDSIPS: docs/WirelessIDSIPSAPI.md
    - Wireless IDSIPS Template: docs/WirelessIDSIPSTemplateAPI.md
    - Wireless Network: docs/WirelessNetworkAPI.md
    - Wireless Network Template: docs/WirelessNetworkTemplateAPI.md
    - WLAN Optimization: docs/WLANOptimizationAPI.md
plugins:
  - search
  - exclude:
      glob:
        - /.openapi-generator
        - /test
        - "*.go"
        - .openapi-generator-ignore