/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type DHCPReservationAPI interface {

	/*
	BatchExportDhcpReservationListToFile Batch Export DHCP reservation list to file

	Batch Export DHCP reservation list to file.<br/><br/>The interface requires one of the permissions: <br/>Site Settings Manager View Only<br/>Network Config Page View Only<br/><br/>The possible error code for the interface in the returned body is one of the following error codes (non generic error codes): <br/>-1005  -  Operation forbidden.<br/>-33004  -  Operation failed because other operations (site copying, restoring, template synchronizing, etc.) are being performed on this site. Please wait and try again later.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param omadacId Omada ID
	@param siteId Site ID
	@return DHCPReservationAPIBatchExportDhcpReservationListToFileRequest
	*/
	BatchExportDhcpReservationListToFile(ctx context.Context, omadacId string, siteId string) DHCPReservationAPIBatchExportDhcpReservationListToFileRequest

	// BatchExportDhcpReservationListToFileExecute executes the request
	//  @return OperationResponseWithoutResult
	BatchExportDhcpReservationListToFileExecute(r DHCPReservationAPIBatchExportDhcpReservationListToFileRequest) (*OperationResponseWithoutResult, *http.Response, error)

	/*
	CreateDhcpReservation Create a new DHCP reservation

	Create a new DHCP reservation with the given params.<br/><br/>The interface requires one of the permissions: <br/>Site Settings Manager Modify<br/>Network Config Page Modify<br/>Site Device Manager Modify<br/><br/>The possible error code for the interface in the returned body is one of the following error codes (non generic error codes): <br/>-33000  -  This site does not exist.<br/>-33004  -  Operation failed because other operations (site copying, restoring, template synchronizing, etc.) are being performed on this site. Please wait and try again later.<br/>-33503  -  This network does not exist.<br/>-34511  -  The number of DHCP Reservation entries has reached the limit.<br/>-34512  -  Invalid network. Please select a network with the purpose selected as Interface.<br/>-34513  -  Enter an IP address within the Network IP range.<br/>-34514  -  This IP address conflicts with an existing DHCP Reservation entry.<br/>-34515  -  This MAC address conflicts with an existing DHCP Reservation entry.<br/>-34520  -  The LAN network in this entry does not exist, please reconfigure the DHCP reservation entry.<br/>-34522  -  This IP address of DHCP Reservation conflicts with a reserved static IP-MAC binding.<br/>-34543  -  The IP cannot be the same as the LAN network IP.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param omadacId Omada ID
	@param siteId Site ID
	@return DHCPReservationAPICreateDhcpReservationRequest
	*/
	CreateDhcpReservation(ctx context.Context, omadacId string, siteId string) DHCPReservationAPICreateDhcpReservationRequest

	// CreateDhcpReservationExecute executes the request
	//  @return OperationResponseResIdOpenApiVO
	CreateDhcpReservationExecute(r DHCPReservationAPICreateDhcpReservationRequest) (*OperationResponseResIdOpenApiVO, *http.Response, error)

	/*
	DeleteDhcpReservation Delete an exist DHCP reservation

	Delete an exist DHCP reservation with the given params.<br/><br/>The interface requires one of the permissions: <br/>Site Settings Manager Modify<br/>Network Config Page Modify<br/>Site Device Manager Modify<br/><br/>The possible error code for the interface in the returned body is one of the following error codes (non generic error codes): <br/>-33000  -  This site does not exist.<br/>-33004  -  Operation failed because other operations (site copying, restoring, template synchronizing, etc.) are being performed on this site. Please wait and try again later.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param omadacId Omada ID
	@param siteId Site ID
	@param mac MAC address of the DHCP reservation, format: AA-BB-CC-11-22-33.
	@return DHCPReservationAPIDeleteDhcpReservationRequest
	*/
	DeleteDhcpReservation(ctx context.Context, omadacId string, siteId string, mac string) DHCPReservationAPIDeleteDhcpReservationRequest

	// DeleteDhcpReservationExecute executes the request
	//  @return OperationResponseWithoutResult
	DeleteDhcpReservationExecute(r DHCPReservationAPIDeleteDhcpReservationRequest) (*OperationResponseWithoutResult, *http.Response, error)

	/*
	DownloadDhcpImportResult Download DHCP import result

	Download DHCP import result.<br/><br/>The interface requires one of the permissions: <br/>Site Settings Manager Modify<br/>Network Config Page Modify<br/>Site Device Manager Modify<br/><br/>The possible error code for the interface in the returned body is one of the following error codes (non generic error codes): <br/>-33004  -  Operation failed because other operations (site copying, restoring, template synchronizing, etc.) are being performed on this site. Please wait and try again later.<br/>-34534  -  The error messages file has expired and cannot be downloaded.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param omadacId Omada ID
	@param siteId Site ID
	@return DHCPReservationAPIDownloadDhcpImportResultRequest
	*/
	DownloadDhcpImportResult(ctx context.Context, omadacId string, siteId string) DHCPReservationAPIDownloadDhcpImportResultRequest

	// DownloadDhcpImportResultExecute executes the request
	//  @return OperationResponse
	DownloadDhcpImportResultExecute(r DHCPReservationAPIDownloadDhcpImportResultRequest) (*OperationResponse, *http.Response, error)

	/*
	ExportDhcpReservation Export DHCP reservation to IP_MAC Binding

	Export an exist DHCP reservation to IP_MAC Binding.<br/><br/>The interface requires one of the permissions: <br/>Site Settings Manager Modify<br/>Network Config Page Modify<br/>Site Device Manager Modify<br/><br/>The possible error code for the interface in the returned body is one of the following error codes (non generic error codes): <br/>-33000  -  This site does not exist.<br/>-33004  -  Operation failed because other operations (site copying, restoring, template synchronizing, etc.) are being performed on this site. Please wait and try again later.<br/>-33503  -  This network does not exist.<br/>-33621  -  The number of IP-MAC Binding entries has reached the limit.<br/>-33623  -  The binding IP cannot be the same as the LAN network IP.<br/>-33752  -  This IP address already exists.<br/>-33753  -  This IP address of IP-MAC binding conflicts with a reserved static DHCP Reservation.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param omadacId Omada ID
	@param siteId Site ID
	@param mac DHCP MAC address
	@return DHCPReservationAPIExportDhcpReservationRequest
	*/
	ExportDhcpReservation(ctx context.Context, omadacId string, siteId string, mac string) DHCPReservationAPIExportDhcpReservationRequest

	// ExportDhcpReservationExecute executes the request
	//  @return OperationResponseWithoutResult
	ExportDhcpReservationExecute(r DHCPReservationAPIExportDhcpReservationRequest) (*OperationResponseWithoutResult, *http.Response, error)

	/*
	ExportDhcpReservationListToFile Export DHCP reservation list to file

	Export existed DHCP reservation list to file.<br/><br/>The interface requires one of the permissions: <br/>Site Settings Manager Modify<br/>Network Config Page Modify<br/>Site Device Manager Modify<br/><br/>The possible error code for the interface in the returned body is one of the following error codes (non generic error codes): <br/>-1005  -  Operation forbidden.<br/>-33004  -  Operation failed because other operations (site copying, restoring, template synchronizing, etc.) are being performed on this site. Please wait and try again later.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param omadacId Omada ID
	@param siteId Site ID
	@return DHCPReservationAPIExportDhcpReservationListToFileRequest
	*/
	ExportDhcpReservationListToFile(ctx context.Context, omadacId string, siteId string) DHCPReservationAPIExportDhcpReservationListToFileRequest

	// ExportDhcpReservationListToFileExecute executes the request
	//  @return OperationResponseWithoutResult
	ExportDhcpReservationListToFileExecute(r DHCPReservationAPIExportDhcpReservationListToFileRequest) (*OperationResponseWithoutResult, *http.Response, error)

	/*
	GetDhcpReservationGrid Get DHCP reservation list

	Get DHCP reservation list of the site with the given omadacId and siteId.<br/><br/>The interface requires one of the permissions: <br/>Site Settings Manager View Only<br/>Network Config Page View Only<br/>Site Device Manager View Only<br/><br/>The possible error code for the interface in the returned body is one of the following error codes (non generic error codes): <br/>-33000  -  This site does not exist.<br/>-33004  -  Operation failed because other operations (site copying, restoring, template synchronizing, etc.) are being performed on this site. Please wait and try again later.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param omadacId Omada ID
	@param siteId Site ID
	@return DHCPReservationAPIGetDhcpReservationGridRequest
	*/
	GetDhcpReservationGrid(ctx context.Context, omadacId string, siteId string) DHCPReservationAPIGetDhcpReservationGridRequest

	// GetDhcpReservationGridExecute executes the request
	//  @return OperationResponseDhcpReservationOpenApiGridVODhcpReservationOpenApiVO
	GetDhcpReservationGridExecute(r DHCPReservationAPIGetDhcpReservationGridRequest) (*OperationResponseDhcpReservationOpenApiGridVODhcpReservationOpenApiVO, *http.Response, error)

	/*
	GetGridAllDhcpUserList Get the dhcp user list of all servers

	Get the dhcp user list of all servers.<br/><br/>The interface requires one of the permissions: <br/>Site Settings Manager View Only<br/>Network Config Page View Only

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param omadacId Omada ID
	@param siteId Site ID
	@return DHCPReservationAPIGetGridAllDhcpUserListRequest
	*/
	GetGridAllDhcpUserList(ctx context.Context, omadacId string, siteId string) DHCPReservationAPIGetGridAllDhcpUserListRequest

	// GetGridAllDhcpUserListExecute executes the request
	//  @return OperationResponseDhcpUserGridVODhcpUserVO
	GetGridAllDhcpUserListExecute(r DHCPReservationAPIGetGridAllDhcpUserListRequest) (*OperationResponseDhcpUserGridVODhcpUserVO, *http.Response, error)

	/*
	ImportDhcpReservationListFromFile Import DHCP reservation list from file

	Import DHCP reservation list from existed file.<br/><br/>The interface requires one of the permissions: <br/>Site Settings Manager Modify<br/>Network Config Page Modify<br/>Site Device Manager Modify<br/><br/>The possible error code for the interface in the returned body is one of the following error codes (non generic error codes): <br/>-33004  -  Operation failed because other operations (site copying, restoring, template synchronizing, etc.) are being performed on this site. Please wait and try again later.<br/>-33712  -  This file is empty.<br/>-33713  -  Failed to process the files.<br/>-34533  -  The uploaded file contains wrong-format content. Please download the error messages, modify your file as required and re-upload it.<br/>-34544  -  The format of the import file must be csv.<br/>-34545  -  The number of DHCP Reservation entries has reached the limit. The exceeding entries cannot be saved.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param omadacId Omada ID
	@param siteId Site ID
	@return DHCPReservationAPIImportDhcpReservationListFromFileRequest
	*/
	ImportDhcpReservationListFromFile(ctx context.Context, omadacId string, siteId string) DHCPReservationAPIImportDhcpReservationListFromFileRequest

	// ImportDhcpReservationListFromFileExecute executes the request
	//  @return OperationResponseWithoutResult
	ImportDhcpReservationListFromFileExecute(r DHCPReservationAPIImportDhcpReservationListFromFileRequest) (*OperationResponseWithoutResult, *http.Response, error)

	/*
	ModifyDhcpReservation Modify an exist DHCP reservation

	Modify an exist DHCP reservation with the given params.<br/><br/>The interface requires one of the permissions: <br/>Site Settings Manager Modify<br/>Network Config Page Modify<br/>Site Device Manager Modify<br/><br/>The possible error code for the interface in the returned body is one of the following error codes (non generic error codes): <br/>-33000  -  This site does not exist.<br/>-33004  -  Operation failed because other operations (site copying, restoring, template synchronizing, etc.) are being performed on this site. Please wait and try again later.<br/>-33503  -  This network does not exist.<br/>-34511  -  The number of DHCP Reservation entries has reached the limit.<br/>-34512  -  Invalid network. Please select a network with the purpose selected as Interface.<br/>-34513  -  Enter an IP address within the Network IP range.<br/>-34514  -  This IP address conflicts with an existing DHCP Reservation entry.<br/>-34515  -  This MAC address conflicts with an existing DHCP Reservation entry.<br/>-34520  -  The LAN network in this entry does not exist, please reconfigure the DHCP reservation entry.<br/>-34522  -  This IP address of DHCP Reservation conflicts with a reserved static IP-MAC binding.<br/>-34543  -  The IP cannot be the same as the LAN network IP.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param omadacId Omada ID
	@param siteId Site ID
	@param mac MAC address of the DHCP reservation, format: AA-BB-CC-11-22-33.
	@return DHCPReservationAPIModifyDhcpReservationRequest
	*/
	ModifyDhcpReservation(ctx context.Context, omadacId string, siteId string, mac string) DHCPReservationAPIModifyDhcpReservationRequest

	// ModifyDhcpReservationExecute executes the request
	//  @return OperationResponseWithoutResult
	ModifyDhcpReservationExecute(r DHCPReservationAPIModifyDhcpReservationRequest) (*OperationResponseWithoutResult, *http.Response, error)

	/*
	ReservationFromDhcpUserList Reservation From Dhcp User List

	Reservation From Dhcp User List.<br/><br/>The interface requires one of the permissions: <br/>Site Settings Manager View Only<br/>Network Config Page View Only

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param omadacId Omada ID
	@param siteId Site ID
	@return DHCPReservationAPIReservationFromDhcpUserListRequest
	*/
	ReservationFromDhcpUserList(ctx context.Context, omadacId string, siteId string) DHCPReservationAPIReservationFromDhcpUserListRequest

	// ReservationFromDhcpUserListExecute executes the request
	//  @return OperationResponseDhcpReservationErrorVO
	ReservationFromDhcpUserListExecute(r DHCPReservationAPIReservationFromDhcpUserListRequest) (*OperationResponseDhcpReservationErrorVO, *http.Response, error)
}

// DHCPReservationAPIService DHCPReservationAPI service
type DHCPReservationAPIService service

type DHCPReservationAPIBatchExportDhcpReservationListToFileRequest struct {
	ctx context.Context
	ApiService DHCPReservationAPI
	omadacId string
	siteId string
	dhcpReservationFilterVO *DhcpReservationFilterVO
}

func (r DHCPReservationAPIBatchExportDhcpReservationListToFileRequest) DhcpReservationFilterVO(dhcpReservationFilterVO DhcpReservationFilterVO) DHCPReservationAPIBatchExportDhcpReservationListToFileRequest {
	r.dhcpReservationFilterVO = &dhcpReservationFilterVO
	return r
}

func (r DHCPReservationAPIBatchExportDhcpReservationListToFileRequest) Execute() (*OperationResponseWithoutResult, *http.Response, error) {
	return r.ApiService.BatchExportDhcpReservationListToFileExecute(r)
}

/*
BatchExportDhcpReservationListToFile Batch Export DHCP reservation list to file

Batch Export DHCP reservation list to file.<br/><br/>The interface requires one of the permissions: <br/>Site Settings Manager View Only<br/>Network Config Page View Only<br/><br/>The possible error code for the interface in the returned body is one of the following error codes (non generic error codes): <br/>-1005  -  Operation forbidden.<br/>-33004  -  Operation failed because other operations (site copying, restoring, template synchronizing, etc.) are being performed on this site. Please wait and try again later.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param omadacId Omada ID
 @param siteId Site ID
 @return DHCPReservationAPIBatchExportDhcpReservationListToFileRequest
*/
func (a *DHCPReservationAPIService) BatchExportDhcpReservationListToFile(ctx context.Context, omadacId string, siteId string) DHCPReservationAPIBatchExportDhcpReservationListToFileRequest {
	return DHCPReservationAPIBatchExportDhcpReservationListToFileRequest{
		ApiService: a,
		ctx: ctx,
		omadacId: omadacId,
		siteId: siteId,
	}
}

// Execute executes the request
//  @return OperationResponseWithoutResult
func (a *DHCPReservationAPIService) BatchExportDhcpReservationListToFileExecute(r DHCPReservationAPIBatchExportDhcpReservationListToFileRequest) (*OperationResponseWithoutResult, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *OperationResponseWithoutResult
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DHCPReservationAPIService.BatchExportDhcpReservationListToFile")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/openapi/v1/{omadacId}/sites/{siteId}/setting/service/files/dhcp/batch-export"
	localVarPath = strings.Replace(localVarPath, "{"+"omadacId"+"}", url.PathEscape(parameterValueToString(r.omadacId, "omadacId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"siteId"+"}", url.PathEscape(parameterValueToString(r.siteId, "siteId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.dhcpReservationFilterVO == nil {
		return localVarReturnValue, nil, reportError("dhcpReservationFilterVO is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.dhcpReservationFilterVO
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["AccessToken"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type DHCPReservationAPICreateDhcpReservationRequest struct {
	ctx context.Context
	ApiService DHCPReservationAPI
	omadacId string
	siteId string
	createDhcpReservationOpenApiVO *CreateDhcpReservationOpenApiVO
}

func (r DHCPReservationAPICreateDhcpReservationRequest) CreateDhcpReservationOpenApiVO(createDhcpReservationOpenApiVO CreateDhcpReservationOpenApiVO) DHCPReservationAPICreateDhcpReservationRequest {
	r.createDhcpReservationOpenApiVO = &createDhcpReservationOpenApiVO
	return r
}

func (r DHCPReservationAPICreateDhcpReservationRequest) Execute() (*OperationResponseResIdOpenApiVO, *http.Response, error) {
	return r.ApiService.CreateDhcpReservationExecute(r)
}

/*
CreateDhcpReservation Create a new DHCP reservation

Create a new DHCP reservation with the given params.<br/><br/>The interface requires one of the permissions: <br/>Site Settings Manager Modify<br/>Network Config Page Modify<br/>Site Device Manager Modify<br/><br/>The possible error code for the interface in the returned body is one of the following error codes (non generic error codes): <br/>-33000  -  This site does not exist.<br/>-33004  -  Operation failed because other operations (site copying, restoring, template synchronizing, etc.) are being performed on this site. Please wait and try again later.<br/>-33503  -  This network does not exist.<br/>-34511  -  The number of DHCP Reservation entries has reached the limit.<br/>-34512  -  Invalid network. Please select a network with the purpose selected as Interface.<br/>-34513  -  Enter an IP address within the Network IP range.<br/>-34514  -  This IP address conflicts with an existing DHCP Reservation entry.<br/>-34515  -  This MAC address conflicts with an existing DHCP Reservation entry.<br/>-34520  -  The LAN network in this entry does not exist, please reconfigure the DHCP reservation entry.<br/>-34522  -  This IP address of DHCP Reservation conflicts with a reserved static IP-MAC binding.<br/>-34543  -  The IP cannot be the same as the LAN network IP.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param omadacId Omada ID
 @param siteId Site ID
 @return DHCPReservationAPICreateDhcpReservationRequest
*/
func (a *DHCPReservationAPIService) CreateDhcpReservation(ctx context.Context, omadacId string, siteId string) DHCPReservationAPICreateDhcpReservationRequest {
	return DHCPReservationAPICreateDhcpReservationRequest{
		ApiService: a,
		ctx: ctx,
		omadacId: omadacId,
		siteId: siteId,
	}
}

// Execute executes the request
//  @return OperationResponseResIdOpenApiVO
func (a *DHCPReservationAPIService) CreateDhcpReservationExecute(r DHCPReservationAPICreateDhcpReservationRequest) (*OperationResponseResIdOpenApiVO, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *OperationResponseResIdOpenApiVO
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DHCPReservationAPIService.CreateDhcpReservation")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/openapi/v1/{omadacId}/sites/{siteId}/setting/service/dhcp"
	localVarPath = strings.Replace(localVarPath, "{"+"omadacId"+"}", url.PathEscape(parameterValueToString(r.omadacId, "omadacId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"siteId"+"}", url.PathEscape(parameterValueToString(r.siteId, "siteId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.createDhcpReservationOpenApiVO == nil {
		return localVarReturnValue, nil, reportError("createDhcpReservationOpenApiVO is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.createDhcpReservationOpenApiVO
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["AccessToken"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type DHCPReservationAPIDeleteDhcpReservationRequest struct {
	ctx context.Context
	ApiService DHCPReservationAPI
	omadacId string
	siteId string
	mac string
}

func (r DHCPReservationAPIDeleteDhcpReservationRequest) Execute() (*OperationResponseWithoutResult, *http.Response, error) {
	return r.ApiService.DeleteDhcpReservationExecute(r)
}

/*
DeleteDhcpReservation Delete an exist DHCP reservation

Delete an exist DHCP reservation with the given params.<br/><br/>The interface requires one of the permissions: <br/>Site Settings Manager Modify<br/>Network Config Page Modify<br/>Site Device Manager Modify<br/><br/>The possible error code for the interface in the returned body is one of the following error codes (non generic error codes): <br/>-33000  -  This site does not exist.<br/>-33004  -  Operation failed because other operations (site copying, restoring, template synchronizing, etc.) are being performed on this site. Please wait and try again later.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param omadacId Omada ID
 @param siteId Site ID
 @param mac MAC address of the DHCP reservation, format: AA-BB-CC-11-22-33.
 @return DHCPReservationAPIDeleteDhcpReservationRequest
*/
func (a *DHCPReservationAPIService) DeleteDhcpReservation(ctx context.Context, omadacId string, siteId string, mac string) DHCPReservationAPIDeleteDhcpReservationRequest {
	return DHCPReservationAPIDeleteDhcpReservationRequest{
		ApiService: a,
		ctx: ctx,
		omadacId: omadacId,
		siteId: siteId,
		mac: mac,
	}
}

// Execute executes the request
//  @return OperationResponseWithoutResult
func (a *DHCPReservationAPIService) DeleteDhcpReservationExecute(r DHCPReservationAPIDeleteDhcpReservationRequest) (*OperationResponseWithoutResult, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *OperationResponseWithoutResult
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DHCPReservationAPIService.DeleteDhcpReservation")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/openapi/v1/{omadacId}/sites/{siteId}/setting/service/dhcp/{mac}"
	localVarPath = strings.Replace(localVarPath, "{"+"omadacId"+"}", url.PathEscape(parameterValueToString(r.omadacId, "omadacId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"siteId"+"}", url.PathEscape(parameterValueToString(r.siteId, "siteId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"mac"+"}", url.PathEscape(parameterValueToString(r.mac, "mac")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["AccessToken"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type DHCPReservationAPIDownloadDhcpImportResultRequest struct {
	ctx context.Context
	ApiService DHCPReservationAPI
	omadacId string
	siteId string
}

func (r DHCPReservationAPIDownloadDhcpImportResultRequest) Execute() (*OperationResponse, *http.Response, error) {
	return r.ApiService.DownloadDhcpImportResultExecute(r)
}

/*
DownloadDhcpImportResult Download DHCP import result

Download DHCP import result.<br/><br/>The interface requires one of the permissions: <br/>Site Settings Manager Modify<br/>Network Config Page Modify<br/>Site Device Manager Modify<br/><br/>The possible error code for the interface in the returned body is one of the following error codes (non generic error codes): <br/>-33004  -  Operation failed because other operations (site copying, restoring, template synchronizing, etc.) are being performed on this site. Please wait and try again later.<br/>-34534  -  The error messages file has expired and cannot be downloaded.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param omadacId Omada ID
 @param siteId Site ID
 @return DHCPReservationAPIDownloadDhcpImportResultRequest
*/
func (a *DHCPReservationAPIService) DownloadDhcpImportResult(ctx context.Context, omadacId string, siteId string) DHCPReservationAPIDownloadDhcpImportResultRequest {
	return DHCPReservationAPIDownloadDhcpImportResultRequest{
		ApiService: a,
		ctx: ctx,
		omadacId: omadacId,
		siteId: siteId,
	}
}

// Execute executes the request
//  @return OperationResponse
func (a *DHCPReservationAPIService) DownloadDhcpImportResultExecute(r DHCPReservationAPIDownloadDhcpImportResultRequest) (*OperationResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *OperationResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DHCPReservationAPIService.DownloadDhcpImportResult")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/openapi/v1/{omadacId}/sites/{siteId}/setting/service/files/dhcp/import-result"
	localVarPath = strings.Replace(localVarPath, "{"+"omadacId"+"}", url.PathEscape(parameterValueToString(r.omadacId, "omadacId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"siteId"+"}", url.PathEscape(parameterValueToString(r.siteId, "siteId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["AccessToken"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type DHCPReservationAPIExportDhcpReservationRequest struct {
	ctx context.Context
	ApiService DHCPReservationAPI
	omadacId string
	siteId string
	mac string
	exportDhcpReservationOpenApiVO *ExportDhcpReservationOpenApiVO
}

func (r DHCPReservationAPIExportDhcpReservationRequest) ExportDhcpReservationOpenApiVO(exportDhcpReservationOpenApiVO ExportDhcpReservationOpenApiVO) DHCPReservationAPIExportDhcpReservationRequest {
	r.exportDhcpReservationOpenApiVO = &exportDhcpReservationOpenApiVO
	return r
}

func (r DHCPReservationAPIExportDhcpReservationRequest) Execute() (*OperationResponseWithoutResult, *http.Response, error) {
	return r.ApiService.ExportDhcpReservationExecute(r)
}

/*
ExportDhcpReservation Export DHCP reservation to IP_MAC Binding

Export an exist DHCP reservation to IP_MAC Binding.<br/><br/>The interface requires one of the permissions: <br/>Site Settings Manager Modify<br/>Network Config Page Modify<br/>Site Device Manager Modify<br/><br/>The possible error code for the interface in the returned body is one of the following error codes (non generic error codes): <br/>-33000  -  This site does not exist.<br/>-33004  -  Operation failed because other operations (site copying, restoring, template synchronizing, etc.) are being performed on this site. Please wait and try again later.<br/>-33503  -  This network does not exist.<br/>-33621  -  The number of IP-MAC Binding entries has reached the limit.<br/>-33623  -  The binding IP cannot be the same as the LAN network IP.<br/>-33752  -  This IP address already exists.<br/>-33753  -  This IP address of IP-MAC binding conflicts with a reserved static DHCP Reservation.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param omadacId Omada ID
 @param siteId Site ID
 @param mac DHCP MAC address
 @return DHCPReservationAPIExportDhcpReservationRequest
*/
func (a *DHCPReservationAPIService) ExportDhcpReservation(ctx context.Context, omadacId string, siteId string, mac string) DHCPReservationAPIExportDhcpReservationRequest {
	return DHCPReservationAPIExportDhcpReservationRequest{
		ApiService: a,
		ctx: ctx,
		omadacId: omadacId,
		siteId: siteId,
		mac: mac,
	}
}

// Execute executes the request
//  @return OperationResponseWithoutResult
func (a *DHCPReservationAPIService) ExportDhcpReservationExecute(r DHCPReservationAPIExportDhcpReservationRequest) (*OperationResponseWithoutResult, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *OperationResponseWithoutResult
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DHCPReservationAPIService.ExportDhcpReservation")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/openapi/v1/{omadacId}/sites/{siteId}/setting/service/dhcp/{mac}/export"
	localVarPath = strings.Replace(localVarPath, "{"+"omadacId"+"}", url.PathEscape(parameterValueToString(r.omadacId, "omadacId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"siteId"+"}", url.PathEscape(parameterValueToString(r.siteId, "siteId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"mac"+"}", url.PathEscape(parameterValueToString(r.mac, "mac")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.exportDhcpReservationOpenApiVO == nil {
		return localVarReturnValue, nil, reportError("exportDhcpReservationOpenApiVO is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.exportDhcpReservationOpenApiVO
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["AccessToken"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type DHCPReservationAPIExportDhcpReservationListToFileRequest struct {
	ctx context.Context
	ApiService DHCPReservationAPI
	omadacId string
	siteId string
}

func (r DHCPReservationAPIExportDhcpReservationListToFileRequest) Execute() (*OperationResponseWithoutResult, *http.Response, error) {
	return r.ApiService.ExportDhcpReservationListToFileExecute(r)
}

/*
ExportDhcpReservationListToFile Export DHCP reservation list to file

Export existed DHCP reservation list to file.<br/><br/>The interface requires one of the permissions: <br/>Site Settings Manager Modify<br/>Network Config Page Modify<br/>Site Device Manager Modify<br/><br/>The possible error code for the interface in the returned body is one of the following error codes (non generic error codes): <br/>-1005  -  Operation forbidden.<br/>-33004  -  Operation failed because other operations (site copying, restoring, template synchronizing, etc.) are being performed on this site. Please wait and try again later.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param omadacId Omada ID
 @param siteId Site ID
 @return DHCPReservationAPIExportDhcpReservationListToFileRequest
*/
func (a *DHCPReservationAPIService) ExportDhcpReservationListToFile(ctx context.Context, omadacId string, siteId string) DHCPReservationAPIExportDhcpReservationListToFileRequest {
	return DHCPReservationAPIExportDhcpReservationListToFileRequest{
		ApiService: a,
		ctx: ctx,
		omadacId: omadacId,
		siteId: siteId,
	}
}

// Execute executes the request
//  @return OperationResponseWithoutResult
func (a *DHCPReservationAPIService) ExportDhcpReservationListToFileExecute(r DHCPReservationAPIExportDhcpReservationListToFileRequest) (*OperationResponseWithoutResult, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *OperationResponseWithoutResult
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DHCPReservationAPIService.ExportDhcpReservationListToFile")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/openapi/v1/{omadacId}/sites/{siteId}/setting/service/files/dhcp/export"
	localVarPath = strings.Replace(localVarPath, "{"+"omadacId"+"}", url.PathEscape(parameterValueToString(r.omadacId, "omadacId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"siteId"+"}", url.PathEscape(parameterValueToString(r.siteId, "siteId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["AccessToken"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type DHCPReservationAPIGetDhcpReservationGridRequest struct {
	ctx context.Context
	ApiService DHCPReservationAPI
	omadacId string
	siteId string
	page *int32
	pageSize *int32
	sortsMac *string
	sortsIp *string
	sortsNetName *string
	sortsDescription *string
	sortsStatus *string
	searchKey *string
}

// Start page number. Start from 1.
func (r DHCPReservationAPIGetDhcpReservationGridRequest) Page(page int32) DHCPReservationAPIGetDhcpReservationGridRequest {
	r.page = &page
	return r
}

// Number of entries per page. It should be within the range of 1–1000.
func (r DHCPReservationAPIGetDhcpReservationGridRequest) PageSize(pageSize int32) DHCPReservationAPIGetDhcpReservationGridRequest {
	r.pageSize = &pageSize
	return r
}

// Sort parameter may be one of asc or desc. Optional parameter. If it is not carried, it means it is not sorted by this field. When there are more than one, the first one takes effect
func (r DHCPReservationAPIGetDhcpReservationGridRequest) SortsMac(sortsMac string) DHCPReservationAPIGetDhcpReservationGridRequest {
	r.sortsMac = &sortsMac
	return r
}

// Sort parameter may be one of asc or desc. Optional parameter. If it is not carried, it means it is not sorted by this field. When there are more than one, the first one takes effect
func (r DHCPReservationAPIGetDhcpReservationGridRequest) SortsIp(sortsIp string) DHCPReservationAPIGetDhcpReservationGridRequest {
	r.sortsIp = &sortsIp
	return r
}

// Sort parameter may be one of asc or desc. Optional parameter. If it is not carried, it means it is not sorted by this field. When there are more than one, the first one takes effect
func (r DHCPReservationAPIGetDhcpReservationGridRequest) SortsNetName(sortsNetName string) DHCPReservationAPIGetDhcpReservationGridRequest {
	r.sortsNetName = &sortsNetName
	return r
}

// Sort parameter may be one of asc or desc. Optional parameter. If it is not carried, it means it is not sorted by this field. When there are more than one, the first one takes effect
func (r DHCPReservationAPIGetDhcpReservationGridRequest) SortsDescription(sortsDescription string) DHCPReservationAPIGetDhcpReservationGridRequest {
	r.sortsDescription = &sortsDescription
	return r
}

// Sort parameter may be one of asc or desc. Optional parameter. If it is not carried, it means it is not sorted by this field. When there are more than one, the first one takes effect
func (r DHCPReservationAPIGetDhcpReservationGridRequest) SortsStatus(sortsStatus string) DHCPReservationAPIGetDhcpReservationGridRequest {
	r.sortsStatus = &sortsStatus
	return r
}

// Fuzzy query parameters, support field : mac, ip, description.
func (r DHCPReservationAPIGetDhcpReservationGridRequest) SearchKey(searchKey string) DHCPReservationAPIGetDhcpReservationGridRequest {
	r.searchKey = &searchKey
	return r
}

func (r DHCPReservationAPIGetDhcpReservationGridRequest) Execute() (*OperationResponseDhcpReservationOpenApiGridVODhcpReservationOpenApiVO, *http.Response, error) {
	return r.ApiService.GetDhcpReservationGridExecute(r)
}

/*
GetDhcpReservationGrid Get DHCP reservation list

Get DHCP reservation list of the site with the given omadacId and siteId.<br/><br/>The interface requires one of the permissions: <br/>Site Settings Manager View Only<br/>Network Config Page View Only<br/>Site Device Manager View Only<br/><br/>The possible error code for the interface in the returned body is one of the following error codes (non generic error codes): <br/>-33000  -  This site does not exist.<br/>-33004  -  Operation failed because other operations (site copying, restoring, template synchronizing, etc.) are being performed on this site. Please wait and try again later.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param omadacId Omada ID
 @param siteId Site ID
 @return DHCPReservationAPIGetDhcpReservationGridRequest
*/
func (a *DHCPReservationAPIService) GetDhcpReservationGrid(ctx context.Context, omadacId string, siteId string) DHCPReservationAPIGetDhcpReservationGridRequest {
	return DHCPReservationAPIGetDhcpReservationGridRequest{
		ApiService: a,
		ctx: ctx,
		omadacId: omadacId,
		siteId: siteId,
	}
}

// Execute executes the request
//  @return OperationResponseDhcpReservationOpenApiGridVODhcpReservationOpenApiVO
func (a *DHCPReservationAPIService) GetDhcpReservationGridExecute(r DHCPReservationAPIGetDhcpReservationGridRequest) (*OperationResponseDhcpReservationOpenApiGridVODhcpReservationOpenApiVO, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *OperationResponseDhcpReservationOpenApiGridVODhcpReservationOpenApiVO
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DHCPReservationAPIService.GetDhcpReservationGrid")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/openapi/v1/{omadacId}/sites/{siteId}/setting/service/dhcp"
	localVarPath = strings.Replace(localVarPath, "{"+"omadacId"+"}", url.PathEscape(parameterValueToString(r.omadacId, "omadacId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"siteId"+"}", url.PathEscape(parameterValueToString(r.siteId, "siteId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.page == nil {
		return localVarReturnValue, nil, reportError("page is required and must be specified")
	}
	if r.pageSize == nil {
		return localVarReturnValue, nil, reportError("pageSize is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "page", r.page, "form", "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "pageSize", r.pageSize, "form", "")
	if r.sortsMac != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "sorts.mac", r.sortsMac, "form", "")
	}
	if r.sortsIp != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "sorts.ip", r.sortsIp, "form", "")
	}
	if r.sortsNetName != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "sorts.netName", r.sortsNetName, "form", "")
	}
	if r.sortsDescription != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "sorts.description", r.sortsDescription, "form", "")
	}
	if r.sortsStatus != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "sorts.status", r.sortsStatus, "form", "")
	}
	if r.searchKey != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "searchKey", r.searchKey, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["AccessToken"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type DHCPReservationAPIGetGridAllDhcpUserListRequest struct {
	ctx context.Context
	ApiService DHCPReservationAPI
	omadacId string
	siteId string
	page *int32
	pageSize *int32
}

// Start page number. Start from 1.
func (r DHCPReservationAPIGetGridAllDhcpUserListRequest) Page(page int32) DHCPReservationAPIGetGridAllDhcpUserListRequest {
	r.page = &page
	return r
}

// Number of entries per page. It should be within the range of 1–1000.
func (r DHCPReservationAPIGetGridAllDhcpUserListRequest) PageSize(pageSize int32) DHCPReservationAPIGetGridAllDhcpUserListRequest {
	r.pageSize = &pageSize
	return r
}

func (r DHCPReservationAPIGetGridAllDhcpUserListRequest) Execute() (*OperationResponseDhcpUserGridVODhcpUserVO, *http.Response, error) {
	return r.ApiService.GetGridAllDhcpUserListExecute(r)
}

/*
GetGridAllDhcpUserList Get the dhcp user list of all servers

Get the dhcp user list of all servers.<br/><br/>The interface requires one of the permissions: <br/>Site Settings Manager View Only<br/>Network Config Page View Only

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param omadacId Omada ID
 @param siteId Site ID
 @return DHCPReservationAPIGetGridAllDhcpUserListRequest
*/
func (a *DHCPReservationAPIService) GetGridAllDhcpUserList(ctx context.Context, omadacId string, siteId string) DHCPReservationAPIGetGridAllDhcpUserListRequest {
	return DHCPReservationAPIGetGridAllDhcpUserListRequest{
		ApiService: a,
		ctx: ctx,
		omadacId: omadacId,
		siteId: siteId,
	}
}

// Execute executes the request
//  @return OperationResponseDhcpUserGridVODhcpUserVO
func (a *DHCPReservationAPIService) GetGridAllDhcpUserListExecute(r DHCPReservationAPIGetGridAllDhcpUserListRequest) (*OperationResponseDhcpUserGridVODhcpUserVO, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *OperationResponseDhcpUserGridVODhcpUserVO
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DHCPReservationAPIService.GetGridAllDhcpUserList")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/openapi/v1/{omadacId}/sites/{siteId}/setting/service/dhcp/user-list"
	localVarPath = strings.Replace(localVarPath, "{"+"omadacId"+"}", url.PathEscape(parameterValueToString(r.omadacId, "omadacId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"siteId"+"}", url.PathEscape(parameterValueToString(r.siteId, "siteId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.page == nil {
		return localVarReturnValue, nil, reportError("page is required and must be specified")
	}
	if r.pageSize == nil {
		return localVarReturnValue, nil, reportError("pageSize is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "page", r.page, "form", "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "pageSize", r.pageSize, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["AccessToken"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type DHCPReservationAPIImportDhcpReservationListFromFileRequest struct {
	ctx context.Context
	ApiService DHCPReservationAPI
	omadacId string
	siteId string
	importDhcpReservationListFromFileRequest *ImportDhcpReservationListFromFileRequest
}

func (r DHCPReservationAPIImportDhcpReservationListFromFileRequest) ImportDhcpReservationListFromFileRequest(importDhcpReservationListFromFileRequest ImportDhcpReservationListFromFileRequest) DHCPReservationAPIImportDhcpReservationListFromFileRequest {
	r.importDhcpReservationListFromFileRequest = &importDhcpReservationListFromFileRequest
	return r
}

func (r DHCPReservationAPIImportDhcpReservationListFromFileRequest) Execute() (*OperationResponseWithoutResult, *http.Response, error) {
	return r.ApiService.ImportDhcpReservationListFromFileExecute(r)
}

/*
ImportDhcpReservationListFromFile Import DHCP reservation list from file

Import DHCP reservation list from existed file.<br/><br/>The interface requires one of the permissions: <br/>Site Settings Manager Modify<br/>Network Config Page Modify<br/>Site Device Manager Modify<br/><br/>The possible error code for the interface in the returned body is one of the following error codes (non generic error codes): <br/>-33004  -  Operation failed because other operations (site copying, restoring, template synchronizing, etc.) are being performed on this site. Please wait and try again later.<br/>-33712  -  This file is empty.<br/>-33713  -  Failed to process the files.<br/>-34533  -  The uploaded file contains wrong-format content. Please download the error messages, modify your file as required and re-upload it.<br/>-34544  -  The format of the import file must be csv.<br/>-34545  -  The number of DHCP Reservation entries has reached the limit. The exceeding entries cannot be saved.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param omadacId Omada ID
 @param siteId Site ID
 @return DHCPReservationAPIImportDhcpReservationListFromFileRequest
*/
func (a *DHCPReservationAPIService) ImportDhcpReservationListFromFile(ctx context.Context, omadacId string, siteId string) DHCPReservationAPIImportDhcpReservationListFromFileRequest {
	return DHCPReservationAPIImportDhcpReservationListFromFileRequest{
		ApiService: a,
		ctx: ctx,
		omadacId: omadacId,
		siteId: siteId,
	}
}

// Execute executes the request
//  @return OperationResponseWithoutResult
func (a *DHCPReservationAPIService) ImportDhcpReservationListFromFileExecute(r DHCPReservationAPIImportDhcpReservationListFromFileRequest) (*OperationResponseWithoutResult, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *OperationResponseWithoutResult
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DHCPReservationAPIService.ImportDhcpReservationListFromFile")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/openapi/v1/{omadacId}/sites/{siteId}/setting/service/files/dhcp/import"
	localVarPath = strings.Replace(localVarPath, "{"+"omadacId"+"}", url.PathEscape(parameterValueToString(r.omadacId, "omadacId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"siteId"+"}", url.PathEscape(parameterValueToString(r.siteId, "siteId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.importDhcpReservationListFromFileRequest
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["AccessToken"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type DHCPReservationAPIModifyDhcpReservationRequest struct {
	ctx context.Context
	ApiService DHCPReservationAPI
	omadacId string
	siteId string
	mac string
	createDhcpReservationOpenApiVO *CreateDhcpReservationOpenApiVO
}

func (r DHCPReservationAPIModifyDhcpReservationRequest) CreateDhcpReservationOpenApiVO(createDhcpReservationOpenApiVO CreateDhcpReservationOpenApiVO) DHCPReservationAPIModifyDhcpReservationRequest {
	r.createDhcpReservationOpenApiVO = &createDhcpReservationOpenApiVO
	return r
}

func (r DHCPReservationAPIModifyDhcpReservationRequest) Execute() (*OperationResponseWithoutResult, *http.Response, error) {
	return r.ApiService.ModifyDhcpReservationExecute(r)
}

/*
ModifyDhcpReservation Modify an exist DHCP reservation

Modify an exist DHCP reservation with the given params.<br/><br/>The interface requires one of the permissions: <br/>Site Settings Manager Modify<br/>Network Config Page Modify<br/>Site Device Manager Modify<br/><br/>The possible error code for the interface in the returned body is one of the following error codes (non generic error codes): <br/>-33000  -  This site does not exist.<br/>-33004  -  Operation failed because other operations (site copying, restoring, template synchronizing, etc.) are being performed on this site. Please wait and try again later.<br/>-33503  -  This network does not exist.<br/>-34511  -  The number of DHCP Reservation entries has reached the limit.<br/>-34512  -  Invalid network. Please select a network with the purpose selected as Interface.<br/>-34513  -  Enter an IP address within the Network IP range.<br/>-34514  -  This IP address conflicts with an existing DHCP Reservation entry.<br/>-34515  -  This MAC address conflicts with an existing DHCP Reservation entry.<br/>-34520  -  The LAN network in this entry does not exist, please reconfigure the DHCP reservation entry.<br/>-34522  -  This IP address of DHCP Reservation conflicts with a reserved static IP-MAC binding.<br/>-34543  -  The IP cannot be the same as the LAN network IP.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param omadacId Omada ID
 @param siteId Site ID
 @param mac MAC address of the DHCP reservation, format: AA-BB-CC-11-22-33.
 @return DHCPReservationAPIModifyDhcpReservationRequest
*/
func (a *DHCPReservationAPIService) ModifyDhcpReservation(ctx context.Context, omadacId string, siteId string, mac string) DHCPReservationAPIModifyDhcpReservationRequest {
	return DHCPReservationAPIModifyDhcpReservationRequest{
		ApiService: a,
		ctx: ctx,
		omadacId: omadacId,
		siteId: siteId,
		mac: mac,
	}
}

// Execute executes the request
//  @return OperationResponseWithoutResult
func (a *DHCPReservationAPIService) ModifyDhcpReservationExecute(r DHCPReservationAPIModifyDhcpReservationRequest) (*OperationResponseWithoutResult, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPatch
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *OperationResponseWithoutResult
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DHCPReservationAPIService.ModifyDhcpReservation")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/openapi/v1/{omadacId}/sites/{siteId}/setting/service/dhcp/{mac}"
	localVarPath = strings.Replace(localVarPath, "{"+"omadacId"+"}", url.PathEscape(parameterValueToString(r.omadacId, "omadacId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"siteId"+"}", url.PathEscape(parameterValueToString(r.siteId, "siteId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"mac"+"}", url.PathEscape(parameterValueToString(r.mac, "mac")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.createDhcpReservationOpenApiVO == nil {
		return localVarReturnValue, nil, reportError("createDhcpReservationOpenApiVO is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.createDhcpReservationOpenApiVO
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["AccessToken"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type DHCPReservationAPIReservationFromDhcpUserListRequest struct {
	ctx context.Context
	ApiService DHCPReservationAPI
	omadacId string
	siteId string
	dhcpUserFilterVO *DhcpUserFilterVO
}

func (r DHCPReservationAPIReservationFromDhcpUserListRequest) DhcpUserFilterVO(dhcpUserFilterVO DhcpUserFilterVO) DHCPReservationAPIReservationFromDhcpUserListRequest {
	r.dhcpUserFilterVO = &dhcpUserFilterVO
	return r
}

func (r DHCPReservationAPIReservationFromDhcpUserListRequest) Execute() (*OperationResponseDhcpReservationErrorVO, *http.Response, error) {
	return r.ApiService.ReservationFromDhcpUserListExecute(r)
}

/*
ReservationFromDhcpUserList Reservation From Dhcp User List

Reservation From Dhcp User List.<br/><br/>The interface requires one of the permissions: <br/>Site Settings Manager View Only<br/>Network Config Page View Only

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param omadacId Omada ID
 @param siteId Site ID
 @return DHCPReservationAPIReservationFromDhcpUserListRequest
*/
func (a *DHCPReservationAPIService) ReservationFromDhcpUserList(ctx context.Context, omadacId string, siteId string) DHCPReservationAPIReservationFromDhcpUserListRequest {
	return DHCPReservationAPIReservationFromDhcpUserListRequest{
		ApiService: a,
		ctx: ctx,
		omadacId: omadacId,
		siteId: siteId,
	}
}

// Execute executes the request
//  @return OperationResponseDhcpReservationErrorVO
func (a *DHCPReservationAPIService) ReservationFromDhcpUserListExecute(r DHCPReservationAPIReservationFromDhcpUserListRequest) (*OperationResponseDhcpReservationErrorVO, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *OperationResponseDhcpReservationErrorVO
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DHCPReservationAPIService.ReservationFromDhcpUserList")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/openapi/v1/{omadacId}/sites/{siteId}/setting/service/dhcp/user-list/reservation"
	localVarPath = strings.Replace(localVarPath, "{"+"omadacId"+"}", url.PathEscape(parameterValueToString(r.omadacId, "omadacId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"siteId"+"}", url.PathEscape(parameterValueToString(r.siteId, "siteId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.dhcpUserFilterVO == nil {
		return localVarReturnValue, nil, reportError("dhcpUserFilterVO is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.dhcpUserFilterVO
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["AccessToken"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
