/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PortScheduleQueryOpenApiVO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PortScheduleQueryOpenApiVO{}

// PortScheduleQueryOpenApiVO struct for PortScheduleQueryOpenApiVO
type PortScheduleQueryOpenApiVO struct {
	// Port Schedule individual ID.
	Id *string `json:"id,omitempty"`
	// Port Schedule Name should contain 1 to 128 characters.
	Name string `json:"name" validate:"regexp=^[^ ]$|^[^ ].{0,126}[^ ]$"`
	// Show Poe Schedule next execution timestamp.
	NextExecute *int64 `json:"nextExecute,omitempty"`
	// When notInDst is true, Not displayed in DST.
	NotInDst *bool `json:"notInDst,omitempty"`
	// Key:MAC(\"String\"), Value:Set of Ports(\"Integer\")
	PortsMap map[string][]int32 `json:"portsMap"`
	// Site ID
	SiteId *string `json:"siteId,omitempty"`
	// Port Schedule Status.
	Status bool `json:"status"`
	// Time Range ID, cannot be empty.
	TurnOnTime string `json:"turnOnTime"`
}

type _PortScheduleQueryOpenApiVO PortScheduleQueryOpenApiVO

// NewPortScheduleQueryOpenApiVO instantiates a new PortScheduleQueryOpenApiVO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPortScheduleQueryOpenApiVO(name string, portsMap map[string][]int32, status bool, turnOnTime string) *PortScheduleQueryOpenApiVO {
	this := PortScheduleQueryOpenApiVO{}
	this.Name = name
	this.PortsMap = portsMap
	this.Status = status
	this.TurnOnTime = turnOnTime
	return &this
}

// NewPortScheduleQueryOpenApiVOWithDefaults instantiates a new PortScheduleQueryOpenApiVO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPortScheduleQueryOpenApiVOWithDefaults() *PortScheduleQueryOpenApiVO {
	this := PortScheduleQueryOpenApiVO{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PortScheduleQueryOpenApiVO) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PortScheduleQueryOpenApiVO) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PortScheduleQueryOpenApiVO) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PortScheduleQueryOpenApiVO) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value
func (o *PortScheduleQueryOpenApiVO) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PortScheduleQueryOpenApiVO) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PortScheduleQueryOpenApiVO) SetName(v string) {
	o.Name = v
}

// GetNextExecute returns the NextExecute field value if set, zero value otherwise.
func (o *PortScheduleQueryOpenApiVO) GetNextExecute() int64 {
	if o == nil || IsNil(o.NextExecute) {
		var ret int64
		return ret
	}
	return *o.NextExecute
}

// GetNextExecuteOk returns a tuple with the NextExecute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PortScheduleQueryOpenApiVO) GetNextExecuteOk() (*int64, bool) {
	if o == nil || IsNil(o.NextExecute) {
		return nil, false
	}
	return o.NextExecute, true
}

// HasNextExecute returns a boolean if a field has been set.
func (o *PortScheduleQueryOpenApiVO) HasNextExecute() bool {
	if o != nil && !IsNil(o.NextExecute) {
		return true
	}

	return false
}

// SetNextExecute gets a reference to the given int64 and assigns it to the NextExecute field.
func (o *PortScheduleQueryOpenApiVO) SetNextExecute(v int64) {
	o.NextExecute = &v
}

// GetNotInDst returns the NotInDst field value if set, zero value otherwise.
func (o *PortScheduleQueryOpenApiVO) GetNotInDst() bool {
	if o == nil || IsNil(o.NotInDst) {
		var ret bool
		return ret
	}
	return *o.NotInDst
}

// GetNotInDstOk returns a tuple with the NotInDst field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PortScheduleQueryOpenApiVO) GetNotInDstOk() (*bool, bool) {
	if o == nil || IsNil(o.NotInDst) {
		return nil, false
	}
	return o.NotInDst, true
}

// HasNotInDst returns a boolean if a field has been set.
func (o *PortScheduleQueryOpenApiVO) HasNotInDst() bool {
	if o != nil && !IsNil(o.NotInDst) {
		return true
	}

	return false
}

// SetNotInDst gets a reference to the given bool and assigns it to the NotInDst field.
func (o *PortScheduleQueryOpenApiVO) SetNotInDst(v bool) {
	o.NotInDst = &v
}

// GetPortsMap returns the PortsMap field value
func (o *PortScheduleQueryOpenApiVO) GetPortsMap() map[string][]int32 {
	if o == nil {
		var ret map[string][]int32
		return ret
	}

	return o.PortsMap
}

// GetPortsMapOk returns a tuple with the PortsMap field value
// and a boolean to check if the value has been set.
func (o *PortScheduleQueryOpenApiVO) GetPortsMapOk() (*map[string][]int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PortsMap, true
}

// SetPortsMap sets field value
func (o *PortScheduleQueryOpenApiVO) SetPortsMap(v map[string][]int32) {
	o.PortsMap = v
}

// GetSiteId returns the SiteId field value if set, zero value otherwise.
func (o *PortScheduleQueryOpenApiVO) GetSiteId() string {
	if o == nil || IsNil(o.SiteId) {
		var ret string
		return ret
	}
	return *o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PortScheduleQueryOpenApiVO) GetSiteIdOk() (*string, bool) {
	if o == nil || IsNil(o.SiteId) {
		return nil, false
	}
	return o.SiteId, true
}

// HasSiteId returns a boolean if a field has been set.
func (o *PortScheduleQueryOpenApiVO) HasSiteId() bool {
	if o != nil && !IsNil(o.SiteId) {
		return true
	}

	return false
}

// SetSiteId gets a reference to the given string and assigns it to the SiteId field.
func (o *PortScheduleQueryOpenApiVO) SetSiteId(v string) {
	o.SiteId = &v
}

// GetStatus returns the Status field value
func (o *PortScheduleQueryOpenApiVO) GetStatus() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PortScheduleQueryOpenApiVO) GetStatusOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PortScheduleQueryOpenApiVO) SetStatus(v bool) {
	o.Status = v
}

// GetTurnOnTime returns the TurnOnTime field value
func (o *PortScheduleQueryOpenApiVO) GetTurnOnTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TurnOnTime
}

// GetTurnOnTimeOk returns a tuple with the TurnOnTime field value
// and a boolean to check if the value has been set.
func (o *PortScheduleQueryOpenApiVO) GetTurnOnTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TurnOnTime, true
}

// SetTurnOnTime sets field value
func (o *PortScheduleQueryOpenApiVO) SetTurnOnTime(v string) {
	o.TurnOnTime = v
}

func (o PortScheduleQueryOpenApiVO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PortScheduleQueryOpenApiVO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.NextExecute) {
		toSerialize["nextExecute"] = o.NextExecute
	}
	if !IsNil(o.NotInDst) {
		toSerialize["notInDst"] = o.NotInDst
	}
	toSerialize["portsMap"] = o.PortsMap
	if !IsNil(o.SiteId) {
		toSerialize["siteId"] = o.SiteId
	}
	toSerialize["status"] = o.Status
	toSerialize["turnOnTime"] = o.TurnOnTime
	return toSerialize, nil
}

func (o *PortScheduleQueryOpenApiVO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"portsMap",
		"status",
		"turnOnTime",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPortScheduleQueryOpenApiVO := _PortScheduleQueryOpenApiVO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPortScheduleQueryOpenApiVO)

	if err != nil {
		return err
	}

	*o = PortScheduleQueryOpenApiVO(varPortScheduleQueryOpenApiVO)

	return err
}

type NullablePortScheduleQueryOpenApiVO struct {
	value *PortScheduleQueryOpenApiVO
	isSet bool
}

func (v NullablePortScheduleQueryOpenApiVO) Get() *PortScheduleQueryOpenApiVO {
	return v.value
}

func (v *NullablePortScheduleQueryOpenApiVO) Set(val *PortScheduleQueryOpenApiVO) {
	v.value = val
	v.isSet = true
}

func (v NullablePortScheduleQueryOpenApiVO) IsSet() bool {
	return v.isSet
}

func (v *NullablePortScheduleQueryOpenApiVO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePortScheduleQueryOpenApiVO(val *PortScheduleQueryOpenApiVO) *NullablePortScheduleQueryOpenApiVO {
	return &NullablePortScheduleQueryOpenApiVO{value: val, isSet: true}
}

func (v NullablePortScheduleQueryOpenApiVO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePortScheduleQueryOpenApiVO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


