/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
)

// checks if the PlanningHistoryListVO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlanningHistoryListVO{}

// PlanningHistoryListVO struct for PlanningHistoryListVO
type PlanningHistoryListVO struct {
	HistoryList []map[string]interface{} `json:"historyList,omitempty"`
}

// NewPlanningHistoryListVO instantiates a new PlanningHistoryListVO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlanningHistoryListVO() *PlanningHistoryListVO {
	this := PlanningHistoryListVO{}
	return &this
}

// NewPlanningHistoryListVOWithDefaults instantiates a new PlanningHistoryListVO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlanningHistoryListVOWithDefaults() *PlanningHistoryListVO {
	this := PlanningHistoryListVO{}
	return &this
}

// GetHistoryList returns the HistoryList field value if set, zero value otherwise.
func (o *PlanningHistoryListVO) GetHistoryList() []map[string]interface{} {
	if o == nil || IsNil(o.HistoryList) {
		var ret []map[string]interface{}
		return ret
	}
	return o.HistoryList
}

// GetHistoryListOk returns a tuple with the HistoryList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanningHistoryListVO) GetHistoryListOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.HistoryList) {
		return nil, false
	}
	return o.HistoryList, true
}

// HasHistoryList returns a boolean if a field has been set.
func (o *PlanningHistoryListVO) HasHistoryList() bool {
	if o != nil && !IsNil(o.HistoryList) {
		return true
	}

	return false
}

// SetHistoryList gets a reference to the given []map[string]interface{} and assigns it to the HistoryList field.
func (o *PlanningHistoryListVO) SetHistoryList(v []map[string]interface{}) {
	o.HistoryList = v
}

func (o PlanningHistoryListVO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlanningHistoryListVO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HistoryList) {
		toSerialize["historyList"] = o.HistoryList
	}
	return toSerialize, nil
}

type NullablePlanningHistoryListVO struct {
	value *PlanningHistoryListVO
	isSet bool
}

func (v NullablePlanningHistoryListVO) Get() *PlanningHistoryListVO {
	return v.value
}

func (v *NullablePlanningHistoryListVO) Set(val *PlanningHistoryListVO) {
	v.value = val
	v.isSet = true
}

func (v NullablePlanningHistoryListVO) IsSet() bool {
	return v.isSet
}

func (v *NullablePlanningHistoryListVO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlanningHistoryListVO(val *PlanningHistoryListVO) *NullablePlanningHistoryListVO {
	return &NullablePlanningHistoryListVO{value: val, isSet: true}
}

func (v NullablePlanningHistoryListVO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlanningHistoryListVO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


