/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
)

// checks if the AddMonitorDeviceList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddMonitorDeviceList{}

// AddMonitorDeviceList struct for AddMonitorDeviceList
type AddMonitorDeviceList struct {
	// The device to be added to the monitor list
	AddDeviceList []MonitorDevice `json:"addDeviceList,omitempty"`
}

// NewAddMonitorDeviceList instantiates a new AddMonitorDeviceList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddMonitorDeviceList() *AddMonitorDeviceList {
	this := AddMonitorDeviceList{}
	return &this
}

// NewAddMonitorDeviceListWithDefaults instantiates a new AddMonitorDeviceList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddMonitorDeviceListWithDefaults() *AddMonitorDeviceList {
	this := AddMonitorDeviceList{}
	return &this
}

// GetAddDeviceList returns the AddDeviceList field value if set, zero value otherwise.
func (o *AddMonitorDeviceList) GetAddDeviceList() []MonitorDevice {
	if o == nil || IsNil(o.AddDeviceList) {
		var ret []MonitorDevice
		return ret
	}
	return o.AddDeviceList
}

// GetAddDeviceListOk returns a tuple with the AddDeviceList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddMonitorDeviceList) GetAddDeviceListOk() ([]MonitorDevice, bool) {
	if o == nil || IsNil(o.AddDeviceList) {
		return nil, false
	}
	return o.AddDeviceList, true
}

// HasAddDeviceList returns a boolean if a field has been set.
func (o *AddMonitorDeviceList) HasAddDeviceList() bool {
	if o != nil && !IsNil(o.AddDeviceList) {
		return true
	}

	return false
}

// SetAddDeviceList gets a reference to the given []MonitorDevice and assigns it to the AddDeviceList field.
func (o *AddMonitorDeviceList) SetAddDeviceList(v []MonitorDevice) {
	o.AddDeviceList = v
}

func (o AddMonitorDeviceList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddMonitorDeviceList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AddDeviceList) {
		toSerialize["addDeviceList"] = o.AddDeviceList
	}
	return toSerialize, nil
}

type NullableAddMonitorDeviceList struct {
	value *AddMonitorDeviceList
	isSet bool
}

func (v NullableAddMonitorDeviceList) Get() *AddMonitorDeviceList {
	return v.value
}

func (v *NullableAddMonitorDeviceList) Set(val *AddMonitorDeviceList) {
	v.value = val
	v.isSet = true
}

func (v NullableAddMonitorDeviceList) IsSet() bool {
	return v.isSet
}

func (v *NullableAddMonitorDeviceList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddMonitorDeviceList(val *AddMonitorDeviceList) *NullableAddMonitorDeviceList {
	return &NullableAddMonitorDeviceList{value: val, isSet: true}
}

func (v NullableAddMonitorDeviceList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddMonitorDeviceList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


