/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CheckMappedNetwork type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckMappedNetwork{}

// CheckMappedNetwork struct for CheckMappedNetwork
type CheckMappedNetwork struct {
	// A list of current mapped network of the SD-WAN group
	MappedNetworks []string `json:"mappedNetworks,omitempty"`
	// A list of members of the SD-WAN group
	MemberList []SdWanMemberSelected `json:"memberList"`
	// The IP Subnet of the modified network
	ModifiedNetwork string `json:"modifiedNetwork"`
}

type _CheckMappedNetwork CheckMappedNetwork

// NewCheckMappedNetwork instantiates a new CheckMappedNetwork object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckMappedNetwork(memberList []SdWanMemberSelected, modifiedNetwork string) *CheckMappedNetwork {
	this := CheckMappedNetwork{}
	this.MemberList = memberList
	this.ModifiedNetwork = modifiedNetwork
	return &this
}

// NewCheckMappedNetworkWithDefaults instantiates a new CheckMappedNetwork object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckMappedNetworkWithDefaults() *CheckMappedNetwork {
	this := CheckMappedNetwork{}
	return &this
}

// GetMappedNetworks returns the MappedNetworks field value if set, zero value otherwise.
func (o *CheckMappedNetwork) GetMappedNetworks() []string {
	if o == nil || IsNil(o.MappedNetworks) {
		var ret []string
		return ret
	}
	return o.MappedNetworks
}

// GetMappedNetworksOk returns a tuple with the MappedNetworks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckMappedNetwork) GetMappedNetworksOk() ([]string, bool) {
	if o == nil || IsNil(o.MappedNetworks) {
		return nil, false
	}
	return o.MappedNetworks, true
}

// HasMappedNetworks returns a boolean if a field has been set.
func (o *CheckMappedNetwork) HasMappedNetworks() bool {
	if o != nil && !IsNil(o.MappedNetworks) {
		return true
	}

	return false
}

// SetMappedNetworks gets a reference to the given []string and assigns it to the MappedNetworks field.
func (o *CheckMappedNetwork) SetMappedNetworks(v []string) {
	o.MappedNetworks = v
}

// GetMemberList returns the MemberList field value
func (o *CheckMappedNetwork) GetMemberList() []SdWanMemberSelected {
	if o == nil {
		var ret []SdWanMemberSelected
		return ret
	}

	return o.MemberList
}

// GetMemberListOk returns a tuple with the MemberList field value
// and a boolean to check if the value has been set.
func (o *CheckMappedNetwork) GetMemberListOk() ([]SdWanMemberSelected, bool) {
	if o == nil {
		return nil, false
	}
	return o.MemberList, true
}

// SetMemberList sets field value
func (o *CheckMappedNetwork) SetMemberList(v []SdWanMemberSelected) {
	o.MemberList = v
}

// GetModifiedNetwork returns the ModifiedNetwork field value
func (o *CheckMappedNetwork) GetModifiedNetwork() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ModifiedNetwork
}

// GetModifiedNetworkOk returns a tuple with the ModifiedNetwork field value
// and a boolean to check if the value has been set.
func (o *CheckMappedNetwork) GetModifiedNetworkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModifiedNetwork, true
}

// SetModifiedNetwork sets field value
func (o *CheckMappedNetwork) SetModifiedNetwork(v string) {
	o.ModifiedNetwork = v
}

func (o CheckMappedNetwork) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckMappedNetwork) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MappedNetworks) {
		toSerialize["mappedNetworks"] = o.MappedNetworks
	}
	toSerialize["memberList"] = o.MemberList
	toSerialize["modifiedNetwork"] = o.ModifiedNetwork
	return toSerialize, nil
}

func (o *CheckMappedNetwork) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"memberList",
		"modifiedNetwork",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCheckMappedNetwork := _CheckMappedNetwork{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCheckMappedNetwork)

	if err != nil {
		return err
	}

	*o = CheckMappedNetwork(varCheckMappedNetwork)

	return err
}

type NullableCheckMappedNetwork struct {
	value *CheckMappedNetwork
	isSet bool
}

func (v NullableCheckMappedNetwork) Get() *CheckMappedNetwork {
	return v.value
}

func (v *NullableCheckMappedNetwork) Set(val *CheckMappedNetwork) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckMappedNetwork) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckMappedNetwork) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckMappedNetwork(val *CheckMappedNetwork) *NullableCheckMappedNetwork {
	return &NullableCheckMappedNetwork{value: val, isSet: true}
}

func (v NullableCheckMappedNetwork) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckMappedNetwork) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


