/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AutoConfigOpenApiVO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AutoConfigOpenApiVO{}

// AutoConfigOpenApiVO It is required when [configType] is 0.
type AutoConfigOpenApiVO struct {
	// Location index, which refers to \"Get location and ISP info\".
	Location int32 `json:"location"`
	// MobileISP index, which refers to \"Get location and ISP info\".
	MobileISP int32 `json:"mobileISP"`
}

type _AutoConfigOpenApiVO AutoConfigOpenApiVO

// NewAutoConfigOpenApiVO instantiates a new AutoConfigOpenApiVO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAutoConfigOpenApiVO(location int32, mobileISP int32) *AutoConfigOpenApiVO {
	this := AutoConfigOpenApiVO{}
	this.Location = location
	this.MobileISP = mobileISP
	return &this
}

// NewAutoConfigOpenApiVOWithDefaults instantiates a new AutoConfigOpenApiVO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAutoConfigOpenApiVOWithDefaults() *AutoConfigOpenApiVO {
	this := AutoConfigOpenApiVO{}
	return &this
}

// GetLocation returns the Location field value
func (o *AutoConfigOpenApiVO) GetLocation() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Location
}

// GetLocationOk returns a tuple with the Location field value
// and a boolean to check if the value has been set.
func (o *AutoConfigOpenApiVO) GetLocationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Location, true
}

// SetLocation sets field value
func (o *AutoConfigOpenApiVO) SetLocation(v int32) {
	o.Location = v
}

// GetMobileISP returns the MobileISP field value
func (o *AutoConfigOpenApiVO) GetMobileISP() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MobileISP
}

// GetMobileISPOk returns a tuple with the MobileISP field value
// and a boolean to check if the value has been set.
func (o *AutoConfigOpenApiVO) GetMobileISPOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MobileISP, true
}

// SetMobileISP sets field value
func (o *AutoConfigOpenApiVO) SetMobileISP(v int32) {
	o.MobileISP = v
}

func (o AutoConfigOpenApiVO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AutoConfigOpenApiVO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["location"] = o.Location
	toSerialize["mobileISP"] = o.MobileISP
	return toSerialize, nil
}

func (o *AutoConfigOpenApiVO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"location",
		"mobileISP",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAutoConfigOpenApiVO := _AutoConfigOpenApiVO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAutoConfigOpenApiVO)

	if err != nil {
		return err
	}

	*o = AutoConfigOpenApiVO(varAutoConfigOpenApiVO)

	return err
}

type NullableAutoConfigOpenApiVO struct {
	value *AutoConfigOpenApiVO
	isSet bool
}

func (v NullableAutoConfigOpenApiVO) Get() *AutoConfigOpenApiVO {
	return v.value
}

func (v *NullableAutoConfigOpenApiVO) Set(val *AutoConfigOpenApiVO) {
	v.value = val
	v.isSet = true
}

func (v NullableAutoConfigOpenApiVO) IsSet() bool {
	return v.isSet
}

func (v *NullableAutoConfigOpenApiVO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAutoConfigOpenApiVO(val *AutoConfigOpenApiVO) *NullableAutoConfigOpenApiVO {
	return &NullableAutoConfigOpenApiVO{value: val, isSet: true}
}

func (v NullableAutoConfigOpenApiVO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAutoConfigOpenApiVO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


