/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Dot1xEapOpenApiVO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Dot1xEapOpenApiVO{}

// Dot1xEapOpenApiVO struct for Dot1xEapOpenApiVO
type Dot1xEapOpenApiVO struct {
	// Enabled eap ports
	Eaps []Dot1xEapSettingOpenApiVO `json:"eaps,omitempty"`
	// EAP 802.1x function enable status
	Enable bool `json:"enable"`
	// Format of the MAC address. MacFormat should be a value as follows: 0: aabbccddeeff, 1: aa-bb-cc-dd-ee-ff, 2: aa:bb:cc:dd:ee:ff, 3: AABBCCDDEEFF, 4: AA-BB-CC-DD-EE-FF, 5: AA:BB:CC:DD:EE:FF
	MacFormat *int32 `json:"macFormat,omitempty"`
	// This field represents radius profile ID. Radius profile can be created using 'Create a new Radius profile' ('Create a new Radius profile template') interface, and radius profile ID can be obtained from 'Get Radius profile list' ('Get Radius profile template list') interface
	RadiusProfileId *string `json:"radiusProfileId,omitempty"`
}

type _Dot1xEapOpenApiVO Dot1xEapOpenApiVO

// NewDot1xEapOpenApiVO instantiates a new Dot1xEapOpenApiVO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDot1xEapOpenApiVO(enable bool) *Dot1xEapOpenApiVO {
	this := Dot1xEapOpenApiVO{}
	this.Enable = enable
	return &this
}

// NewDot1xEapOpenApiVOWithDefaults instantiates a new Dot1xEapOpenApiVO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDot1xEapOpenApiVOWithDefaults() *Dot1xEapOpenApiVO {
	this := Dot1xEapOpenApiVO{}
	return &this
}

// GetEaps returns the Eaps field value if set, zero value otherwise.
func (o *Dot1xEapOpenApiVO) GetEaps() []Dot1xEapSettingOpenApiVO {
	if o == nil || IsNil(o.Eaps) {
		var ret []Dot1xEapSettingOpenApiVO
		return ret
	}
	return o.Eaps
}

// GetEapsOk returns a tuple with the Eaps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dot1xEapOpenApiVO) GetEapsOk() ([]Dot1xEapSettingOpenApiVO, bool) {
	if o == nil || IsNil(o.Eaps) {
		return nil, false
	}
	return o.Eaps, true
}

// HasEaps returns a boolean if a field has been set.
func (o *Dot1xEapOpenApiVO) HasEaps() bool {
	if o != nil && !IsNil(o.Eaps) {
		return true
	}

	return false
}

// SetEaps gets a reference to the given []Dot1xEapSettingOpenApiVO and assigns it to the Eaps field.
func (o *Dot1xEapOpenApiVO) SetEaps(v []Dot1xEapSettingOpenApiVO) {
	o.Eaps = v
}

// GetEnable returns the Enable field value
func (o *Dot1xEapOpenApiVO) GetEnable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enable
}

// GetEnableOk returns a tuple with the Enable field value
// and a boolean to check if the value has been set.
func (o *Dot1xEapOpenApiVO) GetEnableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enable, true
}

// SetEnable sets field value
func (o *Dot1xEapOpenApiVO) SetEnable(v bool) {
	o.Enable = v
}

// GetMacFormat returns the MacFormat field value if set, zero value otherwise.
func (o *Dot1xEapOpenApiVO) GetMacFormat() int32 {
	if o == nil || IsNil(o.MacFormat) {
		var ret int32
		return ret
	}
	return *o.MacFormat
}

// GetMacFormatOk returns a tuple with the MacFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dot1xEapOpenApiVO) GetMacFormatOk() (*int32, bool) {
	if o == nil || IsNil(o.MacFormat) {
		return nil, false
	}
	return o.MacFormat, true
}

// HasMacFormat returns a boolean if a field has been set.
func (o *Dot1xEapOpenApiVO) HasMacFormat() bool {
	if o != nil && !IsNil(o.MacFormat) {
		return true
	}

	return false
}

// SetMacFormat gets a reference to the given int32 and assigns it to the MacFormat field.
func (o *Dot1xEapOpenApiVO) SetMacFormat(v int32) {
	o.MacFormat = &v
}

// GetRadiusProfileId returns the RadiusProfileId field value if set, zero value otherwise.
func (o *Dot1xEapOpenApiVO) GetRadiusProfileId() string {
	if o == nil || IsNil(o.RadiusProfileId) {
		var ret string
		return ret
	}
	return *o.RadiusProfileId
}

// GetRadiusProfileIdOk returns a tuple with the RadiusProfileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dot1xEapOpenApiVO) GetRadiusProfileIdOk() (*string, bool) {
	if o == nil || IsNil(o.RadiusProfileId) {
		return nil, false
	}
	return o.RadiusProfileId, true
}

// HasRadiusProfileId returns a boolean if a field has been set.
func (o *Dot1xEapOpenApiVO) HasRadiusProfileId() bool {
	if o != nil && !IsNil(o.RadiusProfileId) {
		return true
	}

	return false
}

// SetRadiusProfileId gets a reference to the given string and assigns it to the RadiusProfileId field.
func (o *Dot1xEapOpenApiVO) SetRadiusProfileId(v string) {
	o.RadiusProfileId = &v
}

func (o Dot1xEapOpenApiVO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Dot1xEapOpenApiVO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Eaps) {
		toSerialize["eaps"] = o.Eaps
	}
	toSerialize["enable"] = o.Enable
	if !IsNil(o.MacFormat) {
		toSerialize["macFormat"] = o.MacFormat
	}
	if !IsNil(o.RadiusProfileId) {
		toSerialize["radiusProfileId"] = o.RadiusProfileId
	}
	return toSerialize, nil
}

func (o *Dot1xEapOpenApiVO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enable",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDot1xEapOpenApiVO := _Dot1xEapOpenApiVO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDot1xEapOpenApiVO)

	if err != nil {
		return err
	}

	*o = Dot1xEapOpenApiVO(varDot1xEapOpenApiVO)

	return err
}

type NullableDot1xEapOpenApiVO struct {
	value *Dot1xEapOpenApiVO
	isSet bool
}

func (v NullableDot1xEapOpenApiVO) Get() *Dot1xEapOpenApiVO {
	return v.value
}

func (v *NullableDot1xEapOpenApiVO) Set(val *Dot1xEapOpenApiVO) {
	v.value = val
	v.isSet = true
}

func (v NullableDot1xEapOpenApiVO) IsSet() bool {
	return v.isSet
}

func (v *NullableDot1xEapOpenApiVO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDot1xEapOpenApiVO(val *Dot1xEapOpenApiVO) *NullableDot1xEapOpenApiVO {
	return &NullableDot1xEapOpenApiVO{value: val, isSet: true}
}

func (v NullableDot1xEapOpenApiVO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDot1xEapOpenApiVO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


