/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DomainOpenApiVO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainOpenApiVO{}

// DomainOpenApiVO Domain info. Handle situations where there are ports, [type] value of 7 is required
type DomainOpenApiVO struct {
	// Domain address, should be a valid domain address
	Address string `json:"address"`
	// Domain description, description should contain 1 to 512 characters.
	Description *string `json:"description,omitempty" validate:"regexp=^$|^[^ ]$|^[^ ].{0,510}[^ ]$"`
	// Domain port, port should be within the range of 0-65535 or empty, e.g. 80,80-100
	Port *string `json:"port,omitempty"`
}

type _DomainOpenApiVO DomainOpenApiVO

// NewDomainOpenApiVO instantiates a new DomainOpenApiVO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainOpenApiVO(address string) *DomainOpenApiVO {
	this := DomainOpenApiVO{}
	this.Address = address
	return &this
}

// NewDomainOpenApiVOWithDefaults instantiates a new DomainOpenApiVO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainOpenApiVOWithDefaults() *DomainOpenApiVO {
	this := DomainOpenApiVO{}
	return &this
}

// GetAddress returns the Address field value
func (o *DomainOpenApiVO) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *DomainOpenApiVO) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *DomainOpenApiVO) SetAddress(v string) {
	o.Address = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *DomainOpenApiVO) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainOpenApiVO) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *DomainOpenApiVO) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *DomainOpenApiVO) SetDescription(v string) {
	o.Description = &v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *DomainOpenApiVO) GetPort() string {
	if o == nil || IsNil(o.Port) {
		var ret string
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainOpenApiVO) GetPortOk() (*string, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *DomainOpenApiVO) HasPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given string and assigns it to the Port field.
func (o *DomainOpenApiVO) SetPort(v string) {
	o.Port = &v
}

func (o DomainOpenApiVO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainOpenApiVO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	return toSerialize, nil
}

func (o *DomainOpenApiVO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDomainOpenApiVO := _DomainOpenApiVO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDomainOpenApiVO)

	if err != nil {
		return err
	}

	*o = DomainOpenApiVO(varDomainOpenApiVO)

	return err
}

type NullableDomainOpenApiVO struct {
	value *DomainOpenApiVO
	isSet bool
}

func (v NullableDomainOpenApiVO) Get() *DomainOpenApiVO {
	return v.value
}

func (v *NullableDomainOpenApiVO) Set(val *DomainOpenApiVO) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainOpenApiVO) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainOpenApiVO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainOpenApiVO(val *DomainOpenApiVO) *NullableDomainOpenApiVO {
	return &NullableDomainOpenApiVO{value: val, isSet: true}
}

func (v NullableDomainOpenApiVO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainOpenApiVO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


