/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
)

// checks if the DeviceNodeInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceNodeInfo{}

// DeviceNodeInfo Device Node info.
type DeviceNodeInfo struct {
	Ap *bool `json:"ap,omitempty"`
	ApInfo *APInfo `json:"apInfo,omitempty"`
	// Device real-time downloadRate
	DevRxRate *int64 `json:"devRxRate,omitempty"`
	// Device real-time uploadRate
	DevTxRate *int64 `json:"devTxRate,omitempty"`
	// Device type, 0: AP; 1: Switch; 2: Gateway.
	DeviceType *int32 `json:"deviceType,omitempty"`
	GatewayInfo *GatewayInfoEntity `json:"gatewayInfo,omitempty"`
	// 1~3: poor; 4~7: fair; 0: no data; 8~10 good.
	HealthScore *int32 `json:"healthScore,omitempty"`
	// Device IP
	Ip *string `json:"ip,omitempty"`
	// Device IPv6 list
	Ipv6List []string `json:"ipv6List,omitempty"`
	// Device MAC
	Mac *string `json:"mac,omitempty"`
	// Device model name
	Model *string `json:"model,omitempty"`
	// Model version of device,for example:3.0
	ModelVersion *string `json:"modelVersion,omitempty"`
	// Device name
	Name *string `json:"name,omitempty"`
	Osg *bool `json:"osg,omitempty"`
	Osw *bool `json:"osw,omitempty"`
	// Device model name with version
	ShowModel *string `json:"showModel,omitempty"`
	// Stack Group
	StackGroup *bool `json:"stackGroup,omitempty"`
	// Stack Id
	StackId *string `json:"stackId,omitempty"`
	// Status of device,status should be a value as follows: 0:Disconnected;1:Disconnected(Migrating);10:Provisioning;11:Configuring;12:Upgrading;13:Rebooting;14:Connected;15:Connected(Wireless);16:Connected(Migrating);17:Connected(Wireless,Migrating);20:Pending;21:Pending(Wireless);22:Adopting;23:Adopting(Wireless);24:Adopt Failed;25:Adopt Failed(Wireless);26:Managed By Others;27:Managed By Others(Wireless);30:Heartbeat Missed;31:Heartbeat Missed(Wireless);32:Heartbeat Missed(Migrating);33:Heartbeat Missed(Wireless,Migrating);40:Isolated;41:Isolated(Migrating);50:Slice Configuring
	Status *int32 `json:"status,omitempty"`
	// Device status should be a value as follows: 0: Disconnected; 1: Connected; 2: Pending; 3: Heartbeat Missed; 4: Isolated
	StatusCategory *int32 `json:"statusCategory,omitempty"`
	SwitchInfo *SwitchInfo `json:"switchInfo,omitempty"`
}

// NewDeviceNodeInfo instantiates a new DeviceNodeInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceNodeInfo() *DeviceNodeInfo {
	this := DeviceNodeInfo{}
	return &this
}

// NewDeviceNodeInfoWithDefaults instantiates a new DeviceNodeInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceNodeInfoWithDefaults() *DeviceNodeInfo {
	this := DeviceNodeInfo{}
	return &this
}

// GetAp returns the Ap field value if set, zero value otherwise.
func (o *DeviceNodeInfo) GetAp() bool {
	if o == nil || IsNil(o.Ap) {
		var ret bool
		return ret
	}
	return *o.Ap
}

// GetApOk returns a tuple with the Ap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceNodeInfo) GetApOk() (*bool, bool) {
	if o == nil || IsNil(o.Ap) {
		return nil, false
	}
	return o.Ap, true
}

// HasAp returns a boolean if a field has been set.
func (o *DeviceNodeInfo) HasAp() bool {
	if o != nil && !IsNil(o.Ap) {
		return true
	}

	return false
}

// SetAp gets a reference to the given bool and assigns it to the Ap field.
func (o *DeviceNodeInfo) SetAp(v bool) {
	o.Ap = &v
}

// GetApInfo returns the ApInfo field value if set, zero value otherwise.
func (o *DeviceNodeInfo) GetApInfo() APInfo {
	if o == nil || IsNil(o.ApInfo) {
		var ret APInfo
		return ret
	}
	return *o.ApInfo
}

// GetApInfoOk returns a tuple with the ApInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceNodeInfo) GetApInfoOk() (*APInfo, bool) {
	if o == nil || IsNil(o.ApInfo) {
		return nil, false
	}
	return o.ApInfo, true
}

// HasApInfo returns a boolean if a field has been set.
func (o *DeviceNodeInfo) HasApInfo() bool {
	if o != nil && !IsNil(o.ApInfo) {
		return true
	}

	return false
}

// SetApInfo gets a reference to the given APInfo and assigns it to the ApInfo field.
func (o *DeviceNodeInfo) SetApInfo(v APInfo) {
	o.ApInfo = &v
}

// GetDevRxRate returns the DevRxRate field value if set, zero value otherwise.
func (o *DeviceNodeInfo) GetDevRxRate() int64 {
	if o == nil || IsNil(o.DevRxRate) {
		var ret int64
		return ret
	}
	return *o.DevRxRate
}

// GetDevRxRateOk returns a tuple with the DevRxRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceNodeInfo) GetDevRxRateOk() (*int64, bool) {
	if o == nil || IsNil(o.DevRxRate) {
		return nil, false
	}
	return o.DevRxRate, true
}

// HasDevRxRate returns a boolean if a field has been set.
func (o *DeviceNodeInfo) HasDevRxRate() bool {
	if o != nil && !IsNil(o.DevRxRate) {
		return true
	}

	return false
}

// SetDevRxRate gets a reference to the given int64 and assigns it to the DevRxRate field.
func (o *DeviceNodeInfo) SetDevRxRate(v int64) {
	o.DevRxRate = &v
}

// GetDevTxRate returns the DevTxRate field value if set, zero value otherwise.
func (o *DeviceNodeInfo) GetDevTxRate() int64 {
	if o == nil || IsNil(o.DevTxRate) {
		var ret int64
		return ret
	}
	return *o.DevTxRate
}

// GetDevTxRateOk returns a tuple with the DevTxRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceNodeInfo) GetDevTxRateOk() (*int64, bool) {
	if o == nil || IsNil(o.DevTxRate) {
		return nil, false
	}
	return o.DevTxRate, true
}

// HasDevTxRate returns a boolean if a field has been set.
func (o *DeviceNodeInfo) HasDevTxRate() bool {
	if o != nil && !IsNil(o.DevTxRate) {
		return true
	}

	return false
}

// SetDevTxRate gets a reference to the given int64 and assigns it to the DevTxRate field.
func (o *DeviceNodeInfo) SetDevTxRate(v int64) {
	o.DevTxRate = &v
}

// GetDeviceType returns the DeviceType field value if set, zero value otherwise.
func (o *DeviceNodeInfo) GetDeviceType() int32 {
	if o == nil || IsNil(o.DeviceType) {
		var ret int32
		return ret
	}
	return *o.DeviceType
}

// GetDeviceTypeOk returns a tuple with the DeviceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceNodeInfo) GetDeviceTypeOk() (*int32, bool) {
	if o == nil || IsNil(o.DeviceType) {
		return nil, false
	}
	return o.DeviceType, true
}

// HasDeviceType returns a boolean if a field has been set.
func (o *DeviceNodeInfo) HasDeviceType() bool {
	if o != nil && !IsNil(o.DeviceType) {
		return true
	}

	return false
}

// SetDeviceType gets a reference to the given int32 and assigns it to the DeviceType field.
func (o *DeviceNodeInfo) SetDeviceType(v int32) {
	o.DeviceType = &v
}

// GetGatewayInfo returns the GatewayInfo field value if set, zero value otherwise.
func (o *DeviceNodeInfo) GetGatewayInfo() GatewayInfoEntity {
	if o == nil || IsNil(o.GatewayInfo) {
		var ret GatewayInfoEntity
		return ret
	}
	return *o.GatewayInfo
}

// GetGatewayInfoOk returns a tuple with the GatewayInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceNodeInfo) GetGatewayInfoOk() (*GatewayInfoEntity, bool) {
	if o == nil || IsNil(o.GatewayInfo) {
		return nil, false
	}
	return o.GatewayInfo, true
}

// HasGatewayInfo returns a boolean if a field has been set.
func (o *DeviceNodeInfo) HasGatewayInfo() bool {
	if o != nil && !IsNil(o.GatewayInfo) {
		return true
	}

	return false
}

// SetGatewayInfo gets a reference to the given GatewayInfoEntity and assigns it to the GatewayInfo field.
func (o *DeviceNodeInfo) SetGatewayInfo(v GatewayInfoEntity) {
	o.GatewayInfo = &v
}

// GetHealthScore returns the HealthScore field value if set, zero value otherwise.
func (o *DeviceNodeInfo) GetHealthScore() int32 {
	if o == nil || IsNil(o.HealthScore) {
		var ret int32
		return ret
	}
	return *o.HealthScore
}

// GetHealthScoreOk returns a tuple with the HealthScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceNodeInfo) GetHealthScoreOk() (*int32, bool) {
	if o == nil || IsNil(o.HealthScore) {
		return nil, false
	}
	return o.HealthScore, true
}

// HasHealthScore returns a boolean if a field has been set.
func (o *DeviceNodeInfo) HasHealthScore() bool {
	if o != nil && !IsNil(o.HealthScore) {
		return true
	}

	return false
}

// SetHealthScore gets a reference to the given int32 and assigns it to the HealthScore field.
func (o *DeviceNodeInfo) SetHealthScore(v int32) {
	o.HealthScore = &v
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *DeviceNodeInfo) GetIp() string {
	if o == nil || IsNil(o.Ip) {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceNodeInfo) GetIpOk() (*string, bool) {
	if o == nil || IsNil(o.Ip) {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *DeviceNodeInfo) HasIp() bool {
	if o != nil && !IsNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *DeviceNodeInfo) SetIp(v string) {
	o.Ip = &v
}

// GetIpv6List returns the Ipv6List field value if set, zero value otherwise.
func (o *DeviceNodeInfo) GetIpv6List() []string {
	if o == nil || IsNil(o.Ipv6List) {
		var ret []string
		return ret
	}
	return o.Ipv6List
}

// GetIpv6ListOk returns a tuple with the Ipv6List field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceNodeInfo) GetIpv6ListOk() ([]string, bool) {
	if o == nil || IsNil(o.Ipv6List) {
		return nil, false
	}
	return o.Ipv6List, true
}

// HasIpv6List returns a boolean if a field has been set.
func (o *DeviceNodeInfo) HasIpv6List() bool {
	if o != nil && !IsNil(o.Ipv6List) {
		return true
	}

	return false
}

// SetIpv6List gets a reference to the given []string and assigns it to the Ipv6List field.
func (o *DeviceNodeInfo) SetIpv6List(v []string) {
	o.Ipv6List = v
}

// GetMac returns the Mac field value if set, zero value otherwise.
func (o *DeviceNodeInfo) GetMac() string {
	if o == nil || IsNil(o.Mac) {
		var ret string
		return ret
	}
	return *o.Mac
}

// GetMacOk returns a tuple with the Mac field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceNodeInfo) GetMacOk() (*string, bool) {
	if o == nil || IsNil(o.Mac) {
		return nil, false
	}
	return o.Mac, true
}

// HasMac returns a boolean if a field has been set.
func (o *DeviceNodeInfo) HasMac() bool {
	if o != nil && !IsNil(o.Mac) {
		return true
	}

	return false
}

// SetMac gets a reference to the given string and assigns it to the Mac field.
func (o *DeviceNodeInfo) SetMac(v string) {
	o.Mac = &v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *DeviceNodeInfo) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceNodeInfo) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *DeviceNodeInfo) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *DeviceNodeInfo) SetModel(v string) {
	o.Model = &v
}

// GetModelVersion returns the ModelVersion field value if set, zero value otherwise.
func (o *DeviceNodeInfo) GetModelVersion() string {
	if o == nil || IsNil(o.ModelVersion) {
		var ret string
		return ret
	}
	return *o.ModelVersion
}

// GetModelVersionOk returns a tuple with the ModelVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceNodeInfo) GetModelVersionOk() (*string, bool) {
	if o == nil || IsNil(o.ModelVersion) {
		return nil, false
	}
	return o.ModelVersion, true
}

// HasModelVersion returns a boolean if a field has been set.
func (o *DeviceNodeInfo) HasModelVersion() bool {
	if o != nil && !IsNil(o.ModelVersion) {
		return true
	}

	return false
}

// SetModelVersion gets a reference to the given string and assigns it to the ModelVersion field.
func (o *DeviceNodeInfo) SetModelVersion(v string) {
	o.ModelVersion = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DeviceNodeInfo) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceNodeInfo) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DeviceNodeInfo) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DeviceNodeInfo) SetName(v string) {
	o.Name = &v
}

// GetOsg returns the Osg field value if set, zero value otherwise.
func (o *DeviceNodeInfo) GetOsg() bool {
	if o == nil || IsNil(o.Osg) {
		var ret bool
		return ret
	}
	return *o.Osg
}

// GetOsgOk returns a tuple with the Osg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceNodeInfo) GetOsgOk() (*bool, bool) {
	if o == nil || IsNil(o.Osg) {
		return nil, false
	}
	return o.Osg, true
}

// HasOsg returns a boolean if a field has been set.
func (o *DeviceNodeInfo) HasOsg() bool {
	if o != nil && !IsNil(o.Osg) {
		return true
	}

	return false
}

// SetOsg gets a reference to the given bool and assigns it to the Osg field.
func (o *DeviceNodeInfo) SetOsg(v bool) {
	o.Osg = &v
}

// GetOsw returns the Osw field value if set, zero value otherwise.
func (o *DeviceNodeInfo) GetOsw() bool {
	if o == nil || IsNil(o.Osw) {
		var ret bool
		return ret
	}
	return *o.Osw
}

// GetOswOk returns a tuple with the Osw field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceNodeInfo) GetOswOk() (*bool, bool) {
	if o == nil || IsNil(o.Osw) {
		return nil, false
	}
	return o.Osw, true
}

// HasOsw returns a boolean if a field has been set.
func (o *DeviceNodeInfo) HasOsw() bool {
	if o != nil && !IsNil(o.Osw) {
		return true
	}

	return false
}

// SetOsw gets a reference to the given bool and assigns it to the Osw field.
func (o *DeviceNodeInfo) SetOsw(v bool) {
	o.Osw = &v
}

// GetShowModel returns the ShowModel field value if set, zero value otherwise.
func (o *DeviceNodeInfo) GetShowModel() string {
	if o == nil || IsNil(o.ShowModel) {
		var ret string
		return ret
	}
	return *o.ShowModel
}

// GetShowModelOk returns a tuple with the ShowModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceNodeInfo) GetShowModelOk() (*string, bool) {
	if o == nil || IsNil(o.ShowModel) {
		return nil, false
	}
	return o.ShowModel, true
}

// HasShowModel returns a boolean if a field has been set.
func (o *DeviceNodeInfo) HasShowModel() bool {
	if o != nil && !IsNil(o.ShowModel) {
		return true
	}

	return false
}

// SetShowModel gets a reference to the given string and assigns it to the ShowModel field.
func (o *DeviceNodeInfo) SetShowModel(v string) {
	o.ShowModel = &v
}

// GetStackGroup returns the StackGroup field value if set, zero value otherwise.
func (o *DeviceNodeInfo) GetStackGroup() bool {
	if o == nil || IsNil(o.StackGroup) {
		var ret bool
		return ret
	}
	return *o.StackGroup
}

// GetStackGroupOk returns a tuple with the StackGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceNodeInfo) GetStackGroupOk() (*bool, bool) {
	if o == nil || IsNil(o.StackGroup) {
		return nil, false
	}
	return o.StackGroup, true
}

// HasStackGroup returns a boolean if a field has been set.
func (o *DeviceNodeInfo) HasStackGroup() bool {
	if o != nil && !IsNil(o.StackGroup) {
		return true
	}

	return false
}

// SetStackGroup gets a reference to the given bool and assigns it to the StackGroup field.
func (o *DeviceNodeInfo) SetStackGroup(v bool) {
	o.StackGroup = &v
}

// GetStackId returns the StackId field value if set, zero value otherwise.
func (o *DeviceNodeInfo) GetStackId() string {
	if o == nil || IsNil(o.StackId) {
		var ret string
		return ret
	}
	return *o.StackId
}

// GetStackIdOk returns a tuple with the StackId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceNodeInfo) GetStackIdOk() (*string, bool) {
	if o == nil || IsNil(o.StackId) {
		return nil, false
	}
	return o.StackId, true
}

// HasStackId returns a boolean if a field has been set.
func (o *DeviceNodeInfo) HasStackId() bool {
	if o != nil && !IsNil(o.StackId) {
		return true
	}

	return false
}

// SetStackId gets a reference to the given string and assigns it to the StackId field.
func (o *DeviceNodeInfo) SetStackId(v string) {
	o.StackId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DeviceNodeInfo) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceNodeInfo) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DeviceNodeInfo) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *DeviceNodeInfo) SetStatus(v int32) {
	o.Status = &v
}

// GetStatusCategory returns the StatusCategory field value if set, zero value otherwise.
func (o *DeviceNodeInfo) GetStatusCategory() int32 {
	if o == nil || IsNil(o.StatusCategory) {
		var ret int32
		return ret
	}
	return *o.StatusCategory
}

// GetStatusCategoryOk returns a tuple with the StatusCategory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceNodeInfo) GetStatusCategoryOk() (*int32, bool) {
	if o == nil || IsNil(o.StatusCategory) {
		return nil, false
	}
	return o.StatusCategory, true
}

// HasStatusCategory returns a boolean if a field has been set.
func (o *DeviceNodeInfo) HasStatusCategory() bool {
	if o != nil && !IsNil(o.StatusCategory) {
		return true
	}

	return false
}

// SetStatusCategory gets a reference to the given int32 and assigns it to the StatusCategory field.
func (o *DeviceNodeInfo) SetStatusCategory(v int32) {
	o.StatusCategory = &v
}

// GetSwitchInfo returns the SwitchInfo field value if set, zero value otherwise.
func (o *DeviceNodeInfo) GetSwitchInfo() SwitchInfo {
	if o == nil || IsNil(o.SwitchInfo) {
		var ret SwitchInfo
		return ret
	}
	return *o.SwitchInfo
}

// GetSwitchInfoOk returns a tuple with the SwitchInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceNodeInfo) GetSwitchInfoOk() (*SwitchInfo, bool) {
	if o == nil || IsNil(o.SwitchInfo) {
		return nil, false
	}
	return o.SwitchInfo, true
}

// HasSwitchInfo returns a boolean if a field has been set.
func (o *DeviceNodeInfo) HasSwitchInfo() bool {
	if o != nil && !IsNil(o.SwitchInfo) {
		return true
	}

	return false
}

// SetSwitchInfo gets a reference to the given SwitchInfo and assigns it to the SwitchInfo field.
func (o *DeviceNodeInfo) SetSwitchInfo(v SwitchInfo) {
	o.SwitchInfo = &v
}

func (o DeviceNodeInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceNodeInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ap) {
		toSerialize["ap"] = o.Ap
	}
	if !IsNil(o.ApInfo) {
		toSerialize["apInfo"] = o.ApInfo
	}
	if !IsNil(o.DevRxRate) {
		toSerialize["devRxRate"] = o.DevRxRate
	}
	if !IsNil(o.DevTxRate) {
		toSerialize["devTxRate"] = o.DevTxRate
	}
	if !IsNil(o.DeviceType) {
		toSerialize["deviceType"] = o.DeviceType
	}
	if !IsNil(o.GatewayInfo) {
		toSerialize["gatewayInfo"] = o.GatewayInfo
	}
	if !IsNil(o.HealthScore) {
		toSerialize["healthScore"] = o.HealthScore
	}
	if !IsNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}
	if !IsNil(o.Ipv6List) {
		toSerialize["ipv6List"] = o.Ipv6List
	}
	if !IsNil(o.Mac) {
		toSerialize["mac"] = o.Mac
	}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.ModelVersion) {
		toSerialize["modelVersion"] = o.ModelVersion
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Osg) {
		toSerialize["osg"] = o.Osg
	}
	if !IsNil(o.Osw) {
		toSerialize["osw"] = o.Osw
	}
	if !IsNil(o.ShowModel) {
		toSerialize["showModel"] = o.ShowModel
	}
	if !IsNil(o.StackGroup) {
		toSerialize["stackGroup"] = o.StackGroup
	}
	if !IsNil(o.StackId) {
		toSerialize["stackId"] = o.StackId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.StatusCategory) {
		toSerialize["statusCategory"] = o.StatusCategory
	}
	if !IsNil(o.SwitchInfo) {
		toSerialize["switchInfo"] = o.SwitchInfo
	}
	return toSerialize, nil
}

type NullableDeviceNodeInfo struct {
	value *DeviceNodeInfo
	isSet bool
}

func (v NullableDeviceNodeInfo) Get() *DeviceNodeInfo {
	return v.value
}

func (v *NullableDeviceNodeInfo) Set(val *DeviceNodeInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceNodeInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceNodeInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceNodeInfo(val *DeviceNodeInfo) *NullableDeviceNodeInfo {
	return &NullableDeviceNodeInfo{value: val, isSet: true}
}

func (v NullableDeviceNodeInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceNodeInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


