/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
)

// checks if the ApplicationStatTraffic type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationStatTraffic{}

// ApplicationStatTraffic struct for ApplicationStatTraffic
type ApplicationStatTraffic struct {
	// The number of active users under this app.
	ActiveUser *int32 `json:"activeUser,omitempty"`
	// The description of the application.
	ApplicationDescription *string `json:"applicationDescription,omitempty"`
	// The id of the application.
	ApplicationId *int32 `json:"applicationId,omitempty"`
	// The name of the application.
	ApplicationName *string `json:"applicationName,omitempty"`
	// The number of times this app has been blocked.
	Block *int64 `json:"block,omitempty"`
	// The clients info.
	Clients []ClientTrafficWithApplications `json:"clients,omitempty"`
	// The number of clients using the app.
	ClientsCount *int32 `json:"clientsCount,omitempty"`
	// The download traffic used by the app.
	Download *int64 `json:"download,omitempty"`
	// The id of the family.
	FamilyId *int32 `json:"familyId,omitempty"`
	// The name of the family.
	FamilyName *string `json:"familyName,omitempty"`
	// The total amount of traffic used by the app.
	Traffic *int64 `json:"traffic,omitempty"`
	// The percentage of traffic used by the app.
	TrafficPercent *float64 `json:"trafficPercent,omitempty"`
	// The upload traffic used by the app.
	Upload *int64 `json:"upload,omitempty"`
}

// NewApplicationStatTraffic instantiates a new ApplicationStatTraffic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationStatTraffic() *ApplicationStatTraffic {
	this := ApplicationStatTraffic{}
	return &this
}

// NewApplicationStatTrafficWithDefaults instantiates a new ApplicationStatTraffic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationStatTrafficWithDefaults() *ApplicationStatTraffic {
	this := ApplicationStatTraffic{}
	return &this
}

// GetActiveUser returns the ActiveUser field value if set, zero value otherwise.
func (o *ApplicationStatTraffic) GetActiveUser() int32 {
	if o == nil || IsNil(o.ActiveUser) {
		var ret int32
		return ret
	}
	return *o.ActiveUser
}

// GetActiveUserOk returns a tuple with the ActiveUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationStatTraffic) GetActiveUserOk() (*int32, bool) {
	if o == nil || IsNil(o.ActiveUser) {
		return nil, false
	}
	return o.ActiveUser, true
}

// HasActiveUser returns a boolean if a field has been set.
func (o *ApplicationStatTraffic) HasActiveUser() bool {
	if o != nil && !IsNil(o.ActiveUser) {
		return true
	}

	return false
}

// SetActiveUser gets a reference to the given int32 and assigns it to the ActiveUser field.
func (o *ApplicationStatTraffic) SetActiveUser(v int32) {
	o.ActiveUser = &v
}

// GetApplicationDescription returns the ApplicationDescription field value if set, zero value otherwise.
func (o *ApplicationStatTraffic) GetApplicationDescription() string {
	if o == nil || IsNil(o.ApplicationDescription) {
		var ret string
		return ret
	}
	return *o.ApplicationDescription
}

// GetApplicationDescriptionOk returns a tuple with the ApplicationDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationStatTraffic) GetApplicationDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.ApplicationDescription) {
		return nil, false
	}
	return o.ApplicationDescription, true
}

// HasApplicationDescription returns a boolean if a field has been set.
func (o *ApplicationStatTraffic) HasApplicationDescription() bool {
	if o != nil && !IsNil(o.ApplicationDescription) {
		return true
	}

	return false
}

// SetApplicationDescription gets a reference to the given string and assigns it to the ApplicationDescription field.
func (o *ApplicationStatTraffic) SetApplicationDescription(v string) {
	o.ApplicationDescription = &v
}

// GetApplicationId returns the ApplicationId field value if set, zero value otherwise.
func (o *ApplicationStatTraffic) GetApplicationId() int32 {
	if o == nil || IsNil(o.ApplicationId) {
		var ret int32
		return ret
	}
	return *o.ApplicationId
}

// GetApplicationIdOk returns a tuple with the ApplicationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationStatTraffic) GetApplicationIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ApplicationId) {
		return nil, false
	}
	return o.ApplicationId, true
}

// HasApplicationId returns a boolean if a field has been set.
func (o *ApplicationStatTraffic) HasApplicationId() bool {
	if o != nil && !IsNil(o.ApplicationId) {
		return true
	}

	return false
}

// SetApplicationId gets a reference to the given int32 and assigns it to the ApplicationId field.
func (o *ApplicationStatTraffic) SetApplicationId(v int32) {
	o.ApplicationId = &v
}

// GetApplicationName returns the ApplicationName field value if set, zero value otherwise.
func (o *ApplicationStatTraffic) GetApplicationName() string {
	if o == nil || IsNil(o.ApplicationName) {
		var ret string
		return ret
	}
	return *o.ApplicationName
}

// GetApplicationNameOk returns a tuple with the ApplicationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationStatTraffic) GetApplicationNameOk() (*string, bool) {
	if o == nil || IsNil(o.ApplicationName) {
		return nil, false
	}
	return o.ApplicationName, true
}

// HasApplicationName returns a boolean if a field has been set.
func (o *ApplicationStatTraffic) HasApplicationName() bool {
	if o != nil && !IsNil(o.ApplicationName) {
		return true
	}

	return false
}

// SetApplicationName gets a reference to the given string and assigns it to the ApplicationName field.
func (o *ApplicationStatTraffic) SetApplicationName(v string) {
	o.ApplicationName = &v
}

// GetBlock returns the Block field value if set, zero value otherwise.
func (o *ApplicationStatTraffic) GetBlock() int64 {
	if o == nil || IsNil(o.Block) {
		var ret int64
		return ret
	}
	return *o.Block
}

// GetBlockOk returns a tuple with the Block field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationStatTraffic) GetBlockOk() (*int64, bool) {
	if o == nil || IsNil(o.Block) {
		return nil, false
	}
	return o.Block, true
}

// HasBlock returns a boolean if a field has been set.
func (o *ApplicationStatTraffic) HasBlock() bool {
	if o != nil && !IsNil(o.Block) {
		return true
	}

	return false
}

// SetBlock gets a reference to the given int64 and assigns it to the Block field.
func (o *ApplicationStatTraffic) SetBlock(v int64) {
	o.Block = &v
}

// GetClients returns the Clients field value if set, zero value otherwise.
func (o *ApplicationStatTraffic) GetClients() []ClientTrafficWithApplications {
	if o == nil || IsNil(o.Clients) {
		var ret []ClientTrafficWithApplications
		return ret
	}
	return o.Clients
}

// GetClientsOk returns a tuple with the Clients field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationStatTraffic) GetClientsOk() ([]ClientTrafficWithApplications, bool) {
	if o == nil || IsNil(o.Clients) {
		return nil, false
	}
	return o.Clients, true
}

// HasClients returns a boolean if a field has been set.
func (o *ApplicationStatTraffic) HasClients() bool {
	if o != nil && !IsNil(o.Clients) {
		return true
	}

	return false
}

// SetClients gets a reference to the given []ClientTrafficWithApplications and assigns it to the Clients field.
func (o *ApplicationStatTraffic) SetClients(v []ClientTrafficWithApplications) {
	o.Clients = v
}

// GetClientsCount returns the ClientsCount field value if set, zero value otherwise.
func (o *ApplicationStatTraffic) GetClientsCount() int32 {
	if o == nil || IsNil(o.ClientsCount) {
		var ret int32
		return ret
	}
	return *o.ClientsCount
}

// GetClientsCountOk returns a tuple with the ClientsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationStatTraffic) GetClientsCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ClientsCount) {
		return nil, false
	}
	return o.ClientsCount, true
}

// HasClientsCount returns a boolean if a field has been set.
func (o *ApplicationStatTraffic) HasClientsCount() bool {
	if o != nil && !IsNil(o.ClientsCount) {
		return true
	}

	return false
}

// SetClientsCount gets a reference to the given int32 and assigns it to the ClientsCount field.
func (o *ApplicationStatTraffic) SetClientsCount(v int32) {
	o.ClientsCount = &v
}

// GetDownload returns the Download field value if set, zero value otherwise.
func (o *ApplicationStatTraffic) GetDownload() int64 {
	if o == nil || IsNil(o.Download) {
		var ret int64
		return ret
	}
	return *o.Download
}

// GetDownloadOk returns a tuple with the Download field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationStatTraffic) GetDownloadOk() (*int64, bool) {
	if o == nil || IsNil(o.Download) {
		return nil, false
	}
	return o.Download, true
}

// HasDownload returns a boolean if a field has been set.
func (o *ApplicationStatTraffic) HasDownload() bool {
	if o != nil && !IsNil(o.Download) {
		return true
	}

	return false
}

// SetDownload gets a reference to the given int64 and assigns it to the Download field.
func (o *ApplicationStatTraffic) SetDownload(v int64) {
	o.Download = &v
}

// GetFamilyId returns the FamilyId field value if set, zero value otherwise.
func (o *ApplicationStatTraffic) GetFamilyId() int32 {
	if o == nil || IsNil(o.FamilyId) {
		var ret int32
		return ret
	}
	return *o.FamilyId
}

// GetFamilyIdOk returns a tuple with the FamilyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationStatTraffic) GetFamilyIdOk() (*int32, bool) {
	if o == nil || IsNil(o.FamilyId) {
		return nil, false
	}
	return o.FamilyId, true
}

// HasFamilyId returns a boolean if a field has been set.
func (o *ApplicationStatTraffic) HasFamilyId() bool {
	if o != nil && !IsNil(o.FamilyId) {
		return true
	}

	return false
}

// SetFamilyId gets a reference to the given int32 and assigns it to the FamilyId field.
func (o *ApplicationStatTraffic) SetFamilyId(v int32) {
	o.FamilyId = &v
}

// GetFamilyName returns the FamilyName field value if set, zero value otherwise.
func (o *ApplicationStatTraffic) GetFamilyName() string {
	if o == nil || IsNil(o.FamilyName) {
		var ret string
		return ret
	}
	return *o.FamilyName
}

// GetFamilyNameOk returns a tuple with the FamilyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationStatTraffic) GetFamilyNameOk() (*string, bool) {
	if o == nil || IsNil(o.FamilyName) {
		return nil, false
	}
	return o.FamilyName, true
}

// HasFamilyName returns a boolean if a field has been set.
func (o *ApplicationStatTraffic) HasFamilyName() bool {
	if o != nil && !IsNil(o.FamilyName) {
		return true
	}

	return false
}

// SetFamilyName gets a reference to the given string and assigns it to the FamilyName field.
func (o *ApplicationStatTraffic) SetFamilyName(v string) {
	o.FamilyName = &v
}

// GetTraffic returns the Traffic field value if set, zero value otherwise.
func (o *ApplicationStatTraffic) GetTraffic() int64 {
	if o == nil || IsNil(o.Traffic) {
		var ret int64
		return ret
	}
	return *o.Traffic
}

// GetTrafficOk returns a tuple with the Traffic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationStatTraffic) GetTrafficOk() (*int64, bool) {
	if o == nil || IsNil(o.Traffic) {
		return nil, false
	}
	return o.Traffic, true
}

// HasTraffic returns a boolean if a field has been set.
func (o *ApplicationStatTraffic) HasTraffic() bool {
	if o != nil && !IsNil(o.Traffic) {
		return true
	}

	return false
}

// SetTraffic gets a reference to the given int64 and assigns it to the Traffic field.
func (o *ApplicationStatTraffic) SetTraffic(v int64) {
	o.Traffic = &v
}

// GetTrafficPercent returns the TrafficPercent field value if set, zero value otherwise.
func (o *ApplicationStatTraffic) GetTrafficPercent() float64 {
	if o == nil || IsNil(o.TrafficPercent) {
		var ret float64
		return ret
	}
	return *o.TrafficPercent
}

// GetTrafficPercentOk returns a tuple with the TrafficPercent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationStatTraffic) GetTrafficPercentOk() (*float64, bool) {
	if o == nil || IsNil(o.TrafficPercent) {
		return nil, false
	}
	return o.TrafficPercent, true
}

// HasTrafficPercent returns a boolean if a field has been set.
func (o *ApplicationStatTraffic) HasTrafficPercent() bool {
	if o != nil && !IsNil(o.TrafficPercent) {
		return true
	}

	return false
}

// SetTrafficPercent gets a reference to the given float64 and assigns it to the TrafficPercent field.
func (o *ApplicationStatTraffic) SetTrafficPercent(v float64) {
	o.TrafficPercent = &v
}

// GetUpload returns the Upload field value if set, zero value otherwise.
func (o *ApplicationStatTraffic) GetUpload() int64 {
	if o == nil || IsNil(o.Upload) {
		var ret int64
		return ret
	}
	return *o.Upload
}

// GetUploadOk returns a tuple with the Upload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationStatTraffic) GetUploadOk() (*int64, bool) {
	if o == nil || IsNil(o.Upload) {
		return nil, false
	}
	return o.Upload, true
}

// HasUpload returns a boolean if a field has been set.
func (o *ApplicationStatTraffic) HasUpload() bool {
	if o != nil && !IsNil(o.Upload) {
		return true
	}

	return false
}

// SetUpload gets a reference to the given int64 and assigns it to the Upload field.
func (o *ApplicationStatTraffic) SetUpload(v int64) {
	o.Upload = &v
}

func (o ApplicationStatTraffic) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationStatTraffic) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ActiveUser) {
		toSerialize["activeUser"] = o.ActiveUser
	}
	if !IsNil(o.ApplicationDescription) {
		toSerialize["applicationDescription"] = o.ApplicationDescription
	}
	if !IsNil(o.ApplicationId) {
		toSerialize["applicationId"] = o.ApplicationId
	}
	if !IsNil(o.ApplicationName) {
		toSerialize["applicationName"] = o.ApplicationName
	}
	if !IsNil(o.Block) {
		toSerialize["block"] = o.Block
	}
	if !IsNil(o.Clients) {
		toSerialize["clients"] = o.Clients
	}
	if !IsNil(o.ClientsCount) {
		toSerialize["clientsCount"] = o.ClientsCount
	}
	if !IsNil(o.Download) {
		toSerialize["download"] = o.Download
	}
	if !IsNil(o.FamilyId) {
		toSerialize["familyId"] = o.FamilyId
	}
	if !IsNil(o.FamilyName) {
		toSerialize["familyName"] = o.FamilyName
	}
	if !IsNil(o.Traffic) {
		toSerialize["traffic"] = o.Traffic
	}
	if !IsNil(o.TrafficPercent) {
		toSerialize["trafficPercent"] = o.TrafficPercent
	}
	if !IsNil(o.Upload) {
		toSerialize["upload"] = o.Upload
	}
	return toSerialize, nil
}

type NullableApplicationStatTraffic struct {
	value *ApplicationStatTraffic
	isSet bool
}

func (v NullableApplicationStatTraffic) Get() *ApplicationStatTraffic {
	return v.value
}

func (v *NullableApplicationStatTraffic) Set(val *ApplicationStatTraffic) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationStatTraffic) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationStatTraffic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationStatTraffic(val *ApplicationStatTraffic) *NullableApplicationStatTraffic {
	return &NullableApplicationStatTraffic{value: val, isSet: true}
}

func (v NullableApplicationStatTraffic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationStatTraffic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


