/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
)

// checks if the OpsBlockedCountryOpenApiVO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpsBlockedCountryOpenApiVO{}

// OpsBlockedCountryOpenApiVO struct for OpsBlockedCountryOpenApiVO
type OpsBlockedCountryOpenApiVO struct {
	// Country.
	Country *string `json:"country,omitempty"`
	// Site list.
	Sites []string `json:"sites,omitempty"`
}

// NewOpsBlockedCountryOpenApiVO instantiates a new OpsBlockedCountryOpenApiVO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpsBlockedCountryOpenApiVO() *OpsBlockedCountryOpenApiVO {
	this := OpsBlockedCountryOpenApiVO{}
	return &this
}

// NewOpsBlockedCountryOpenApiVOWithDefaults instantiates a new OpsBlockedCountryOpenApiVO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpsBlockedCountryOpenApiVOWithDefaults() *OpsBlockedCountryOpenApiVO {
	this := OpsBlockedCountryOpenApiVO{}
	return &this
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *OpsBlockedCountryOpenApiVO) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsBlockedCountryOpenApiVO) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *OpsBlockedCountryOpenApiVO) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *OpsBlockedCountryOpenApiVO) SetCountry(v string) {
	o.Country = &v
}

// GetSites returns the Sites field value if set, zero value otherwise.
func (o *OpsBlockedCountryOpenApiVO) GetSites() []string {
	if o == nil || IsNil(o.Sites) {
		var ret []string
		return ret
	}
	return o.Sites
}

// GetSitesOk returns a tuple with the Sites field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsBlockedCountryOpenApiVO) GetSitesOk() ([]string, bool) {
	if o == nil || IsNil(o.Sites) {
		return nil, false
	}
	return o.Sites, true
}

// HasSites returns a boolean if a field has been set.
func (o *OpsBlockedCountryOpenApiVO) HasSites() bool {
	if o != nil && !IsNil(o.Sites) {
		return true
	}

	return false
}

// SetSites gets a reference to the given []string and assigns it to the Sites field.
func (o *OpsBlockedCountryOpenApiVO) SetSites(v []string) {
	o.Sites = v
}

func (o OpsBlockedCountryOpenApiVO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpsBlockedCountryOpenApiVO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.Sites) {
		toSerialize["sites"] = o.Sites
	}
	return toSerialize, nil
}

type NullableOpsBlockedCountryOpenApiVO struct {
	value *OpsBlockedCountryOpenApiVO
	isSet bool
}

func (v NullableOpsBlockedCountryOpenApiVO) Get() *OpsBlockedCountryOpenApiVO {
	return v.value
}

func (v *NullableOpsBlockedCountryOpenApiVO) Set(val *OpsBlockedCountryOpenApiVO) {
	v.value = val
	v.isSet = true
}

func (v NullableOpsBlockedCountryOpenApiVO) IsSet() bool {
	return v.isSet
}

func (v *NullableOpsBlockedCountryOpenApiVO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpsBlockedCountryOpenApiVO(val *OpsBlockedCountryOpenApiVO) *NullableOpsBlockedCountryOpenApiVO {
	return &NullableOpsBlockedCountryOpenApiVO{value: val, isSet: true}
}

func (v NullableOpsBlockedCountryOpenApiVO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpsBlockedCountryOpenApiVO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


