/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EthUnit1PortDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EthUnit1PortDTO{}

// EthUnit1PortDTO Eth unit1 port list
type EthUnit1PortDTO struct {
	Description *string `json:"description,omitempty"`
	Duplex *string `json:"duplex,omitempty"`
	DuplexLink *string `json:"duplexLink,omitempty"`
	FlowControl *string `json:"flowControl,omitempty"`
	Lag *string `json:"lag,omitempty"`
	LinkStatus *string `json:"linkStatus,omitempty"`
	MediaType *string `json:"mediaType,omitempty"`
	Port string `json:"port"`
	Speed *int32 `json:"speed,omitempty"`
	SpeedLink *int32 `json:"speedLink,omitempty"`
	SpeedMax *int32 `json:"speedMax,omitempty"`
	Status *string `json:"status,omitempty"`
	Type *string `json:"type,omitempty"`
}

type _EthUnit1PortDTO EthUnit1PortDTO

// NewEthUnit1PortDTO instantiates a new EthUnit1PortDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEthUnit1PortDTO(port string) *EthUnit1PortDTO {
	this := EthUnit1PortDTO{}
	this.Port = port
	return &this
}

// NewEthUnit1PortDTOWithDefaults instantiates a new EthUnit1PortDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEthUnit1PortDTOWithDefaults() *EthUnit1PortDTO {
	this := EthUnit1PortDTO{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *EthUnit1PortDTO) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EthUnit1PortDTO) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *EthUnit1PortDTO) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *EthUnit1PortDTO) SetDescription(v string) {
	o.Description = &v
}

// GetDuplex returns the Duplex field value if set, zero value otherwise.
func (o *EthUnit1PortDTO) GetDuplex() string {
	if o == nil || IsNil(o.Duplex) {
		var ret string
		return ret
	}
	return *o.Duplex
}

// GetDuplexOk returns a tuple with the Duplex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EthUnit1PortDTO) GetDuplexOk() (*string, bool) {
	if o == nil || IsNil(o.Duplex) {
		return nil, false
	}
	return o.Duplex, true
}

// HasDuplex returns a boolean if a field has been set.
func (o *EthUnit1PortDTO) HasDuplex() bool {
	if o != nil && !IsNil(o.Duplex) {
		return true
	}

	return false
}

// SetDuplex gets a reference to the given string and assigns it to the Duplex field.
func (o *EthUnit1PortDTO) SetDuplex(v string) {
	o.Duplex = &v
}

// GetDuplexLink returns the DuplexLink field value if set, zero value otherwise.
func (o *EthUnit1PortDTO) GetDuplexLink() string {
	if o == nil || IsNil(o.DuplexLink) {
		var ret string
		return ret
	}
	return *o.DuplexLink
}

// GetDuplexLinkOk returns a tuple with the DuplexLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EthUnit1PortDTO) GetDuplexLinkOk() (*string, bool) {
	if o == nil || IsNil(o.DuplexLink) {
		return nil, false
	}
	return o.DuplexLink, true
}

// HasDuplexLink returns a boolean if a field has been set.
func (o *EthUnit1PortDTO) HasDuplexLink() bool {
	if o != nil && !IsNil(o.DuplexLink) {
		return true
	}

	return false
}

// SetDuplexLink gets a reference to the given string and assigns it to the DuplexLink field.
func (o *EthUnit1PortDTO) SetDuplexLink(v string) {
	o.DuplexLink = &v
}

// GetFlowControl returns the FlowControl field value if set, zero value otherwise.
func (o *EthUnit1PortDTO) GetFlowControl() string {
	if o == nil || IsNil(o.FlowControl) {
		var ret string
		return ret
	}
	return *o.FlowControl
}

// GetFlowControlOk returns a tuple with the FlowControl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EthUnit1PortDTO) GetFlowControlOk() (*string, bool) {
	if o == nil || IsNil(o.FlowControl) {
		return nil, false
	}
	return o.FlowControl, true
}

// HasFlowControl returns a boolean if a field has been set.
func (o *EthUnit1PortDTO) HasFlowControl() bool {
	if o != nil && !IsNil(o.FlowControl) {
		return true
	}

	return false
}

// SetFlowControl gets a reference to the given string and assigns it to the FlowControl field.
func (o *EthUnit1PortDTO) SetFlowControl(v string) {
	o.FlowControl = &v
}

// GetLag returns the Lag field value if set, zero value otherwise.
func (o *EthUnit1PortDTO) GetLag() string {
	if o == nil || IsNil(o.Lag) {
		var ret string
		return ret
	}
	return *o.Lag
}

// GetLagOk returns a tuple with the Lag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EthUnit1PortDTO) GetLagOk() (*string, bool) {
	if o == nil || IsNil(o.Lag) {
		return nil, false
	}
	return o.Lag, true
}

// HasLag returns a boolean if a field has been set.
func (o *EthUnit1PortDTO) HasLag() bool {
	if o != nil && !IsNil(o.Lag) {
		return true
	}

	return false
}

// SetLag gets a reference to the given string and assigns it to the Lag field.
func (o *EthUnit1PortDTO) SetLag(v string) {
	o.Lag = &v
}

// GetLinkStatus returns the LinkStatus field value if set, zero value otherwise.
func (o *EthUnit1PortDTO) GetLinkStatus() string {
	if o == nil || IsNil(o.LinkStatus) {
		var ret string
		return ret
	}
	return *o.LinkStatus
}

// GetLinkStatusOk returns a tuple with the LinkStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EthUnit1PortDTO) GetLinkStatusOk() (*string, bool) {
	if o == nil || IsNil(o.LinkStatus) {
		return nil, false
	}
	return o.LinkStatus, true
}

// HasLinkStatus returns a boolean if a field has been set.
func (o *EthUnit1PortDTO) HasLinkStatus() bool {
	if o != nil && !IsNil(o.LinkStatus) {
		return true
	}

	return false
}

// SetLinkStatus gets a reference to the given string and assigns it to the LinkStatus field.
func (o *EthUnit1PortDTO) SetLinkStatus(v string) {
	o.LinkStatus = &v
}

// GetMediaType returns the MediaType field value if set, zero value otherwise.
func (o *EthUnit1PortDTO) GetMediaType() string {
	if o == nil || IsNil(o.MediaType) {
		var ret string
		return ret
	}
	return *o.MediaType
}

// GetMediaTypeOk returns a tuple with the MediaType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EthUnit1PortDTO) GetMediaTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MediaType) {
		return nil, false
	}
	return o.MediaType, true
}

// HasMediaType returns a boolean if a field has been set.
func (o *EthUnit1PortDTO) HasMediaType() bool {
	if o != nil && !IsNil(o.MediaType) {
		return true
	}

	return false
}

// SetMediaType gets a reference to the given string and assigns it to the MediaType field.
func (o *EthUnit1PortDTO) SetMediaType(v string) {
	o.MediaType = &v
}

// GetPort returns the Port field value
func (o *EthUnit1PortDTO) GetPort() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Port
}

// GetPortOk returns a tuple with the Port field value
// and a boolean to check if the value has been set.
func (o *EthUnit1PortDTO) GetPortOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Port, true
}

// SetPort sets field value
func (o *EthUnit1PortDTO) SetPort(v string) {
	o.Port = v
}

// GetSpeed returns the Speed field value if set, zero value otherwise.
func (o *EthUnit1PortDTO) GetSpeed() int32 {
	if o == nil || IsNil(o.Speed) {
		var ret int32
		return ret
	}
	return *o.Speed
}

// GetSpeedOk returns a tuple with the Speed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EthUnit1PortDTO) GetSpeedOk() (*int32, bool) {
	if o == nil || IsNil(o.Speed) {
		return nil, false
	}
	return o.Speed, true
}

// HasSpeed returns a boolean if a field has been set.
func (o *EthUnit1PortDTO) HasSpeed() bool {
	if o != nil && !IsNil(o.Speed) {
		return true
	}

	return false
}

// SetSpeed gets a reference to the given int32 and assigns it to the Speed field.
func (o *EthUnit1PortDTO) SetSpeed(v int32) {
	o.Speed = &v
}

// GetSpeedLink returns the SpeedLink field value if set, zero value otherwise.
func (o *EthUnit1PortDTO) GetSpeedLink() int32 {
	if o == nil || IsNil(o.SpeedLink) {
		var ret int32
		return ret
	}
	return *o.SpeedLink
}

// GetSpeedLinkOk returns a tuple with the SpeedLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EthUnit1PortDTO) GetSpeedLinkOk() (*int32, bool) {
	if o == nil || IsNil(o.SpeedLink) {
		return nil, false
	}
	return o.SpeedLink, true
}

// HasSpeedLink returns a boolean if a field has been set.
func (o *EthUnit1PortDTO) HasSpeedLink() bool {
	if o != nil && !IsNil(o.SpeedLink) {
		return true
	}

	return false
}

// SetSpeedLink gets a reference to the given int32 and assigns it to the SpeedLink field.
func (o *EthUnit1PortDTO) SetSpeedLink(v int32) {
	o.SpeedLink = &v
}

// GetSpeedMax returns the SpeedMax field value if set, zero value otherwise.
func (o *EthUnit1PortDTO) GetSpeedMax() int32 {
	if o == nil || IsNil(o.SpeedMax) {
		var ret int32
		return ret
	}
	return *o.SpeedMax
}

// GetSpeedMaxOk returns a tuple with the SpeedMax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EthUnit1PortDTO) GetSpeedMaxOk() (*int32, bool) {
	if o == nil || IsNil(o.SpeedMax) {
		return nil, false
	}
	return o.SpeedMax, true
}

// HasSpeedMax returns a boolean if a field has been set.
func (o *EthUnit1PortDTO) HasSpeedMax() bool {
	if o != nil && !IsNil(o.SpeedMax) {
		return true
	}

	return false
}

// SetSpeedMax gets a reference to the given int32 and assigns it to the SpeedMax field.
func (o *EthUnit1PortDTO) SetSpeedMax(v int32) {
	o.SpeedMax = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *EthUnit1PortDTO) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EthUnit1PortDTO) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *EthUnit1PortDTO) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *EthUnit1PortDTO) SetStatus(v string) {
	o.Status = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *EthUnit1PortDTO) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EthUnit1PortDTO) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *EthUnit1PortDTO) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *EthUnit1PortDTO) SetType(v string) {
	o.Type = &v
}

func (o EthUnit1PortDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EthUnit1PortDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Duplex) {
		toSerialize["duplex"] = o.Duplex
	}
	if !IsNil(o.DuplexLink) {
		toSerialize["duplexLink"] = o.DuplexLink
	}
	if !IsNil(o.FlowControl) {
		toSerialize["flowControl"] = o.FlowControl
	}
	if !IsNil(o.Lag) {
		toSerialize["lag"] = o.Lag
	}
	if !IsNil(o.LinkStatus) {
		toSerialize["linkStatus"] = o.LinkStatus
	}
	if !IsNil(o.MediaType) {
		toSerialize["mediaType"] = o.MediaType
	}
	toSerialize["port"] = o.Port
	if !IsNil(o.Speed) {
		toSerialize["speed"] = o.Speed
	}
	if !IsNil(o.SpeedLink) {
		toSerialize["speedLink"] = o.SpeedLink
	}
	if !IsNil(o.SpeedMax) {
		toSerialize["speedMax"] = o.SpeedMax
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

func (o *EthUnit1PortDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"port",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEthUnit1PortDTO := _EthUnit1PortDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEthUnit1PortDTO)

	if err != nil {
		return err
	}

	*o = EthUnit1PortDTO(varEthUnit1PortDTO)

	return err
}

type NullableEthUnit1PortDTO struct {
	value *EthUnit1PortDTO
	isSet bool
}

func (v NullableEthUnit1PortDTO) Get() *EthUnit1PortDTO {
	return v.value
}

func (v *NullableEthUnit1PortDTO) Set(val *EthUnit1PortDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableEthUnit1PortDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableEthUnit1PortDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEthUnit1PortDTO(val *EthUnit1PortDTO) *NullableEthUnit1PortDTO {
	return &NullableEthUnit1PortDTO{value: val, isSet: true}
}

func (v NullableEthUnit1PortDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEthUnit1PortDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


