/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ClientLockToAPSetting type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientLockToAPSetting{}

// ClientLockToAPSetting struct for ClientLockToAPSetting
type ClientLockToAPSetting struct {
	// AP MAC list. Use capital letters and separator, for example: AA-AA-AA-AA-AA-AA.
	Aps []string `json:"aps,omitempty"`
	// Lock to AP enable
	Enable bool `json:"enable"`
}

type _ClientLockToAPSetting ClientLockToAPSetting

// NewClientLockToAPSetting instantiates a new ClientLockToAPSetting object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientLockToAPSetting(enable bool) *ClientLockToAPSetting {
	this := ClientLockToAPSetting{}
	this.Enable = enable
	return &this
}

// NewClientLockToAPSettingWithDefaults instantiates a new ClientLockToAPSetting object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientLockToAPSettingWithDefaults() *ClientLockToAPSetting {
	this := ClientLockToAPSetting{}
	return &this
}

// GetAps returns the Aps field value if set, zero value otherwise.
func (o *ClientLockToAPSetting) GetAps() []string {
	if o == nil || IsNil(o.Aps) {
		var ret []string
		return ret
	}
	return o.Aps
}

// GetApsOk returns a tuple with the Aps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientLockToAPSetting) GetApsOk() ([]string, bool) {
	if o == nil || IsNil(o.Aps) {
		return nil, false
	}
	return o.Aps, true
}

// HasAps returns a boolean if a field has been set.
func (o *ClientLockToAPSetting) HasAps() bool {
	if o != nil && !IsNil(o.Aps) {
		return true
	}

	return false
}

// SetAps gets a reference to the given []string and assigns it to the Aps field.
func (o *ClientLockToAPSetting) SetAps(v []string) {
	o.Aps = v
}

// GetEnable returns the Enable field value
func (o *ClientLockToAPSetting) GetEnable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enable
}

// GetEnableOk returns a tuple with the Enable field value
// and a boolean to check if the value has been set.
func (o *ClientLockToAPSetting) GetEnableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enable, true
}

// SetEnable sets field value
func (o *ClientLockToAPSetting) SetEnable(v bool) {
	o.Enable = v
}

func (o ClientLockToAPSetting) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientLockToAPSetting) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Aps) {
		toSerialize["aps"] = o.Aps
	}
	toSerialize["enable"] = o.Enable
	return toSerialize, nil
}

func (o *ClientLockToAPSetting) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enable",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClientLockToAPSetting := _ClientLockToAPSetting{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClientLockToAPSetting)

	if err != nil {
		return err
	}

	*o = ClientLockToAPSetting(varClientLockToAPSetting)

	return err
}

type NullableClientLockToAPSetting struct {
	value *ClientLockToAPSetting
	isSet bool
}

func (v NullableClientLockToAPSetting) Get() *ClientLockToAPSetting {
	return v.value
}

func (v *NullableClientLockToAPSetting) Set(val *ClientLockToAPSetting) {
	v.value = val
	v.isSet = true
}

func (v NullableClientLockToAPSetting) IsSet() bool {
	return v.isSet
}

func (v *NullableClientLockToAPSetting) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientLockToAPSetting(val *ClientLockToAPSetting) *NullableClientLockToAPSetting {
	return &NullableClientLockToAPSetting{value: val, isSet: true}
}

func (v NullableClientLockToAPSetting) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientLockToAPSetting) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


