/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateRadiusUserOpenApiVO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateRadiusUserOpenApiVO{}

// CreateRadiusUserOpenApiVO struct for CreateRadiusUserOpenApiVO
type CreateRadiusUserOpenApiVO struct {
	// Build-in Radius profile user downlink traffic limit, unit: MB. DownLimit should be within the range of 1-10485760
	DownLimit *int64 `json:"downLimit,omitempty"`
	// Build-in Radius profile user downlink rate limit, unit: Kbps. DownRateLimit should be within the range of 1-10485760
	DownRateLimit *int64 `json:"downRateLimit,omitempty"`
	// MAC address, required when parameter [type] is 1. Should be a valid MAC address format
	MacAddress *string `json:"macAddress,omitempty"`
	// Session timeout, unit: second
	Timeout *int32 `json:"timeout,omitempty"`
	// Type of Build-in Radius profile user, 0: user auth; 1: MAC auth
	Type int32 `json:"type"`
	// Build-in Radius profile user uplink traffic limit, unit: MB. UpLimit should be within the range of 1-10485760
	UpLimit *int64 `json:"upLimit,omitempty"`
	// Build-in Radius profile user uplink rate limit, unit: Kbps. UpRateLimit should be within the range of 1-10485760
	UpRateLimit *int64 `json:"upRateLimit,omitempty"`
	UserInfo *RadiusUserInfoOpenApiVO `json:"userInfo,omitempty"`
	// VLAN ID. VlanId should be within the range of 1-4096
	VlanId *int32 `json:"vlanId,omitempty"`
}

type _CreateRadiusUserOpenApiVO CreateRadiusUserOpenApiVO

// NewCreateRadiusUserOpenApiVO instantiates a new CreateRadiusUserOpenApiVO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRadiusUserOpenApiVO(type_ int32) *CreateRadiusUserOpenApiVO {
	this := CreateRadiusUserOpenApiVO{}
	this.Type = type_
	return &this
}

// NewCreateRadiusUserOpenApiVOWithDefaults instantiates a new CreateRadiusUserOpenApiVO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRadiusUserOpenApiVOWithDefaults() *CreateRadiusUserOpenApiVO {
	this := CreateRadiusUserOpenApiVO{}
	return &this
}

// GetDownLimit returns the DownLimit field value if set, zero value otherwise.
func (o *CreateRadiusUserOpenApiVO) GetDownLimit() int64 {
	if o == nil || IsNil(o.DownLimit) {
		var ret int64
		return ret
	}
	return *o.DownLimit
}

// GetDownLimitOk returns a tuple with the DownLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRadiusUserOpenApiVO) GetDownLimitOk() (*int64, bool) {
	if o == nil || IsNil(o.DownLimit) {
		return nil, false
	}
	return o.DownLimit, true
}

// HasDownLimit returns a boolean if a field has been set.
func (o *CreateRadiusUserOpenApiVO) HasDownLimit() bool {
	if o != nil && !IsNil(o.DownLimit) {
		return true
	}

	return false
}

// SetDownLimit gets a reference to the given int64 and assigns it to the DownLimit field.
func (o *CreateRadiusUserOpenApiVO) SetDownLimit(v int64) {
	o.DownLimit = &v
}

// GetDownRateLimit returns the DownRateLimit field value if set, zero value otherwise.
func (o *CreateRadiusUserOpenApiVO) GetDownRateLimit() int64 {
	if o == nil || IsNil(o.DownRateLimit) {
		var ret int64
		return ret
	}
	return *o.DownRateLimit
}

// GetDownRateLimitOk returns a tuple with the DownRateLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRadiusUserOpenApiVO) GetDownRateLimitOk() (*int64, bool) {
	if o == nil || IsNil(o.DownRateLimit) {
		return nil, false
	}
	return o.DownRateLimit, true
}

// HasDownRateLimit returns a boolean if a field has been set.
func (o *CreateRadiusUserOpenApiVO) HasDownRateLimit() bool {
	if o != nil && !IsNil(o.DownRateLimit) {
		return true
	}

	return false
}

// SetDownRateLimit gets a reference to the given int64 and assigns it to the DownRateLimit field.
func (o *CreateRadiusUserOpenApiVO) SetDownRateLimit(v int64) {
	o.DownRateLimit = &v
}

// GetMacAddress returns the MacAddress field value if set, zero value otherwise.
func (o *CreateRadiusUserOpenApiVO) GetMacAddress() string {
	if o == nil || IsNil(o.MacAddress) {
		var ret string
		return ret
	}
	return *o.MacAddress
}

// GetMacAddressOk returns a tuple with the MacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRadiusUserOpenApiVO) GetMacAddressOk() (*string, bool) {
	if o == nil || IsNil(o.MacAddress) {
		return nil, false
	}
	return o.MacAddress, true
}

// HasMacAddress returns a boolean if a field has been set.
func (o *CreateRadiusUserOpenApiVO) HasMacAddress() bool {
	if o != nil && !IsNil(o.MacAddress) {
		return true
	}

	return false
}

// SetMacAddress gets a reference to the given string and assigns it to the MacAddress field.
func (o *CreateRadiusUserOpenApiVO) SetMacAddress(v string) {
	o.MacAddress = &v
}

// GetTimeout returns the Timeout field value if set, zero value otherwise.
func (o *CreateRadiusUserOpenApiVO) GetTimeout() int32 {
	if o == nil || IsNil(o.Timeout) {
		var ret int32
		return ret
	}
	return *o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRadiusUserOpenApiVO) GetTimeoutOk() (*int32, bool) {
	if o == nil || IsNil(o.Timeout) {
		return nil, false
	}
	return o.Timeout, true
}

// HasTimeout returns a boolean if a field has been set.
func (o *CreateRadiusUserOpenApiVO) HasTimeout() bool {
	if o != nil && !IsNil(o.Timeout) {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given int32 and assigns it to the Timeout field.
func (o *CreateRadiusUserOpenApiVO) SetTimeout(v int32) {
	o.Timeout = &v
}

// GetType returns the Type field value
func (o *CreateRadiusUserOpenApiVO) GetType() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateRadiusUserOpenApiVO) GetTypeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateRadiusUserOpenApiVO) SetType(v int32) {
	o.Type = v
}

// GetUpLimit returns the UpLimit field value if set, zero value otherwise.
func (o *CreateRadiusUserOpenApiVO) GetUpLimit() int64 {
	if o == nil || IsNil(o.UpLimit) {
		var ret int64
		return ret
	}
	return *o.UpLimit
}

// GetUpLimitOk returns a tuple with the UpLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRadiusUserOpenApiVO) GetUpLimitOk() (*int64, bool) {
	if o == nil || IsNil(o.UpLimit) {
		return nil, false
	}
	return o.UpLimit, true
}

// HasUpLimit returns a boolean if a field has been set.
func (o *CreateRadiusUserOpenApiVO) HasUpLimit() bool {
	if o != nil && !IsNil(o.UpLimit) {
		return true
	}

	return false
}

// SetUpLimit gets a reference to the given int64 and assigns it to the UpLimit field.
func (o *CreateRadiusUserOpenApiVO) SetUpLimit(v int64) {
	o.UpLimit = &v
}

// GetUpRateLimit returns the UpRateLimit field value if set, zero value otherwise.
func (o *CreateRadiusUserOpenApiVO) GetUpRateLimit() int64 {
	if o == nil || IsNil(o.UpRateLimit) {
		var ret int64
		return ret
	}
	return *o.UpRateLimit
}

// GetUpRateLimitOk returns a tuple with the UpRateLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRadiusUserOpenApiVO) GetUpRateLimitOk() (*int64, bool) {
	if o == nil || IsNil(o.UpRateLimit) {
		return nil, false
	}
	return o.UpRateLimit, true
}

// HasUpRateLimit returns a boolean if a field has been set.
func (o *CreateRadiusUserOpenApiVO) HasUpRateLimit() bool {
	if o != nil && !IsNil(o.UpRateLimit) {
		return true
	}

	return false
}

// SetUpRateLimit gets a reference to the given int64 and assigns it to the UpRateLimit field.
func (o *CreateRadiusUserOpenApiVO) SetUpRateLimit(v int64) {
	o.UpRateLimit = &v
}

// GetUserInfo returns the UserInfo field value if set, zero value otherwise.
func (o *CreateRadiusUserOpenApiVO) GetUserInfo() RadiusUserInfoOpenApiVO {
	if o == nil || IsNil(o.UserInfo) {
		var ret RadiusUserInfoOpenApiVO
		return ret
	}
	return *o.UserInfo
}

// GetUserInfoOk returns a tuple with the UserInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRadiusUserOpenApiVO) GetUserInfoOk() (*RadiusUserInfoOpenApiVO, bool) {
	if o == nil || IsNil(o.UserInfo) {
		return nil, false
	}
	return o.UserInfo, true
}

// HasUserInfo returns a boolean if a field has been set.
func (o *CreateRadiusUserOpenApiVO) HasUserInfo() bool {
	if o != nil && !IsNil(o.UserInfo) {
		return true
	}

	return false
}

// SetUserInfo gets a reference to the given RadiusUserInfoOpenApiVO and assigns it to the UserInfo field.
func (o *CreateRadiusUserOpenApiVO) SetUserInfo(v RadiusUserInfoOpenApiVO) {
	o.UserInfo = &v
}

// GetVlanId returns the VlanId field value if set, zero value otherwise.
func (o *CreateRadiusUserOpenApiVO) GetVlanId() int32 {
	if o == nil || IsNil(o.VlanId) {
		var ret int32
		return ret
	}
	return *o.VlanId
}

// GetVlanIdOk returns a tuple with the VlanId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRadiusUserOpenApiVO) GetVlanIdOk() (*int32, bool) {
	if o == nil || IsNil(o.VlanId) {
		return nil, false
	}
	return o.VlanId, true
}

// HasVlanId returns a boolean if a field has been set.
func (o *CreateRadiusUserOpenApiVO) HasVlanId() bool {
	if o != nil && !IsNil(o.VlanId) {
		return true
	}

	return false
}

// SetVlanId gets a reference to the given int32 and assigns it to the VlanId field.
func (o *CreateRadiusUserOpenApiVO) SetVlanId(v int32) {
	o.VlanId = &v
}

func (o CreateRadiusUserOpenApiVO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateRadiusUserOpenApiVO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DownLimit) {
		toSerialize["downLimit"] = o.DownLimit
	}
	if !IsNil(o.DownRateLimit) {
		toSerialize["downRateLimit"] = o.DownRateLimit
	}
	if !IsNil(o.MacAddress) {
		toSerialize["macAddress"] = o.MacAddress
	}
	if !IsNil(o.Timeout) {
		toSerialize["timeout"] = o.Timeout
	}
	toSerialize["type"] = o.Type
	if !IsNil(o.UpLimit) {
		toSerialize["upLimit"] = o.UpLimit
	}
	if !IsNil(o.UpRateLimit) {
		toSerialize["upRateLimit"] = o.UpRateLimit
	}
	if !IsNil(o.UserInfo) {
		toSerialize["userInfo"] = o.UserInfo
	}
	if !IsNil(o.VlanId) {
		toSerialize["vlanId"] = o.VlanId
	}
	return toSerialize, nil
}

func (o *CreateRadiusUserOpenApiVO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateRadiusUserOpenApiVO := _CreateRadiusUserOpenApiVO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateRadiusUserOpenApiVO)

	if err != nil {
		return err
	}

	*o = CreateRadiusUserOpenApiVO(varCreateRadiusUserOpenApiVO)

	return err
}

type NullableCreateRadiusUserOpenApiVO struct {
	value *CreateRadiusUserOpenApiVO
	isSet bool
}

func (v NullableCreateRadiusUserOpenApiVO) Get() *CreateRadiusUserOpenApiVO {
	return v.value
}

func (v *NullableCreateRadiusUserOpenApiVO) Set(val *CreateRadiusUserOpenApiVO) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRadiusUserOpenApiVO) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRadiusUserOpenApiVO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRadiusUserOpenApiVO(val *CreateRadiusUserOpenApiVO) *NullableCreateRadiusUserOpenApiVO {
	return &NullableCreateRadiusUserOpenApiVO{value: val, isSet: true}
}

func (v NullableCreateRadiusUserOpenApiVO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRadiusUserOpenApiVO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


