/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LanNetworkIpv6ConfigTemplateOpenApiVO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LanNetworkIpv6ConfigTemplateOpenApiVO{}

// LanNetworkIpv6ConfigTemplateOpenApiVO LAN network IPv6 config
type LanNetworkIpv6ConfigTemplateOpenApiVO struct {
	Dhcpv6 *Dhcpv6Setting `json:"dhcpv6,omitempty"`
	// IPv6 enable should be a value as follows: 0: Disable (Default); 1: Enable
	Enable int32 `json:"enable"`
	// The IPv6 Connection Type of LAN port. Proto should be a value as follows:  0: \"none\" (Default); 1: \"DHCPv6\"; 2: \"SLAAC+Stateless DHCP\"; 3: \"SLAAC+RDNSS\"; 4: \"passthrough\"
	Proto int32 `json:"proto"`
	Ra *RaSetting `json:"ra,omitempty"`
	Rdnss *SlaacTemplateOpenApiVO `json:"rdnss,omitempty"`
	Slaac *SlaacTemplateOpenApiVO `json:"slaac,omitempty"`
}

type _LanNetworkIpv6ConfigTemplateOpenApiVO LanNetworkIpv6ConfigTemplateOpenApiVO

// NewLanNetworkIpv6ConfigTemplateOpenApiVO instantiates a new LanNetworkIpv6ConfigTemplateOpenApiVO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLanNetworkIpv6ConfigTemplateOpenApiVO(enable int32, proto int32) *LanNetworkIpv6ConfigTemplateOpenApiVO {
	this := LanNetworkIpv6ConfigTemplateOpenApiVO{}
	this.Enable = enable
	this.Proto = proto
	return &this
}

// NewLanNetworkIpv6ConfigTemplateOpenApiVOWithDefaults instantiates a new LanNetworkIpv6ConfigTemplateOpenApiVO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLanNetworkIpv6ConfigTemplateOpenApiVOWithDefaults() *LanNetworkIpv6ConfigTemplateOpenApiVO {
	this := LanNetworkIpv6ConfigTemplateOpenApiVO{}
	return &this
}

// GetDhcpv6 returns the Dhcpv6 field value if set, zero value otherwise.
func (o *LanNetworkIpv6ConfigTemplateOpenApiVO) GetDhcpv6() Dhcpv6Setting {
	if o == nil || IsNil(o.Dhcpv6) {
		var ret Dhcpv6Setting
		return ret
	}
	return *o.Dhcpv6
}

// GetDhcpv6Ok returns a tuple with the Dhcpv6 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LanNetworkIpv6ConfigTemplateOpenApiVO) GetDhcpv6Ok() (*Dhcpv6Setting, bool) {
	if o == nil || IsNil(o.Dhcpv6) {
		return nil, false
	}
	return o.Dhcpv6, true
}

// HasDhcpv6 returns a boolean if a field has been set.
func (o *LanNetworkIpv6ConfigTemplateOpenApiVO) HasDhcpv6() bool {
	if o != nil && !IsNil(o.Dhcpv6) {
		return true
	}

	return false
}

// SetDhcpv6 gets a reference to the given Dhcpv6Setting and assigns it to the Dhcpv6 field.
func (o *LanNetworkIpv6ConfigTemplateOpenApiVO) SetDhcpv6(v Dhcpv6Setting) {
	o.Dhcpv6 = &v
}

// GetEnable returns the Enable field value
func (o *LanNetworkIpv6ConfigTemplateOpenApiVO) GetEnable() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Enable
}

// GetEnableOk returns a tuple with the Enable field value
// and a boolean to check if the value has been set.
func (o *LanNetworkIpv6ConfigTemplateOpenApiVO) GetEnableOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enable, true
}

// SetEnable sets field value
func (o *LanNetworkIpv6ConfigTemplateOpenApiVO) SetEnable(v int32) {
	o.Enable = v
}

// GetProto returns the Proto field value
func (o *LanNetworkIpv6ConfigTemplateOpenApiVO) GetProto() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Proto
}

// GetProtoOk returns a tuple with the Proto field value
// and a boolean to check if the value has been set.
func (o *LanNetworkIpv6ConfigTemplateOpenApiVO) GetProtoOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Proto, true
}

// SetProto sets field value
func (o *LanNetworkIpv6ConfigTemplateOpenApiVO) SetProto(v int32) {
	o.Proto = v
}

// GetRa returns the Ra field value if set, zero value otherwise.
func (o *LanNetworkIpv6ConfigTemplateOpenApiVO) GetRa() RaSetting {
	if o == nil || IsNil(o.Ra) {
		var ret RaSetting
		return ret
	}
	return *o.Ra
}

// GetRaOk returns a tuple with the Ra field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LanNetworkIpv6ConfigTemplateOpenApiVO) GetRaOk() (*RaSetting, bool) {
	if o == nil || IsNil(o.Ra) {
		return nil, false
	}
	return o.Ra, true
}

// HasRa returns a boolean if a field has been set.
func (o *LanNetworkIpv6ConfigTemplateOpenApiVO) HasRa() bool {
	if o != nil && !IsNil(o.Ra) {
		return true
	}

	return false
}

// SetRa gets a reference to the given RaSetting and assigns it to the Ra field.
func (o *LanNetworkIpv6ConfigTemplateOpenApiVO) SetRa(v RaSetting) {
	o.Ra = &v
}

// GetRdnss returns the Rdnss field value if set, zero value otherwise.
func (o *LanNetworkIpv6ConfigTemplateOpenApiVO) GetRdnss() SlaacTemplateOpenApiVO {
	if o == nil || IsNil(o.Rdnss) {
		var ret SlaacTemplateOpenApiVO
		return ret
	}
	return *o.Rdnss
}

// GetRdnssOk returns a tuple with the Rdnss field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LanNetworkIpv6ConfigTemplateOpenApiVO) GetRdnssOk() (*SlaacTemplateOpenApiVO, bool) {
	if o == nil || IsNil(o.Rdnss) {
		return nil, false
	}
	return o.Rdnss, true
}

// HasRdnss returns a boolean if a field has been set.
func (o *LanNetworkIpv6ConfigTemplateOpenApiVO) HasRdnss() bool {
	if o != nil && !IsNil(o.Rdnss) {
		return true
	}

	return false
}

// SetRdnss gets a reference to the given SlaacTemplateOpenApiVO and assigns it to the Rdnss field.
func (o *LanNetworkIpv6ConfigTemplateOpenApiVO) SetRdnss(v SlaacTemplateOpenApiVO) {
	o.Rdnss = &v
}

// GetSlaac returns the Slaac field value if set, zero value otherwise.
func (o *LanNetworkIpv6ConfigTemplateOpenApiVO) GetSlaac() SlaacTemplateOpenApiVO {
	if o == nil || IsNil(o.Slaac) {
		var ret SlaacTemplateOpenApiVO
		return ret
	}
	return *o.Slaac
}

// GetSlaacOk returns a tuple with the Slaac field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LanNetworkIpv6ConfigTemplateOpenApiVO) GetSlaacOk() (*SlaacTemplateOpenApiVO, bool) {
	if o == nil || IsNil(o.Slaac) {
		return nil, false
	}
	return o.Slaac, true
}

// HasSlaac returns a boolean if a field has been set.
func (o *LanNetworkIpv6ConfigTemplateOpenApiVO) HasSlaac() bool {
	if o != nil && !IsNil(o.Slaac) {
		return true
	}

	return false
}

// SetSlaac gets a reference to the given SlaacTemplateOpenApiVO and assigns it to the Slaac field.
func (o *LanNetworkIpv6ConfigTemplateOpenApiVO) SetSlaac(v SlaacTemplateOpenApiVO) {
	o.Slaac = &v
}

func (o LanNetworkIpv6ConfigTemplateOpenApiVO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LanNetworkIpv6ConfigTemplateOpenApiVO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Dhcpv6) {
		toSerialize["dhcpv6"] = o.Dhcpv6
	}
	toSerialize["enable"] = o.Enable
	toSerialize["proto"] = o.Proto
	if !IsNil(o.Ra) {
		toSerialize["ra"] = o.Ra
	}
	if !IsNil(o.Rdnss) {
		toSerialize["rdnss"] = o.Rdnss
	}
	if !IsNil(o.Slaac) {
		toSerialize["slaac"] = o.Slaac
	}
	return toSerialize, nil
}

func (o *LanNetworkIpv6ConfigTemplateOpenApiVO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enable",
		"proto",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLanNetworkIpv6ConfigTemplateOpenApiVO := _LanNetworkIpv6ConfigTemplateOpenApiVO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLanNetworkIpv6ConfigTemplateOpenApiVO)

	if err != nil {
		return err
	}

	*o = LanNetworkIpv6ConfigTemplateOpenApiVO(varLanNetworkIpv6ConfigTemplateOpenApiVO)

	return err
}

type NullableLanNetworkIpv6ConfigTemplateOpenApiVO struct {
	value *LanNetworkIpv6ConfigTemplateOpenApiVO
	isSet bool
}

func (v NullableLanNetworkIpv6ConfigTemplateOpenApiVO) Get() *LanNetworkIpv6ConfigTemplateOpenApiVO {
	return v.value
}

func (v *NullableLanNetworkIpv6ConfigTemplateOpenApiVO) Set(val *LanNetworkIpv6ConfigTemplateOpenApiVO) {
	v.value = val
	v.isSet = true
}

func (v NullableLanNetworkIpv6ConfigTemplateOpenApiVO) IsSet() bool {
	return v.isSet
}

func (v *NullableLanNetworkIpv6ConfigTemplateOpenApiVO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLanNetworkIpv6ConfigTemplateOpenApiVO(val *LanNetworkIpv6ConfigTemplateOpenApiVO) *NullableLanNetworkIpv6ConfigTemplateOpenApiVO {
	return &NullableLanNetworkIpv6ConfigTemplateOpenApiVO{value: val, isSet: true}
}

func (v NullableLanNetworkIpv6ConfigTemplateOpenApiVO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLanNetworkIpv6ConfigTemplateOpenApiVO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


