/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
)

// checks if the OswStackInfoVO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OswStackInfoVO{}

// OswStackInfoVO The osw stack.
type OswStackInfoVO struct {
	// The mac of the master device of the stack device.
	MasterMac *string `json:"masterMac,omitempty"`
	// The members of the stack device.
	Members []StackMemberVO `json:"members,omitempty"`
	// The stack id of the stack device.
	StackId *string `json:"stackId,omitempty"`
	// The stack name of the stack device.
	StackName *string `json:"stackName,omitempty"`
}

// NewOswStackInfoVO instantiates a new OswStackInfoVO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOswStackInfoVO() *OswStackInfoVO {
	this := OswStackInfoVO{}
	return &this
}

// NewOswStackInfoVOWithDefaults instantiates a new OswStackInfoVO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOswStackInfoVOWithDefaults() *OswStackInfoVO {
	this := OswStackInfoVO{}
	return &this
}

// GetMasterMac returns the MasterMac field value if set, zero value otherwise.
func (o *OswStackInfoVO) GetMasterMac() string {
	if o == nil || IsNil(o.MasterMac) {
		var ret string
		return ret
	}
	return *o.MasterMac
}

// GetMasterMacOk returns a tuple with the MasterMac field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OswStackInfoVO) GetMasterMacOk() (*string, bool) {
	if o == nil || IsNil(o.MasterMac) {
		return nil, false
	}
	return o.MasterMac, true
}

// HasMasterMac returns a boolean if a field has been set.
func (o *OswStackInfoVO) HasMasterMac() bool {
	if o != nil && !IsNil(o.MasterMac) {
		return true
	}

	return false
}

// SetMasterMac gets a reference to the given string and assigns it to the MasterMac field.
func (o *OswStackInfoVO) SetMasterMac(v string) {
	o.MasterMac = &v
}

// GetMembers returns the Members field value if set, zero value otherwise.
func (o *OswStackInfoVO) GetMembers() []StackMemberVO {
	if o == nil || IsNil(o.Members) {
		var ret []StackMemberVO
		return ret
	}
	return o.Members
}

// GetMembersOk returns a tuple with the Members field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OswStackInfoVO) GetMembersOk() ([]StackMemberVO, bool) {
	if o == nil || IsNil(o.Members) {
		return nil, false
	}
	return o.Members, true
}

// HasMembers returns a boolean if a field has been set.
func (o *OswStackInfoVO) HasMembers() bool {
	if o != nil && !IsNil(o.Members) {
		return true
	}

	return false
}

// SetMembers gets a reference to the given []StackMemberVO and assigns it to the Members field.
func (o *OswStackInfoVO) SetMembers(v []StackMemberVO) {
	o.Members = v
}

// GetStackId returns the StackId field value if set, zero value otherwise.
func (o *OswStackInfoVO) GetStackId() string {
	if o == nil || IsNil(o.StackId) {
		var ret string
		return ret
	}
	return *o.StackId
}

// GetStackIdOk returns a tuple with the StackId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OswStackInfoVO) GetStackIdOk() (*string, bool) {
	if o == nil || IsNil(o.StackId) {
		return nil, false
	}
	return o.StackId, true
}

// HasStackId returns a boolean if a field has been set.
func (o *OswStackInfoVO) HasStackId() bool {
	if o != nil && !IsNil(o.StackId) {
		return true
	}

	return false
}

// SetStackId gets a reference to the given string and assigns it to the StackId field.
func (o *OswStackInfoVO) SetStackId(v string) {
	o.StackId = &v
}

// GetStackName returns the StackName field value if set, zero value otherwise.
func (o *OswStackInfoVO) GetStackName() string {
	if o == nil || IsNil(o.StackName) {
		var ret string
		return ret
	}
	return *o.StackName
}

// GetStackNameOk returns a tuple with the StackName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OswStackInfoVO) GetStackNameOk() (*string, bool) {
	if o == nil || IsNil(o.StackName) {
		return nil, false
	}
	return o.StackName, true
}

// HasStackName returns a boolean if a field has been set.
func (o *OswStackInfoVO) HasStackName() bool {
	if o != nil && !IsNil(o.StackName) {
		return true
	}

	return false
}

// SetStackName gets a reference to the given string and assigns it to the StackName field.
func (o *OswStackInfoVO) SetStackName(v string) {
	o.StackName = &v
}

func (o OswStackInfoVO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OswStackInfoVO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MasterMac) {
		toSerialize["masterMac"] = o.MasterMac
	}
	if !IsNil(o.Members) {
		toSerialize["members"] = o.Members
	}
	if !IsNil(o.StackId) {
		toSerialize["stackId"] = o.StackId
	}
	if !IsNil(o.StackName) {
		toSerialize["stackName"] = o.StackName
	}
	return toSerialize, nil
}

type NullableOswStackInfoVO struct {
	value *OswStackInfoVO
	isSet bool
}

func (v NullableOswStackInfoVO) Get() *OswStackInfoVO {
	return v.value
}

func (v *NullableOswStackInfoVO) Set(val *OswStackInfoVO) {
	v.value = val
	v.isSet = true
}

func (v NullableOswStackInfoVO) IsSet() bool {
	return v.isSet
}

func (v *NullableOswStackInfoVO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOswStackInfoVO(val *OswStackInfoVO) *NullableOswStackInfoVO {
	return &NullableOswStackInfoVO{value: val, isSet: true}
}

func (v NullableOswStackInfoVO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOswStackInfoVO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


