/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LogNotificationEditOpenApiV2VO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LogNotificationEditOpenApiV2VO{}

// LogNotificationEditOpenApiV2VO Event Notification List
type LogNotificationEditOpenApiV2VO struct {
	// Log Notification Enable or Disable Email
	Email bool `json:"email"`
	// Log Notification Enable or Disable
	Enable bool `json:"enable"`
	// For the values of Log Notification Key, refer to section 5.6.1 of the Open API Access
	Key string `json:"key"`
	// Log Notification Category Enable or Disable Webhook (This config applies to the Omada Pro Controller only and should not bu null)
	Webhook *bool `json:"webhook,omitempty"`
}

type _LogNotificationEditOpenApiV2VO LogNotificationEditOpenApiV2VO

// NewLogNotificationEditOpenApiV2VO instantiates a new LogNotificationEditOpenApiV2VO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLogNotificationEditOpenApiV2VO(email bool, enable bool, key string) *LogNotificationEditOpenApiV2VO {
	this := LogNotificationEditOpenApiV2VO{}
	this.Email = email
	this.Enable = enable
	this.Key = key
	return &this
}

// NewLogNotificationEditOpenApiV2VOWithDefaults instantiates a new LogNotificationEditOpenApiV2VO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLogNotificationEditOpenApiV2VOWithDefaults() *LogNotificationEditOpenApiV2VO {
	this := LogNotificationEditOpenApiV2VO{}
	return &this
}

// GetEmail returns the Email field value
func (o *LogNotificationEditOpenApiV2VO) GetEmail() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *LogNotificationEditOpenApiV2VO) GetEmailOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *LogNotificationEditOpenApiV2VO) SetEmail(v bool) {
	o.Email = v
}

// GetEnable returns the Enable field value
func (o *LogNotificationEditOpenApiV2VO) GetEnable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enable
}

// GetEnableOk returns a tuple with the Enable field value
// and a boolean to check if the value has been set.
func (o *LogNotificationEditOpenApiV2VO) GetEnableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enable, true
}

// SetEnable sets field value
func (o *LogNotificationEditOpenApiV2VO) SetEnable(v bool) {
	o.Enable = v
}

// GetKey returns the Key field value
func (o *LogNotificationEditOpenApiV2VO) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *LogNotificationEditOpenApiV2VO) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *LogNotificationEditOpenApiV2VO) SetKey(v string) {
	o.Key = v
}

// GetWebhook returns the Webhook field value if set, zero value otherwise.
func (o *LogNotificationEditOpenApiV2VO) GetWebhook() bool {
	if o == nil || IsNil(o.Webhook) {
		var ret bool
		return ret
	}
	return *o.Webhook
}

// GetWebhookOk returns a tuple with the Webhook field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogNotificationEditOpenApiV2VO) GetWebhookOk() (*bool, bool) {
	if o == nil || IsNil(o.Webhook) {
		return nil, false
	}
	return o.Webhook, true
}

// HasWebhook returns a boolean if a field has been set.
func (o *LogNotificationEditOpenApiV2VO) HasWebhook() bool {
	if o != nil && !IsNil(o.Webhook) {
		return true
	}

	return false
}

// SetWebhook gets a reference to the given bool and assigns it to the Webhook field.
func (o *LogNotificationEditOpenApiV2VO) SetWebhook(v bool) {
	o.Webhook = &v
}

func (o LogNotificationEditOpenApiV2VO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LogNotificationEditOpenApiV2VO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["enable"] = o.Enable
	toSerialize["key"] = o.Key
	if !IsNil(o.Webhook) {
		toSerialize["webhook"] = o.Webhook
	}
	return toSerialize, nil
}

func (o *LogNotificationEditOpenApiV2VO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"enable",
		"key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLogNotificationEditOpenApiV2VO := _LogNotificationEditOpenApiV2VO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLogNotificationEditOpenApiV2VO)

	if err != nil {
		return err
	}

	*o = LogNotificationEditOpenApiV2VO(varLogNotificationEditOpenApiV2VO)

	return err
}

type NullableLogNotificationEditOpenApiV2VO struct {
	value *LogNotificationEditOpenApiV2VO
	isSet bool
}

func (v NullableLogNotificationEditOpenApiV2VO) Get() *LogNotificationEditOpenApiV2VO {
	return v.value
}

func (v *NullableLogNotificationEditOpenApiV2VO) Set(val *LogNotificationEditOpenApiV2VO) {
	v.value = val
	v.isSet = true
}

func (v NullableLogNotificationEditOpenApiV2VO) IsSet() bool {
	return v.isSet
}

func (v *NullableLogNotificationEditOpenApiV2VO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLogNotificationEditOpenApiV2VO(val *LogNotificationEditOpenApiV2VO) *NullableLogNotificationEditOpenApiV2VO {
	return &NullableLogNotificationEditOpenApiV2VO{value: val, isSet: true}
}

func (v NullableLogNotificationEditOpenApiV2VO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLogNotificationEditOpenApiV2VO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


