/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApMvlanSettingOpenApiVO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApMvlanSettingOpenApiVO{}

// ApMvlanSettingOpenApiVO Management VLAN setting.
type ApMvlanSettingOpenApiVO struct {
	// When mvlanNetworkId is bridge vlan, mvlanBridgeVlan has a value.
	BridgeVlan *int32 `json:"bridgeVlan,omitempty"`
	// This field indicates the currently effective lanNetworkId.
	LanNetworkId *string `json:"lanNetworkId,omitempty"`
	// Mode for the AP management VLAN configuration to take effect.[0:Default,1:Custom]
	Mode int32 `json:"mode"`
}

type _ApMvlanSettingOpenApiVO ApMvlanSettingOpenApiVO

// NewApMvlanSettingOpenApiVO instantiates a new ApMvlanSettingOpenApiVO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApMvlanSettingOpenApiVO(mode int32) *ApMvlanSettingOpenApiVO {
	this := ApMvlanSettingOpenApiVO{}
	this.Mode = mode
	return &this
}

// NewApMvlanSettingOpenApiVOWithDefaults instantiates a new ApMvlanSettingOpenApiVO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApMvlanSettingOpenApiVOWithDefaults() *ApMvlanSettingOpenApiVO {
	this := ApMvlanSettingOpenApiVO{}
	return &this
}

// GetBridgeVlan returns the BridgeVlan field value if set, zero value otherwise.
func (o *ApMvlanSettingOpenApiVO) GetBridgeVlan() int32 {
	if o == nil || IsNil(o.BridgeVlan) {
		var ret int32
		return ret
	}
	return *o.BridgeVlan
}

// GetBridgeVlanOk returns a tuple with the BridgeVlan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApMvlanSettingOpenApiVO) GetBridgeVlanOk() (*int32, bool) {
	if o == nil || IsNil(o.BridgeVlan) {
		return nil, false
	}
	return o.BridgeVlan, true
}

// HasBridgeVlan returns a boolean if a field has been set.
func (o *ApMvlanSettingOpenApiVO) HasBridgeVlan() bool {
	if o != nil && !IsNil(o.BridgeVlan) {
		return true
	}

	return false
}

// SetBridgeVlan gets a reference to the given int32 and assigns it to the BridgeVlan field.
func (o *ApMvlanSettingOpenApiVO) SetBridgeVlan(v int32) {
	o.BridgeVlan = &v
}

// GetLanNetworkId returns the LanNetworkId field value if set, zero value otherwise.
func (o *ApMvlanSettingOpenApiVO) GetLanNetworkId() string {
	if o == nil || IsNil(o.LanNetworkId) {
		var ret string
		return ret
	}
	return *o.LanNetworkId
}

// GetLanNetworkIdOk returns a tuple with the LanNetworkId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApMvlanSettingOpenApiVO) GetLanNetworkIdOk() (*string, bool) {
	if o == nil || IsNil(o.LanNetworkId) {
		return nil, false
	}
	return o.LanNetworkId, true
}

// HasLanNetworkId returns a boolean if a field has been set.
func (o *ApMvlanSettingOpenApiVO) HasLanNetworkId() bool {
	if o != nil && !IsNil(o.LanNetworkId) {
		return true
	}

	return false
}

// SetLanNetworkId gets a reference to the given string and assigns it to the LanNetworkId field.
func (o *ApMvlanSettingOpenApiVO) SetLanNetworkId(v string) {
	o.LanNetworkId = &v
}

// GetMode returns the Mode field value
func (o *ApMvlanSettingOpenApiVO) GetMode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *ApMvlanSettingOpenApiVO) GetModeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *ApMvlanSettingOpenApiVO) SetMode(v int32) {
	o.Mode = v
}

func (o ApMvlanSettingOpenApiVO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApMvlanSettingOpenApiVO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BridgeVlan) {
		toSerialize["bridgeVlan"] = o.BridgeVlan
	}
	if !IsNil(o.LanNetworkId) {
		toSerialize["lanNetworkId"] = o.LanNetworkId
	}
	toSerialize["mode"] = o.Mode
	return toSerialize, nil
}

func (o *ApMvlanSettingOpenApiVO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApMvlanSettingOpenApiVO := _ApMvlanSettingOpenApiVO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApMvlanSettingOpenApiVO)

	if err != nil {
		return err
	}

	*o = ApMvlanSettingOpenApiVO(varApMvlanSettingOpenApiVO)

	return err
}

type NullableApMvlanSettingOpenApiVO struct {
	value *ApMvlanSettingOpenApiVO
	isSet bool
}

func (v NullableApMvlanSettingOpenApiVO) Get() *ApMvlanSettingOpenApiVO {
	return v.value
}

func (v *NullableApMvlanSettingOpenApiVO) Set(val *ApMvlanSettingOpenApiVO) {
	v.value = val
	v.isSet = true
}

func (v NullableApMvlanSettingOpenApiVO) IsSet() bool {
	return v.isSet
}

func (v *NullableApMvlanSettingOpenApiVO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApMvlanSettingOpenApiVO(val *ApMvlanSettingOpenApiVO) *NullableApMvlanSettingOpenApiVO {
	return &NullableApMvlanSettingOpenApiVO{value: val, isSet: true}
}

func (v NullableApMvlanSettingOpenApiVO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApMvlanSettingOpenApiVO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


