/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeviceBindBriefOpenApiVO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceBindBriefOpenApiVO{}

// DeviceBindBriefOpenApiVO struct for DeviceBindBriefOpenApiVO
type DeviceBindBriefOpenApiVO struct {
	// The mac address of device, like AA-BB-CC-DD-EE-FF.
	Mac string `json:"mac"`
	// The ID of target site.
	SiteId string `json:"siteId"`
}

type _DeviceBindBriefOpenApiVO DeviceBindBriefOpenApiVO

// NewDeviceBindBriefOpenApiVO instantiates a new DeviceBindBriefOpenApiVO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceBindBriefOpenApiVO(mac string, siteId string) *DeviceBindBriefOpenApiVO {
	this := DeviceBindBriefOpenApiVO{}
	this.Mac = mac
	this.SiteId = siteId
	return &this
}

// NewDeviceBindBriefOpenApiVOWithDefaults instantiates a new DeviceBindBriefOpenApiVO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceBindBriefOpenApiVOWithDefaults() *DeviceBindBriefOpenApiVO {
	this := DeviceBindBriefOpenApiVO{}
	return &this
}

// GetMac returns the Mac field value
func (o *DeviceBindBriefOpenApiVO) GetMac() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mac
}

// GetMacOk returns a tuple with the Mac field value
// and a boolean to check if the value has been set.
func (o *DeviceBindBriefOpenApiVO) GetMacOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mac, true
}

// SetMac sets field value
func (o *DeviceBindBriefOpenApiVO) SetMac(v string) {
	o.Mac = v
}

// GetSiteId returns the SiteId field value
func (o *DeviceBindBriefOpenApiVO) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *DeviceBindBriefOpenApiVO) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *DeviceBindBriefOpenApiVO) SetSiteId(v string) {
	o.SiteId = v
}

func (o DeviceBindBriefOpenApiVO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceBindBriefOpenApiVO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mac"] = o.Mac
	toSerialize["siteId"] = o.SiteId
	return toSerialize, nil
}

func (o *DeviceBindBriefOpenApiVO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mac",
		"siteId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeviceBindBriefOpenApiVO := _DeviceBindBriefOpenApiVO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeviceBindBriefOpenApiVO)

	if err != nil {
		return err
	}

	*o = DeviceBindBriefOpenApiVO(varDeviceBindBriefOpenApiVO)

	return err
}

type NullableDeviceBindBriefOpenApiVO struct {
	value *DeviceBindBriefOpenApiVO
	isSet bool
}

func (v NullableDeviceBindBriefOpenApiVO) Get() *DeviceBindBriefOpenApiVO {
	return v.value
}

func (v *NullableDeviceBindBriefOpenApiVO) Set(val *DeviceBindBriefOpenApiVO) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceBindBriefOpenApiVO) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceBindBriefOpenApiVO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceBindBriefOpenApiVO(val *DeviceBindBriefOpenApiVO) *NullableDeviceBindBriefOpenApiVO {
	return &NullableDeviceBindBriefOpenApiVO{value: val, isSet: true}
}

func (v NullableDeviceBindBriefOpenApiVO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceBindBriefOpenApiVO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


