/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
)

// checks if the GatewayPortSettingConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayPortSettingConfig{}

// GatewayPortSettingConfig struct for GatewayPortSettingConfig
type GatewayPortSettingConfig struct {
	DslSettings *DslSettings `json:"dslSettings,omitempty"`
	// Port duplex mode should be a value as follows: 0: Auto; 1: Half; 2: Full
	Duplex *int32 `json:"duplex,omitempty"`
	// Enable flow control or not.(When the port supports flow control.)
	FlowControl *bool `json:"flowControl,omitempty"`
	// Port link speed should be a value as follows: 0: Auto; 1: 10M; 2: 100M; 3: 1000M; 4: 2500M; 5: 10G; 6: 5G
	LinkSpeed *int32 `json:"linkSpeed,omitempty"`
	// Port enabled mirror or not
	MirrorEnable *bool `json:"mirrorEnable,omitempty"`
	// Port mirror mode should be a value as follow: 0: ingress; 1: egress; 2: ingress and egress.
	MirrorMode *int32 `json:"mirrorMode,omitempty"`
	// Mirrored Ports Set
	MirroredPorts []int32 `json:"mirroredPorts,omitempty"`
	// Enter a value as follows: 0: off; 1: 802.3at/af.
	PoeMode *int32 `json:"poeMode,omitempty"`
	// Pvid(only for lan port.)
	Pvid *int32 `json:"pvid,omitempty"`
	// Enable port or not, status should be a value as follows: 0: disable; 1: enable.(When the port supports status.)
	Status *int32 `json:"status,omitempty"`
}

// NewGatewayPortSettingConfig instantiates a new GatewayPortSettingConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayPortSettingConfig() *GatewayPortSettingConfig {
	this := GatewayPortSettingConfig{}
	return &this
}

// NewGatewayPortSettingConfigWithDefaults instantiates a new GatewayPortSettingConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayPortSettingConfigWithDefaults() *GatewayPortSettingConfig {
	this := GatewayPortSettingConfig{}
	return &this
}

// GetDslSettings returns the DslSettings field value if set, zero value otherwise.
func (o *GatewayPortSettingConfig) GetDslSettings() DslSettings {
	if o == nil || IsNil(o.DslSettings) {
		var ret DslSettings
		return ret
	}
	return *o.DslSettings
}

// GetDslSettingsOk returns a tuple with the DslSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayPortSettingConfig) GetDslSettingsOk() (*DslSettings, bool) {
	if o == nil || IsNil(o.DslSettings) {
		return nil, false
	}
	return o.DslSettings, true
}

// HasDslSettings returns a boolean if a field has been set.
func (o *GatewayPortSettingConfig) HasDslSettings() bool {
	if o != nil && !IsNil(o.DslSettings) {
		return true
	}

	return false
}

// SetDslSettings gets a reference to the given DslSettings and assigns it to the DslSettings field.
func (o *GatewayPortSettingConfig) SetDslSettings(v DslSettings) {
	o.DslSettings = &v
}

// GetDuplex returns the Duplex field value if set, zero value otherwise.
func (o *GatewayPortSettingConfig) GetDuplex() int32 {
	if o == nil || IsNil(o.Duplex) {
		var ret int32
		return ret
	}
	return *o.Duplex
}

// GetDuplexOk returns a tuple with the Duplex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayPortSettingConfig) GetDuplexOk() (*int32, bool) {
	if o == nil || IsNil(o.Duplex) {
		return nil, false
	}
	return o.Duplex, true
}

// HasDuplex returns a boolean if a field has been set.
func (o *GatewayPortSettingConfig) HasDuplex() bool {
	if o != nil && !IsNil(o.Duplex) {
		return true
	}

	return false
}

// SetDuplex gets a reference to the given int32 and assigns it to the Duplex field.
func (o *GatewayPortSettingConfig) SetDuplex(v int32) {
	o.Duplex = &v
}

// GetFlowControl returns the FlowControl field value if set, zero value otherwise.
func (o *GatewayPortSettingConfig) GetFlowControl() bool {
	if o == nil || IsNil(o.FlowControl) {
		var ret bool
		return ret
	}
	return *o.FlowControl
}

// GetFlowControlOk returns a tuple with the FlowControl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayPortSettingConfig) GetFlowControlOk() (*bool, bool) {
	if o == nil || IsNil(o.FlowControl) {
		return nil, false
	}
	return o.FlowControl, true
}

// HasFlowControl returns a boolean if a field has been set.
func (o *GatewayPortSettingConfig) HasFlowControl() bool {
	if o != nil && !IsNil(o.FlowControl) {
		return true
	}

	return false
}

// SetFlowControl gets a reference to the given bool and assigns it to the FlowControl field.
func (o *GatewayPortSettingConfig) SetFlowControl(v bool) {
	o.FlowControl = &v
}

// GetLinkSpeed returns the LinkSpeed field value if set, zero value otherwise.
func (o *GatewayPortSettingConfig) GetLinkSpeed() int32 {
	if o == nil || IsNil(o.LinkSpeed) {
		var ret int32
		return ret
	}
	return *o.LinkSpeed
}

// GetLinkSpeedOk returns a tuple with the LinkSpeed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayPortSettingConfig) GetLinkSpeedOk() (*int32, bool) {
	if o == nil || IsNil(o.LinkSpeed) {
		return nil, false
	}
	return o.LinkSpeed, true
}

// HasLinkSpeed returns a boolean if a field has been set.
func (o *GatewayPortSettingConfig) HasLinkSpeed() bool {
	if o != nil && !IsNil(o.LinkSpeed) {
		return true
	}

	return false
}

// SetLinkSpeed gets a reference to the given int32 and assigns it to the LinkSpeed field.
func (o *GatewayPortSettingConfig) SetLinkSpeed(v int32) {
	o.LinkSpeed = &v
}

// GetMirrorEnable returns the MirrorEnable field value if set, zero value otherwise.
func (o *GatewayPortSettingConfig) GetMirrorEnable() bool {
	if o == nil || IsNil(o.MirrorEnable) {
		var ret bool
		return ret
	}
	return *o.MirrorEnable
}

// GetMirrorEnableOk returns a tuple with the MirrorEnable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayPortSettingConfig) GetMirrorEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.MirrorEnable) {
		return nil, false
	}
	return o.MirrorEnable, true
}

// HasMirrorEnable returns a boolean if a field has been set.
func (o *GatewayPortSettingConfig) HasMirrorEnable() bool {
	if o != nil && !IsNil(o.MirrorEnable) {
		return true
	}

	return false
}

// SetMirrorEnable gets a reference to the given bool and assigns it to the MirrorEnable field.
func (o *GatewayPortSettingConfig) SetMirrorEnable(v bool) {
	o.MirrorEnable = &v
}

// GetMirrorMode returns the MirrorMode field value if set, zero value otherwise.
func (o *GatewayPortSettingConfig) GetMirrorMode() int32 {
	if o == nil || IsNil(o.MirrorMode) {
		var ret int32
		return ret
	}
	return *o.MirrorMode
}

// GetMirrorModeOk returns a tuple with the MirrorMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayPortSettingConfig) GetMirrorModeOk() (*int32, bool) {
	if o == nil || IsNil(o.MirrorMode) {
		return nil, false
	}
	return o.MirrorMode, true
}

// HasMirrorMode returns a boolean if a field has been set.
func (o *GatewayPortSettingConfig) HasMirrorMode() bool {
	if o != nil && !IsNil(o.MirrorMode) {
		return true
	}

	return false
}

// SetMirrorMode gets a reference to the given int32 and assigns it to the MirrorMode field.
func (o *GatewayPortSettingConfig) SetMirrorMode(v int32) {
	o.MirrorMode = &v
}

// GetMirroredPorts returns the MirroredPorts field value if set, zero value otherwise.
func (o *GatewayPortSettingConfig) GetMirroredPorts() []int32 {
	if o == nil || IsNil(o.MirroredPorts) {
		var ret []int32
		return ret
	}
	return o.MirroredPorts
}

// GetMirroredPortsOk returns a tuple with the MirroredPorts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayPortSettingConfig) GetMirroredPortsOk() ([]int32, bool) {
	if o == nil || IsNil(o.MirroredPorts) {
		return nil, false
	}
	return o.MirroredPorts, true
}

// HasMirroredPorts returns a boolean if a field has been set.
func (o *GatewayPortSettingConfig) HasMirroredPorts() bool {
	if o != nil && !IsNil(o.MirroredPorts) {
		return true
	}

	return false
}

// SetMirroredPorts gets a reference to the given []int32 and assigns it to the MirroredPorts field.
func (o *GatewayPortSettingConfig) SetMirroredPorts(v []int32) {
	o.MirroredPorts = v
}

// GetPoeMode returns the PoeMode field value if set, zero value otherwise.
func (o *GatewayPortSettingConfig) GetPoeMode() int32 {
	if o == nil || IsNil(o.PoeMode) {
		var ret int32
		return ret
	}
	return *o.PoeMode
}

// GetPoeModeOk returns a tuple with the PoeMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayPortSettingConfig) GetPoeModeOk() (*int32, bool) {
	if o == nil || IsNil(o.PoeMode) {
		return nil, false
	}
	return o.PoeMode, true
}

// HasPoeMode returns a boolean if a field has been set.
func (o *GatewayPortSettingConfig) HasPoeMode() bool {
	if o != nil && !IsNil(o.PoeMode) {
		return true
	}

	return false
}

// SetPoeMode gets a reference to the given int32 and assigns it to the PoeMode field.
func (o *GatewayPortSettingConfig) SetPoeMode(v int32) {
	o.PoeMode = &v
}

// GetPvid returns the Pvid field value if set, zero value otherwise.
func (o *GatewayPortSettingConfig) GetPvid() int32 {
	if o == nil || IsNil(o.Pvid) {
		var ret int32
		return ret
	}
	return *o.Pvid
}

// GetPvidOk returns a tuple with the Pvid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayPortSettingConfig) GetPvidOk() (*int32, bool) {
	if o == nil || IsNil(o.Pvid) {
		return nil, false
	}
	return o.Pvid, true
}

// HasPvid returns a boolean if a field has been set.
func (o *GatewayPortSettingConfig) HasPvid() bool {
	if o != nil && !IsNil(o.Pvid) {
		return true
	}

	return false
}

// SetPvid gets a reference to the given int32 and assigns it to the Pvid field.
func (o *GatewayPortSettingConfig) SetPvid(v int32) {
	o.Pvid = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GatewayPortSettingConfig) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayPortSettingConfig) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GatewayPortSettingConfig) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *GatewayPortSettingConfig) SetStatus(v int32) {
	o.Status = &v
}

func (o GatewayPortSettingConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayPortSettingConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DslSettings) {
		toSerialize["dslSettings"] = o.DslSettings
	}
	if !IsNil(o.Duplex) {
		toSerialize["duplex"] = o.Duplex
	}
	if !IsNil(o.FlowControl) {
		toSerialize["flowControl"] = o.FlowControl
	}
	if !IsNil(o.LinkSpeed) {
		toSerialize["linkSpeed"] = o.LinkSpeed
	}
	if !IsNil(o.MirrorEnable) {
		toSerialize["mirrorEnable"] = o.MirrorEnable
	}
	if !IsNil(o.MirrorMode) {
		toSerialize["mirrorMode"] = o.MirrorMode
	}
	if !IsNil(o.MirroredPorts) {
		toSerialize["mirroredPorts"] = o.MirroredPorts
	}
	if !IsNil(o.PoeMode) {
		toSerialize["poeMode"] = o.PoeMode
	}
	if !IsNil(o.Pvid) {
		toSerialize["pvid"] = o.Pvid
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableGatewayPortSettingConfig struct {
	value *GatewayPortSettingConfig
	isSet bool
}

func (v NullableGatewayPortSettingConfig) Get() *GatewayPortSettingConfig {
	return v.value
}

func (v *NullableGatewayPortSettingConfig) Set(val *GatewayPortSettingConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayPortSettingConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayPortSettingConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayPortSettingConfig(val *GatewayPortSettingConfig) *NullableGatewayPortSettingConfig {
	return &NullableGatewayPortSettingConfig{value: val, isSet: true}
}

func (v NullableGatewayPortSettingConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayPortSettingConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


