/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
)

// checks if the RecipientsVO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecipientsVO{}

// RecipientsVO Recipients of the incident notifiction
type RecipientsVO struct {
	// The email address of the recipient.
	Email *string `json:"email,omitempty"`
}

// NewRecipientsVO instantiates a new RecipientsVO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecipientsVO() *RecipientsVO {
	this := RecipientsVO{}
	return &this
}

// NewRecipientsVOWithDefaults instantiates a new RecipientsVO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecipientsVOWithDefaults() *RecipientsVO {
	this := RecipientsVO{}
	return &this
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *RecipientsVO) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecipientsVO) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *RecipientsVO) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *RecipientsVO) SetEmail(v string) {
	o.Email = &v
}

func (o RecipientsVO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecipientsVO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	return toSerialize, nil
}

type NullableRecipientsVO struct {
	value *RecipientsVO
	isSet bool
}

func (v NullableRecipientsVO) Get() *RecipientsVO {
	return v.value
}

func (v *NullableRecipientsVO) Set(val *RecipientsVO) {
	v.value = val
	v.isSet = true
}

func (v NullableRecipientsVO) IsSet() bool {
	return v.isSet
}

func (v *NullableRecipientsVO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecipientsVO(val *RecipientsVO) *NullableRecipientsVO {
	return &NullableRecipientsVO{value: val, isSet: true}
}

func (v NullableRecipientsVO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecipientsVO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


