/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
)

// checks if the SiteTemplateSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SiteTemplateSettings{}

// SiteTemplateSettings struct for SiteTemplateSettings
type SiteTemplateSettings struct {
	Dst *SiteSettingDst `json:"dst,omitempty"`
	// site template id
	Id *string `json:"id,omitempty"`
	// site template name
	Name *string `json:"name,omitempty"`
	// Network Time Protocol enable
	NtpEnable *bool `json:"ntpEnable,omitempty"`
	// ntp servers
	NtpServers []NtpServer `json:"ntpServers,omitempty"`
	// omadacId
	OmadacId *string `json:"omadacId,omitempty"`
	// list of supported configurations
	Settings []string `json:"settings,omitempty"`
	// time zone
	TimeZone *string `json:"timeZone,omitempty"`
	// site type. 0：Basic；1：Pro
	Type *int32 `json:"type,omitempty"`
}

// NewSiteTemplateSettings instantiates a new SiteTemplateSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteTemplateSettings() *SiteTemplateSettings {
	this := SiteTemplateSettings{}
	return &this
}

// NewSiteTemplateSettingsWithDefaults instantiates a new SiteTemplateSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteTemplateSettingsWithDefaults() *SiteTemplateSettings {
	this := SiteTemplateSettings{}
	return &this
}

// GetDst returns the Dst field value if set, zero value otherwise.
func (o *SiteTemplateSettings) GetDst() SiteSettingDst {
	if o == nil || IsNil(o.Dst) {
		var ret SiteSettingDst
		return ret
	}
	return *o.Dst
}

// GetDstOk returns a tuple with the Dst field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteTemplateSettings) GetDstOk() (*SiteSettingDst, bool) {
	if o == nil || IsNil(o.Dst) {
		return nil, false
	}
	return o.Dst, true
}

// HasDst returns a boolean if a field has been set.
func (o *SiteTemplateSettings) HasDst() bool {
	if o != nil && !IsNil(o.Dst) {
		return true
	}

	return false
}

// SetDst gets a reference to the given SiteSettingDst and assigns it to the Dst field.
func (o *SiteTemplateSettings) SetDst(v SiteSettingDst) {
	o.Dst = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SiteTemplateSettings) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteTemplateSettings) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SiteTemplateSettings) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SiteTemplateSettings) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SiteTemplateSettings) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteTemplateSettings) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SiteTemplateSettings) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SiteTemplateSettings) SetName(v string) {
	o.Name = &v
}

// GetNtpEnable returns the NtpEnable field value if set, zero value otherwise.
func (o *SiteTemplateSettings) GetNtpEnable() bool {
	if o == nil || IsNil(o.NtpEnable) {
		var ret bool
		return ret
	}
	return *o.NtpEnable
}

// GetNtpEnableOk returns a tuple with the NtpEnable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteTemplateSettings) GetNtpEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.NtpEnable) {
		return nil, false
	}
	return o.NtpEnable, true
}

// HasNtpEnable returns a boolean if a field has been set.
func (o *SiteTemplateSettings) HasNtpEnable() bool {
	if o != nil && !IsNil(o.NtpEnable) {
		return true
	}

	return false
}

// SetNtpEnable gets a reference to the given bool and assigns it to the NtpEnable field.
func (o *SiteTemplateSettings) SetNtpEnable(v bool) {
	o.NtpEnable = &v
}

// GetNtpServers returns the NtpServers field value if set, zero value otherwise.
func (o *SiteTemplateSettings) GetNtpServers() []NtpServer {
	if o == nil || IsNil(o.NtpServers) {
		var ret []NtpServer
		return ret
	}
	return o.NtpServers
}

// GetNtpServersOk returns a tuple with the NtpServers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteTemplateSettings) GetNtpServersOk() ([]NtpServer, bool) {
	if o == nil || IsNil(o.NtpServers) {
		return nil, false
	}
	return o.NtpServers, true
}

// HasNtpServers returns a boolean if a field has been set.
func (o *SiteTemplateSettings) HasNtpServers() bool {
	if o != nil && !IsNil(o.NtpServers) {
		return true
	}

	return false
}

// SetNtpServers gets a reference to the given []NtpServer and assigns it to the NtpServers field.
func (o *SiteTemplateSettings) SetNtpServers(v []NtpServer) {
	o.NtpServers = v
}

// GetOmadacId returns the OmadacId field value if set, zero value otherwise.
func (o *SiteTemplateSettings) GetOmadacId() string {
	if o == nil || IsNil(o.OmadacId) {
		var ret string
		return ret
	}
	return *o.OmadacId
}

// GetOmadacIdOk returns a tuple with the OmadacId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteTemplateSettings) GetOmadacIdOk() (*string, bool) {
	if o == nil || IsNil(o.OmadacId) {
		return nil, false
	}
	return o.OmadacId, true
}

// HasOmadacId returns a boolean if a field has been set.
func (o *SiteTemplateSettings) HasOmadacId() bool {
	if o != nil && !IsNil(o.OmadacId) {
		return true
	}

	return false
}

// SetOmadacId gets a reference to the given string and assigns it to the OmadacId field.
func (o *SiteTemplateSettings) SetOmadacId(v string) {
	o.OmadacId = &v
}

// GetSettings returns the Settings field value if set, zero value otherwise.
func (o *SiteTemplateSettings) GetSettings() []string {
	if o == nil || IsNil(o.Settings) {
		var ret []string
		return ret
	}
	return o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteTemplateSettings) GetSettingsOk() ([]string, bool) {
	if o == nil || IsNil(o.Settings) {
		return nil, false
	}
	return o.Settings, true
}

// HasSettings returns a boolean if a field has been set.
func (o *SiteTemplateSettings) HasSettings() bool {
	if o != nil && !IsNil(o.Settings) {
		return true
	}

	return false
}

// SetSettings gets a reference to the given []string and assigns it to the Settings field.
func (o *SiteTemplateSettings) SetSettings(v []string) {
	o.Settings = v
}

// GetTimeZone returns the TimeZone field value if set, zero value otherwise.
func (o *SiteTemplateSettings) GetTimeZone() string {
	if o == nil || IsNil(o.TimeZone) {
		var ret string
		return ret
	}
	return *o.TimeZone
}

// GetTimeZoneOk returns a tuple with the TimeZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteTemplateSettings) GetTimeZoneOk() (*string, bool) {
	if o == nil || IsNil(o.TimeZone) {
		return nil, false
	}
	return o.TimeZone, true
}

// HasTimeZone returns a boolean if a field has been set.
func (o *SiteTemplateSettings) HasTimeZone() bool {
	if o != nil && !IsNil(o.TimeZone) {
		return true
	}

	return false
}

// SetTimeZone gets a reference to the given string and assigns it to the TimeZone field.
func (o *SiteTemplateSettings) SetTimeZone(v string) {
	o.TimeZone = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *SiteTemplateSettings) GetType() int32 {
	if o == nil || IsNil(o.Type) {
		var ret int32
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteTemplateSettings) GetTypeOk() (*int32, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *SiteTemplateSettings) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given int32 and assigns it to the Type field.
func (o *SiteTemplateSettings) SetType(v int32) {
	o.Type = &v
}

func (o SiteTemplateSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SiteTemplateSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Dst) {
		toSerialize["dst"] = o.Dst
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.NtpEnable) {
		toSerialize["ntpEnable"] = o.NtpEnable
	}
	if !IsNil(o.NtpServers) {
		toSerialize["ntpServers"] = o.NtpServers
	}
	if !IsNil(o.OmadacId) {
		toSerialize["omadacId"] = o.OmadacId
	}
	if !IsNil(o.Settings) {
		toSerialize["settings"] = o.Settings
	}
	if !IsNil(o.TimeZone) {
		toSerialize["timeZone"] = o.TimeZone
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableSiteTemplateSettings struct {
	value *SiteTemplateSettings
	isSet bool
}

func (v NullableSiteTemplateSettings) Get() *SiteTemplateSettings {
	return v.value
}

func (v *NullableSiteTemplateSettings) Set(val *SiteTemplateSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteTemplateSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteTemplateSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteTemplateSettings(val *SiteTemplateSettings) *NullableSiteTemplateSettings {
	return &NullableSiteTemplateSettings{value: val, isSet: true}
}

func (v NullableSiteTemplateSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteTemplateSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


