/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
)

// checks if the ClientsWithOnBoardingTimes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientsWithOnBoardingTimes{}

// ClientsWithOnBoardingTimes Client distribution with association times.
type ClientsWithOnBoardingTimes struct {
	// Number of clients with failed association,
	Fails *int32 `json:"fails,omitempty"`
	// Number of clients with association time less than 4 seconds and greater than or equal to 2 seconds.
	From2To4sNum *int32 `json:"from2To4sNum,omitempty"`
	// Number of clients with association time less than 6 seconds and greater than or equal to 4 seconds.
	From4To6sNum *int32 `json:"from4To6sNum,omitempty"`
	// Number of clients with association time less than 8 seconds and greater than or equal to 6 seconds.
	From6To8sNum *int32 `json:"from6To8sNum,omitempty"`
	// Number of clients with association time less than 10 seconds and greater than or equal to 8 seconds.
	From8To10sNum *int32 `json:"from8To10sNum,omitempty"`
	// Percentage of association time less than 10 seconds.
	LessThan10sPercent *int32 `json:"lessThan10sPercent,omitempty"`
	// Number of clients with association time less than 2 seconds.
	LessThan2sNum *int32 `json:"lessThan2sNum,omitempty"`
	// Number of clients with association time greater than or equal to 10 seconds.
	MoreThan10sNum *int32 `json:"moreThan10sNum,omitempty"`
}

// NewClientsWithOnBoardingTimes instantiates a new ClientsWithOnBoardingTimes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientsWithOnBoardingTimes() *ClientsWithOnBoardingTimes {
	this := ClientsWithOnBoardingTimes{}
	return &this
}

// NewClientsWithOnBoardingTimesWithDefaults instantiates a new ClientsWithOnBoardingTimes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientsWithOnBoardingTimesWithDefaults() *ClientsWithOnBoardingTimes {
	this := ClientsWithOnBoardingTimes{}
	return &this
}

// GetFails returns the Fails field value if set, zero value otherwise.
func (o *ClientsWithOnBoardingTimes) GetFails() int32 {
	if o == nil || IsNil(o.Fails) {
		var ret int32
		return ret
	}
	return *o.Fails
}

// GetFailsOk returns a tuple with the Fails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientsWithOnBoardingTimes) GetFailsOk() (*int32, bool) {
	if o == nil || IsNil(o.Fails) {
		return nil, false
	}
	return o.Fails, true
}

// HasFails returns a boolean if a field has been set.
func (o *ClientsWithOnBoardingTimes) HasFails() bool {
	if o != nil && !IsNil(o.Fails) {
		return true
	}

	return false
}

// SetFails gets a reference to the given int32 and assigns it to the Fails field.
func (o *ClientsWithOnBoardingTimes) SetFails(v int32) {
	o.Fails = &v
}

// GetFrom2To4sNum returns the From2To4sNum field value if set, zero value otherwise.
func (o *ClientsWithOnBoardingTimes) GetFrom2To4sNum() int32 {
	if o == nil || IsNil(o.From2To4sNum) {
		var ret int32
		return ret
	}
	return *o.From2To4sNum
}

// GetFrom2To4sNumOk returns a tuple with the From2To4sNum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientsWithOnBoardingTimes) GetFrom2To4sNumOk() (*int32, bool) {
	if o == nil || IsNil(o.From2To4sNum) {
		return nil, false
	}
	return o.From2To4sNum, true
}

// HasFrom2To4sNum returns a boolean if a field has been set.
func (o *ClientsWithOnBoardingTimes) HasFrom2To4sNum() bool {
	if o != nil && !IsNil(o.From2To4sNum) {
		return true
	}

	return false
}

// SetFrom2To4sNum gets a reference to the given int32 and assigns it to the From2To4sNum field.
func (o *ClientsWithOnBoardingTimes) SetFrom2To4sNum(v int32) {
	o.From2To4sNum = &v
}

// GetFrom4To6sNum returns the From4To6sNum field value if set, zero value otherwise.
func (o *ClientsWithOnBoardingTimes) GetFrom4To6sNum() int32 {
	if o == nil || IsNil(o.From4To6sNum) {
		var ret int32
		return ret
	}
	return *o.From4To6sNum
}

// GetFrom4To6sNumOk returns a tuple with the From4To6sNum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientsWithOnBoardingTimes) GetFrom4To6sNumOk() (*int32, bool) {
	if o == nil || IsNil(o.From4To6sNum) {
		return nil, false
	}
	return o.From4To6sNum, true
}

// HasFrom4To6sNum returns a boolean if a field has been set.
func (o *ClientsWithOnBoardingTimes) HasFrom4To6sNum() bool {
	if o != nil && !IsNil(o.From4To6sNum) {
		return true
	}

	return false
}

// SetFrom4To6sNum gets a reference to the given int32 and assigns it to the From4To6sNum field.
func (o *ClientsWithOnBoardingTimes) SetFrom4To6sNum(v int32) {
	o.From4To6sNum = &v
}

// GetFrom6To8sNum returns the From6To8sNum field value if set, zero value otherwise.
func (o *ClientsWithOnBoardingTimes) GetFrom6To8sNum() int32 {
	if o == nil || IsNil(o.From6To8sNum) {
		var ret int32
		return ret
	}
	return *o.From6To8sNum
}

// GetFrom6To8sNumOk returns a tuple with the From6To8sNum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientsWithOnBoardingTimes) GetFrom6To8sNumOk() (*int32, bool) {
	if o == nil || IsNil(o.From6To8sNum) {
		return nil, false
	}
	return o.From6To8sNum, true
}

// HasFrom6To8sNum returns a boolean if a field has been set.
func (o *ClientsWithOnBoardingTimes) HasFrom6To8sNum() bool {
	if o != nil && !IsNil(o.From6To8sNum) {
		return true
	}

	return false
}

// SetFrom6To8sNum gets a reference to the given int32 and assigns it to the From6To8sNum field.
func (o *ClientsWithOnBoardingTimes) SetFrom6To8sNum(v int32) {
	o.From6To8sNum = &v
}

// GetFrom8To10sNum returns the From8To10sNum field value if set, zero value otherwise.
func (o *ClientsWithOnBoardingTimes) GetFrom8To10sNum() int32 {
	if o == nil || IsNil(o.From8To10sNum) {
		var ret int32
		return ret
	}
	return *o.From8To10sNum
}

// GetFrom8To10sNumOk returns a tuple with the From8To10sNum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientsWithOnBoardingTimes) GetFrom8To10sNumOk() (*int32, bool) {
	if o == nil || IsNil(o.From8To10sNum) {
		return nil, false
	}
	return o.From8To10sNum, true
}

// HasFrom8To10sNum returns a boolean if a field has been set.
func (o *ClientsWithOnBoardingTimes) HasFrom8To10sNum() bool {
	if o != nil && !IsNil(o.From8To10sNum) {
		return true
	}

	return false
}

// SetFrom8To10sNum gets a reference to the given int32 and assigns it to the From8To10sNum field.
func (o *ClientsWithOnBoardingTimes) SetFrom8To10sNum(v int32) {
	o.From8To10sNum = &v
}

// GetLessThan10sPercent returns the LessThan10sPercent field value if set, zero value otherwise.
func (o *ClientsWithOnBoardingTimes) GetLessThan10sPercent() int32 {
	if o == nil || IsNil(o.LessThan10sPercent) {
		var ret int32
		return ret
	}
	return *o.LessThan10sPercent
}

// GetLessThan10sPercentOk returns a tuple with the LessThan10sPercent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientsWithOnBoardingTimes) GetLessThan10sPercentOk() (*int32, bool) {
	if o == nil || IsNil(o.LessThan10sPercent) {
		return nil, false
	}
	return o.LessThan10sPercent, true
}

// HasLessThan10sPercent returns a boolean if a field has been set.
func (o *ClientsWithOnBoardingTimes) HasLessThan10sPercent() bool {
	if o != nil && !IsNil(o.LessThan10sPercent) {
		return true
	}

	return false
}

// SetLessThan10sPercent gets a reference to the given int32 and assigns it to the LessThan10sPercent field.
func (o *ClientsWithOnBoardingTimes) SetLessThan10sPercent(v int32) {
	o.LessThan10sPercent = &v
}

// GetLessThan2sNum returns the LessThan2sNum field value if set, zero value otherwise.
func (o *ClientsWithOnBoardingTimes) GetLessThan2sNum() int32 {
	if o == nil || IsNil(o.LessThan2sNum) {
		var ret int32
		return ret
	}
	return *o.LessThan2sNum
}

// GetLessThan2sNumOk returns a tuple with the LessThan2sNum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientsWithOnBoardingTimes) GetLessThan2sNumOk() (*int32, bool) {
	if o == nil || IsNil(o.LessThan2sNum) {
		return nil, false
	}
	return o.LessThan2sNum, true
}

// HasLessThan2sNum returns a boolean if a field has been set.
func (o *ClientsWithOnBoardingTimes) HasLessThan2sNum() bool {
	if o != nil && !IsNil(o.LessThan2sNum) {
		return true
	}

	return false
}

// SetLessThan2sNum gets a reference to the given int32 and assigns it to the LessThan2sNum field.
func (o *ClientsWithOnBoardingTimes) SetLessThan2sNum(v int32) {
	o.LessThan2sNum = &v
}

// GetMoreThan10sNum returns the MoreThan10sNum field value if set, zero value otherwise.
func (o *ClientsWithOnBoardingTimes) GetMoreThan10sNum() int32 {
	if o == nil || IsNil(o.MoreThan10sNum) {
		var ret int32
		return ret
	}
	return *o.MoreThan10sNum
}

// GetMoreThan10sNumOk returns a tuple with the MoreThan10sNum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientsWithOnBoardingTimes) GetMoreThan10sNumOk() (*int32, bool) {
	if o == nil || IsNil(o.MoreThan10sNum) {
		return nil, false
	}
	return o.MoreThan10sNum, true
}

// HasMoreThan10sNum returns a boolean if a field has been set.
func (o *ClientsWithOnBoardingTimes) HasMoreThan10sNum() bool {
	if o != nil && !IsNil(o.MoreThan10sNum) {
		return true
	}

	return false
}

// SetMoreThan10sNum gets a reference to the given int32 and assigns it to the MoreThan10sNum field.
func (o *ClientsWithOnBoardingTimes) SetMoreThan10sNum(v int32) {
	o.MoreThan10sNum = &v
}

func (o ClientsWithOnBoardingTimes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientsWithOnBoardingTimes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Fails) {
		toSerialize["fails"] = o.Fails
	}
	if !IsNil(o.From2To4sNum) {
		toSerialize["from2To4sNum"] = o.From2To4sNum
	}
	if !IsNil(o.From4To6sNum) {
		toSerialize["from4To6sNum"] = o.From4To6sNum
	}
	if !IsNil(o.From6To8sNum) {
		toSerialize["from6To8sNum"] = o.From6To8sNum
	}
	if !IsNil(o.From8To10sNum) {
		toSerialize["from8To10sNum"] = o.From8To10sNum
	}
	if !IsNil(o.LessThan10sPercent) {
		toSerialize["lessThan10sPercent"] = o.LessThan10sPercent
	}
	if !IsNil(o.LessThan2sNum) {
		toSerialize["lessThan2sNum"] = o.LessThan2sNum
	}
	if !IsNil(o.MoreThan10sNum) {
		toSerialize["moreThan10sNum"] = o.MoreThan10sNum
	}
	return toSerialize, nil
}

type NullableClientsWithOnBoardingTimes struct {
	value *ClientsWithOnBoardingTimes
	isSet bool
}

func (v NullableClientsWithOnBoardingTimes) Get() *ClientsWithOnBoardingTimes {
	return v.value
}

func (v *NullableClientsWithOnBoardingTimes) Set(val *ClientsWithOnBoardingTimes) {
	v.value = val
	v.isSet = true
}

func (v NullableClientsWithOnBoardingTimes) IsSet() bool {
	return v.isSet
}

func (v *NullableClientsWithOnBoardingTimes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientsWithOnBoardingTimes(val *ClientsWithOnBoardingTimes) *NullableClientsWithOnBoardingTimes {
	return &NullableClientsWithOnBoardingTimes{value: val, isSet: true}
}

func (v NullableClientsWithOnBoardingTimes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientsWithOnBoardingTimes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


