/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
)

// checks if the ClientFilteringOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientFilteringOptions{}

// ClientFilteringOptions struct for ClientFilteringOptions
type ClientFilteringOptions struct {
	// Device list.
	Device []string `json:"device,omitempty"`
	// Type list of clients.
	DeviceType []ClientCategoryOptionsOpenApiVO `json:"deviceType,omitempty"`
	// Network list.
	Network []string `json:"network,omitempty"`
	// Ssid list.
	Ssid []string `json:"ssid,omitempty"`
	// Vendor list of clients.
	Vendor []string `json:"vendor,omitempty"`
}

// NewClientFilteringOptions instantiates a new ClientFilteringOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientFilteringOptions() *ClientFilteringOptions {
	this := ClientFilteringOptions{}
	return &this
}

// NewClientFilteringOptionsWithDefaults instantiates a new ClientFilteringOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientFilteringOptionsWithDefaults() *ClientFilteringOptions {
	this := ClientFilteringOptions{}
	return &this
}

// GetDevice returns the Device field value if set, zero value otherwise.
func (o *ClientFilteringOptions) GetDevice() []string {
	if o == nil || IsNil(o.Device) {
		var ret []string
		return ret
	}
	return o.Device
}

// GetDeviceOk returns a tuple with the Device field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientFilteringOptions) GetDeviceOk() ([]string, bool) {
	if o == nil || IsNil(o.Device) {
		return nil, false
	}
	return o.Device, true
}

// HasDevice returns a boolean if a field has been set.
func (o *ClientFilteringOptions) HasDevice() bool {
	if o != nil && !IsNil(o.Device) {
		return true
	}

	return false
}

// SetDevice gets a reference to the given []string and assigns it to the Device field.
func (o *ClientFilteringOptions) SetDevice(v []string) {
	o.Device = v
}

// GetDeviceType returns the DeviceType field value if set, zero value otherwise.
func (o *ClientFilteringOptions) GetDeviceType() []ClientCategoryOptionsOpenApiVO {
	if o == nil || IsNil(o.DeviceType) {
		var ret []ClientCategoryOptionsOpenApiVO
		return ret
	}
	return o.DeviceType
}

// GetDeviceTypeOk returns a tuple with the DeviceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientFilteringOptions) GetDeviceTypeOk() ([]ClientCategoryOptionsOpenApiVO, bool) {
	if o == nil || IsNil(o.DeviceType) {
		return nil, false
	}
	return o.DeviceType, true
}

// HasDeviceType returns a boolean if a field has been set.
func (o *ClientFilteringOptions) HasDeviceType() bool {
	if o != nil && !IsNil(o.DeviceType) {
		return true
	}

	return false
}

// SetDeviceType gets a reference to the given []ClientCategoryOptionsOpenApiVO and assigns it to the DeviceType field.
func (o *ClientFilteringOptions) SetDeviceType(v []ClientCategoryOptionsOpenApiVO) {
	o.DeviceType = v
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *ClientFilteringOptions) GetNetwork() []string {
	if o == nil || IsNil(o.Network) {
		var ret []string
		return ret
	}
	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientFilteringOptions) GetNetworkOk() ([]string, bool) {
	if o == nil || IsNil(o.Network) {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *ClientFilteringOptions) HasNetwork() bool {
	if o != nil && !IsNil(o.Network) {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given []string and assigns it to the Network field.
func (o *ClientFilteringOptions) SetNetwork(v []string) {
	o.Network = v
}

// GetSsid returns the Ssid field value if set, zero value otherwise.
func (o *ClientFilteringOptions) GetSsid() []string {
	if o == nil || IsNil(o.Ssid) {
		var ret []string
		return ret
	}
	return o.Ssid
}

// GetSsidOk returns a tuple with the Ssid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientFilteringOptions) GetSsidOk() ([]string, bool) {
	if o == nil || IsNil(o.Ssid) {
		return nil, false
	}
	return o.Ssid, true
}

// HasSsid returns a boolean if a field has been set.
func (o *ClientFilteringOptions) HasSsid() bool {
	if o != nil && !IsNil(o.Ssid) {
		return true
	}

	return false
}

// SetSsid gets a reference to the given []string and assigns it to the Ssid field.
func (o *ClientFilteringOptions) SetSsid(v []string) {
	o.Ssid = v
}

// GetVendor returns the Vendor field value if set, zero value otherwise.
func (o *ClientFilteringOptions) GetVendor() []string {
	if o == nil || IsNil(o.Vendor) {
		var ret []string
		return ret
	}
	return o.Vendor
}

// GetVendorOk returns a tuple with the Vendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientFilteringOptions) GetVendorOk() ([]string, bool) {
	if o == nil || IsNil(o.Vendor) {
		return nil, false
	}
	return o.Vendor, true
}

// HasVendor returns a boolean if a field has been set.
func (o *ClientFilteringOptions) HasVendor() bool {
	if o != nil && !IsNil(o.Vendor) {
		return true
	}

	return false
}

// SetVendor gets a reference to the given []string and assigns it to the Vendor field.
func (o *ClientFilteringOptions) SetVendor(v []string) {
	o.Vendor = v
}

func (o ClientFilteringOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientFilteringOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Device) {
		toSerialize["device"] = o.Device
	}
	if !IsNil(o.DeviceType) {
		toSerialize["deviceType"] = o.DeviceType
	}
	if !IsNil(o.Network) {
		toSerialize["network"] = o.Network
	}
	if !IsNil(o.Ssid) {
		toSerialize["ssid"] = o.Ssid
	}
	if !IsNil(o.Vendor) {
		toSerialize["vendor"] = o.Vendor
	}
	return toSerialize, nil
}

type NullableClientFilteringOptions struct {
	value *ClientFilteringOptions
	isSet bool
}

func (v NullableClientFilteringOptions) Get() *ClientFilteringOptions {
	return v.value
}

func (v *NullableClientFilteringOptions) Set(val *ClientFilteringOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableClientFilteringOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableClientFilteringOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientFilteringOptions(val *ClientFilteringOptions) *NullableClientFilteringOptions {
	return &NullableClientFilteringOptions{value: val, isSet: true}
}

func (v NullableClientFilteringOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientFilteringOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


