/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
)

// checks if the GatewayIspLoadInfoVO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayIspLoadInfoVO{}

// GatewayIspLoadInfoVO Gateway isp info list.
type GatewayIspLoadInfoVO struct {
	IspInfo *IspInfoVO `json:"ispInfo,omitempty"`
	// Gateway MAC.
	Mac *string `json:"mac,omitempty"`
	// Gateway name.
	Name *string `json:"name,omitempty"`
	// Gateway status, should be a value as follows:-1 : disconnected1 : active0 : backup gateway under multiple gateways
	Status *int32 `json:"status,omitempty"`
}

// NewGatewayIspLoadInfoVO instantiates a new GatewayIspLoadInfoVO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayIspLoadInfoVO() *GatewayIspLoadInfoVO {
	this := GatewayIspLoadInfoVO{}
	return &this
}

// NewGatewayIspLoadInfoVOWithDefaults instantiates a new GatewayIspLoadInfoVO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayIspLoadInfoVOWithDefaults() *GatewayIspLoadInfoVO {
	this := GatewayIspLoadInfoVO{}
	return &this
}

// GetIspInfo returns the IspInfo field value if set, zero value otherwise.
func (o *GatewayIspLoadInfoVO) GetIspInfo() IspInfoVO {
	if o == nil || IsNil(o.IspInfo) {
		var ret IspInfoVO
		return ret
	}
	return *o.IspInfo
}

// GetIspInfoOk returns a tuple with the IspInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayIspLoadInfoVO) GetIspInfoOk() (*IspInfoVO, bool) {
	if o == nil || IsNil(o.IspInfo) {
		return nil, false
	}
	return o.IspInfo, true
}

// HasIspInfo returns a boolean if a field has been set.
func (o *GatewayIspLoadInfoVO) HasIspInfo() bool {
	if o != nil && !IsNil(o.IspInfo) {
		return true
	}

	return false
}

// SetIspInfo gets a reference to the given IspInfoVO and assigns it to the IspInfo field.
func (o *GatewayIspLoadInfoVO) SetIspInfo(v IspInfoVO) {
	o.IspInfo = &v
}

// GetMac returns the Mac field value if set, zero value otherwise.
func (o *GatewayIspLoadInfoVO) GetMac() string {
	if o == nil || IsNil(o.Mac) {
		var ret string
		return ret
	}
	return *o.Mac
}

// GetMacOk returns a tuple with the Mac field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayIspLoadInfoVO) GetMacOk() (*string, bool) {
	if o == nil || IsNil(o.Mac) {
		return nil, false
	}
	return o.Mac, true
}

// HasMac returns a boolean if a field has been set.
func (o *GatewayIspLoadInfoVO) HasMac() bool {
	if o != nil && !IsNil(o.Mac) {
		return true
	}

	return false
}

// SetMac gets a reference to the given string and assigns it to the Mac field.
func (o *GatewayIspLoadInfoVO) SetMac(v string) {
	o.Mac = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GatewayIspLoadInfoVO) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayIspLoadInfoVO) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GatewayIspLoadInfoVO) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GatewayIspLoadInfoVO) SetName(v string) {
	o.Name = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GatewayIspLoadInfoVO) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayIspLoadInfoVO) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GatewayIspLoadInfoVO) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *GatewayIspLoadInfoVO) SetStatus(v int32) {
	o.Status = &v
}

func (o GatewayIspLoadInfoVO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayIspLoadInfoVO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IspInfo) {
		toSerialize["ispInfo"] = o.IspInfo
	}
	if !IsNil(o.Mac) {
		toSerialize["mac"] = o.Mac
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableGatewayIspLoadInfoVO struct {
	value *GatewayIspLoadInfoVO
	isSet bool
}

func (v NullableGatewayIspLoadInfoVO) Get() *GatewayIspLoadInfoVO {
	return v.value
}

func (v *NullableGatewayIspLoadInfoVO) Set(val *GatewayIspLoadInfoVO) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayIspLoadInfoVO) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayIspLoadInfoVO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayIspLoadInfoVO(val *GatewayIspLoadInfoVO) *NullableGatewayIspLoadInfoVO {
	return &NullableGatewayIspLoadInfoVO{value: val, isSet: true}
}

func (v NullableGatewayIspLoadInfoVO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayIspLoadInfoVO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


