/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
)

// checks if the OswMlagCccVO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OswMlagCccVO{}

// OswMlagCccVO struct for OswMlagCccVO
type OswMlagCccVO struct {
	// M-LAG group member mac
	Mac *string `json:"mac,omitempty"`
	// M-LAG group members configuration check result
	MlagCccResult []MlagCccResultVO `json:"mlagCccResult,omitempty"`
}

// NewOswMlagCccVO instantiates a new OswMlagCccVO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOswMlagCccVO() *OswMlagCccVO {
	this := OswMlagCccVO{}
	return &this
}

// NewOswMlagCccVOWithDefaults instantiates a new OswMlagCccVO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOswMlagCccVOWithDefaults() *OswMlagCccVO {
	this := OswMlagCccVO{}
	return &this
}

// GetMac returns the Mac field value if set, zero value otherwise.
func (o *OswMlagCccVO) GetMac() string {
	if o == nil || IsNil(o.Mac) {
		var ret string
		return ret
	}
	return *o.Mac
}

// GetMacOk returns a tuple with the Mac field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OswMlagCccVO) GetMacOk() (*string, bool) {
	if o == nil || IsNil(o.Mac) {
		return nil, false
	}
	return o.Mac, true
}

// HasMac returns a boolean if a field has been set.
func (o *OswMlagCccVO) HasMac() bool {
	if o != nil && !IsNil(o.Mac) {
		return true
	}

	return false
}

// SetMac gets a reference to the given string and assigns it to the Mac field.
func (o *OswMlagCccVO) SetMac(v string) {
	o.Mac = &v
}

// GetMlagCccResult returns the MlagCccResult field value if set, zero value otherwise.
func (o *OswMlagCccVO) GetMlagCccResult() []MlagCccResultVO {
	if o == nil || IsNil(o.MlagCccResult) {
		var ret []MlagCccResultVO
		return ret
	}
	return o.MlagCccResult
}

// GetMlagCccResultOk returns a tuple with the MlagCccResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OswMlagCccVO) GetMlagCccResultOk() ([]MlagCccResultVO, bool) {
	if o == nil || IsNil(o.MlagCccResult) {
		return nil, false
	}
	return o.MlagCccResult, true
}

// HasMlagCccResult returns a boolean if a field has been set.
func (o *OswMlagCccVO) HasMlagCccResult() bool {
	if o != nil && !IsNil(o.MlagCccResult) {
		return true
	}

	return false
}

// SetMlagCccResult gets a reference to the given []MlagCccResultVO and assigns it to the MlagCccResult field.
func (o *OswMlagCccVO) SetMlagCccResult(v []MlagCccResultVO) {
	o.MlagCccResult = v
}

func (o OswMlagCccVO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OswMlagCccVO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Mac) {
		toSerialize["mac"] = o.Mac
	}
	if !IsNil(o.MlagCccResult) {
		toSerialize["mlagCccResult"] = o.MlagCccResult
	}
	return toSerialize, nil
}

type NullableOswMlagCccVO struct {
	value *OswMlagCccVO
	isSet bool
}

func (v NullableOswMlagCccVO) Get() *OswMlagCccVO {
	return v.value
}

func (v *NullableOswMlagCccVO) Set(val *OswMlagCccVO) {
	v.value = val
	v.isSet = true
}

func (v NullableOswMlagCccVO) IsSet() bool {
	return v.isSet
}

func (v *NullableOswMlagCccVO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOswMlagCccVO(val *OswMlagCccVO) *NullableOswMlagCccVO {
	return &NullableOswMlagCccVO{value: val, isSet: true}
}

func (v NullableOswMlagCccVO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOswMlagCccVO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


