/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
)

// checks if the ApChannel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApChannel{}

// ApChannel List of 6G channel loads.
type ApChannel struct {
	// Channel.
	Channel *int32 `json:"channel,omitempty"`
	// The channel load corresponding to the channel.
	Load *int32 `json:"load,omitempty"`
}

// NewApChannel instantiates a new ApChannel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApChannel() *ApChannel {
	this := ApChannel{}
	return &this
}

// NewApChannelWithDefaults instantiates a new ApChannel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApChannelWithDefaults() *ApChannel {
	this := ApChannel{}
	return &this
}

// GetChannel returns the Channel field value if set, zero value otherwise.
func (o *ApChannel) GetChannel() int32 {
	if o == nil || IsNil(o.Channel) {
		var ret int32
		return ret
	}
	return *o.Channel
}

// GetChannelOk returns a tuple with the Channel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApChannel) GetChannelOk() (*int32, bool) {
	if o == nil || IsNil(o.Channel) {
		return nil, false
	}
	return o.Channel, true
}

// HasChannel returns a boolean if a field has been set.
func (o *ApChannel) HasChannel() bool {
	if o != nil && !IsNil(o.Channel) {
		return true
	}

	return false
}

// SetChannel gets a reference to the given int32 and assigns it to the Channel field.
func (o *ApChannel) SetChannel(v int32) {
	o.Channel = &v
}

// GetLoad returns the Load field value if set, zero value otherwise.
func (o *ApChannel) GetLoad() int32 {
	if o == nil || IsNil(o.Load) {
		var ret int32
		return ret
	}
	return *o.Load
}

// GetLoadOk returns a tuple with the Load field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApChannel) GetLoadOk() (*int32, bool) {
	if o == nil || IsNil(o.Load) {
		return nil, false
	}
	return o.Load, true
}

// HasLoad returns a boolean if a field has been set.
func (o *ApChannel) HasLoad() bool {
	if o != nil && !IsNil(o.Load) {
		return true
	}

	return false
}

// SetLoad gets a reference to the given int32 and assigns it to the Load field.
func (o *ApChannel) SetLoad(v int32) {
	o.Load = &v
}

func (o ApChannel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApChannel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Channel) {
		toSerialize["channel"] = o.Channel
	}
	if !IsNil(o.Load) {
		toSerialize["load"] = o.Load
	}
	return toSerialize, nil
}

type NullableApChannel struct {
	value *ApChannel
	isSet bool
}

func (v NullableApChannel) Get() *ApChannel {
	return v.value
}

func (v *NullableApChannel) Set(val *ApChannel) {
	v.value = val
	v.isSet = true
}

func (v NullableApChannel) IsSet() bool {
	return v.isSet
}

func (v *NullableApChannel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApChannel(val *ApChannel) *NullableApChannel {
	return &NullableApChannel{value: val, isSet: true}
}

func (v NullableApChannel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApChannel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


