/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
)

// checks if the ApSnmpConfigOpenApiVO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApSnmpConfigOpenApiVO{}

// ApSnmpConfigOpenApiVO struct for ApSnmpConfigOpenApiVO
type ApSnmpConfigOpenApiVO struct {
	// Contact, contact should contain 0 to 128 ASCII characters, spaces are not allowed.
	Contact *string `json:"contact,omitempty"`
	// Location, location should contain 0 to 128 ASCII characters, spaces are allowed, and leading and trailing spaces are not allowed.
	Location *string `json:"location,omitempty"`
}

// NewApSnmpConfigOpenApiVO instantiates a new ApSnmpConfigOpenApiVO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApSnmpConfigOpenApiVO() *ApSnmpConfigOpenApiVO {
	this := ApSnmpConfigOpenApiVO{}
	return &this
}

// NewApSnmpConfigOpenApiVOWithDefaults instantiates a new ApSnmpConfigOpenApiVO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApSnmpConfigOpenApiVOWithDefaults() *ApSnmpConfigOpenApiVO {
	this := ApSnmpConfigOpenApiVO{}
	return &this
}

// GetContact returns the Contact field value if set, zero value otherwise.
func (o *ApSnmpConfigOpenApiVO) GetContact() string {
	if o == nil || IsNil(o.Contact) {
		var ret string
		return ret
	}
	return *o.Contact
}

// GetContactOk returns a tuple with the Contact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApSnmpConfigOpenApiVO) GetContactOk() (*string, bool) {
	if o == nil || IsNil(o.Contact) {
		return nil, false
	}
	return o.Contact, true
}

// HasContact returns a boolean if a field has been set.
func (o *ApSnmpConfigOpenApiVO) HasContact() bool {
	if o != nil && !IsNil(o.Contact) {
		return true
	}

	return false
}

// SetContact gets a reference to the given string and assigns it to the Contact field.
func (o *ApSnmpConfigOpenApiVO) SetContact(v string) {
	o.Contact = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *ApSnmpConfigOpenApiVO) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApSnmpConfigOpenApiVO) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *ApSnmpConfigOpenApiVO) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *ApSnmpConfigOpenApiVO) SetLocation(v string) {
	o.Location = &v
}

func (o ApSnmpConfigOpenApiVO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApSnmpConfigOpenApiVO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Contact) {
		toSerialize["contact"] = o.Contact
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	return toSerialize, nil
}

type NullableApSnmpConfigOpenApiVO struct {
	value *ApSnmpConfigOpenApiVO
	isSet bool
}

func (v NullableApSnmpConfigOpenApiVO) Get() *ApSnmpConfigOpenApiVO {
	return v.value
}

func (v *NullableApSnmpConfigOpenApiVO) Set(val *ApSnmpConfigOpenApiVO) {
	v.value = val
	v.isSet = true
}

func (v NullableApSnmpConfigOpenApiVO) IsSet() bool {
	return v.isSet
}

func (v *NullableApSnmpConfigOpenApiVO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApSnmpConfigOpenApiVO(val *ApSnmpConfigOpenApiVO) *NullableApSnmpConfigOpenApiVO {
	return &NullableApSnmpConfigOpenApiVO{value: val, isSet: true}
}

func (v NullableApSnmpConfigOpenApiVO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApSnmpConfigOpenApiVO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


