/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
)

// checks if the OperationResponseBuiltInRadiusServerSetting type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperationResponseBuiltInRadiusServerSetting{}

// OperationResponseBuiltInRadiusServerSetting struct for OperationResponseBuiltInRadiusServerSetting
type OperationResponseBuiltInRadiusServerSetting struct {
	ErrorCode *int32 `json:"errorCode,omitempty"`
	Msg *string `json:"msg,omitempty"`
	Result *BuiltInRadiusServerSetting `json:"result,omitempty"`
}

// NewOperationResponseBuiltInRadiusServerSetting instantiates a new OperationResponseBuiltInRadiusServerSetting object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperationResponseBuiltInRadiusServerSetting() *OperationResponseBuiltInRadiusServerSetting {
	this := OperationResponseBuiltInRadiusServerSetting{}
	return &this
}

// NewOperationResponseBuiltInRadiusServerSettingWithDefaults instantiates a new OperationResponseBuiltInRadiusServerSetting object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperationResponseBuiltInRadiusServerSettingWithDefaults() *OperationResponseBuiltInRadiusServerSetting {
	this := OperationResponseBuiltInRadiusServerSetting{}
	return &this
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise.
func (o *OperationResponseBuiltInRadiusServerSetting) GetErrorCode() int32 {
	if o == nil || IsNil(o.ErrorCode) {
		var ret int32
		return ret
	}
	return *o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperationResponseBuiltInRadiusServerSetting) GetErrorCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.ErrorCode) {
		return nil, false
	}
	return o.ErrorCode, true
}

// HasErrorCode returns a boolean if a field has been set.
func (o *OperationResponseBuiltInRadiusServerSetting) HasErrorCode() bool {
	if o != nil && !IsNil(o.ErrorCode) {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given int32 and assigns it to the ErrorCode field.
func (o *OperationResponseBuiltInRadiusServerSetting) SetErrorCode(v int32) {
	o.ErrorCode = &v
}

// GetMsg returns the Msg field value if set, zero value otherwise.
func (o *OperationResponseBuiltInRadiusServerSetting) GetMsg() string {
	if o == nil || IsNil(o.Msg) {
		var ret string
		return ret
	}
	return *o.Msg
}

// GetMsgOk returns a tuple with the Msg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperationResponseBuiltInRadiusServerSetting) GetMsgOk() (*string, bool) {
	if o == nil || IsNil(o.Msg) {
		return nil, false
	}
	return o.Msg, true
}

// HasMsg returns a boolean if a field has been set.
func (o *OperationResponseBuiltInRadiusServerSetting) HasMsg() bool {
	if o != nil && !IsNil(o.Msg) {
		return true
	}

	return false
}

// SetMsg gets a reference to the given string and assigns it to the Msg field.
func (o *OperationResponseBuiltInRadiusServerSetting) SetMsg(v string) {
	o.Msg = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *OperationResponseBuiltInRadiusServerSetting) GetResult() BuiltInRadiusServerSetting {
	if o == nil || IsNil(o.Result) {
		var ret BuiltInRadiusServerSetting
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperationResponseBuiltInRadiusServerSetting) GetResultOk() (*BuiltInRadiusServerSetting, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *OperationResponseBuiltInRadiusServerSetting) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given BuiltInRadiusServerSetting and assigns it to the Result field.
func (o *OperationResponseBuiltInRadiusServerSetting) SetResult(v BuiltInRadiusServerSetting) {
	o.Result = &v
}

func (o OperationResponseBuiltInRadiusServerSetting) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperationResponseBuiltInRadiusServerSetting) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ErrorCode) {
		toSerialize["errorCode"] = o.ErrorCode
	}
	if !IsNil(o.Msg) {
		toSerialize["msg"] = o.Msg
	}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullableOperationResponseBuiltInRadiusServerSetting struct {
	value *OperationResponseBuiltInRadiusServerSetting
	isSet bool
}

func (v NullableOperationResponseBuiltInRadiusServerSetting) Get() *OperationResponseBuiltInRadiusServerSetting {
	return v.value
}

func (v *NullableOperationResponseBuiltInRadiusServerSetting) Set(val *OperationResponseBuiltInRadiusServerSetting) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationResponseBuiltInRadiusServerSetting) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationResponseBuiltInRadiusServerSetting) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationResponseBuiltInRadiusServerSetting(val *OperationResponseBuiltInRadiusServerSetting) *NullableOperationResponseBuiltInRadiusServerSetting {
	return &NullableOperationResponseBuiltInRadiusServerSetting{value: val, isSet: true}
}

func (v NullableOperationResponseBuiltInRadiusServerSetting) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationResponseBuiltInRadiusServerSetting) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


