/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
)

// checks if the OperationResponseGridVOSdWanGroupBrief type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperationResponseGridVOSdWanGroupBrief{}

// OperationResponseGridVOSdWanGroupBrief struct for OperationResponseGridVOSdWanGroupBrief
type OperationResponseGridVOSdWanGroupBrief struct {
	ErrorCode *int32 `json:"errorCode,omitempty"`
	Msg *string `json:"msg,omitempty"`
	Result *GridVOSdWanGroupBrief `json:"result,omitempty"`
}

// NewOperationResponseGridVOSdWanGroupBrief instantiates a new OperationResponseGridVOSdWanGroupBrief object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperationResponseGridVOSdWanGroupBrief() *OperationResponseGridVOSdWanGroupBrief {
	this := OperationResponseGridVOSdWanGroupBrief{}
	return &this
}

// NewOperationResponseGridVOSdWanGroupBriefWithDefaults instantiates a new OperationResponseGridVOSdWanGroupBrief object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperationResponseGridVOSdWanGroupBriefWithDefaults() *OperationResponseGridVOSdWanGroupBrief {
	this := OperationResponseGridVOSdWanGroupBrief{}
	return &this
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise.
func (o *OperationResponseGridVOSdWanGroupBrief) GetErrorCode() int32 {
	if o == nil || IsNil(o.ErrorCode) {
		var ret int32
		return ret
	}
	return *o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperationResponseGridVOSdWanGroupBrief) GetErrorCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.ErrorCode) {
		return nil, false
	}
	return o.ErrorCode, true
}

// HasErrorCode returns a boolean if a field has been set.
func (o *OperationResponseGridVOSdWanGroupBrief) HasErrorCode() bool {
	if o != nil && !IsNil(o.ErrorCode) {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given int32 and assigns it to the ErrorCode field.
func (o *OperationResponseGridVOSdWanGroupBrief) SetErrorCode(v int32) {
	o.ErrorCode = &v
}

// GetMsg returns the Msg field value if set, zero value otherwise.
func (o *OperationResponseGridVOSdWanGroupBrief) GetMsg() string {
	if o == nil || IsNil(o.Msg) {
		var ret string
		return ret
	}
	return *o.Msg
}

// GetMsgOk returns a tuple with the Msg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperationResponseGridVOSdWanGroupBrief) GetMsgOk() (*string, bool) {
	if o == nil || IsNil(o.Msg) {
		return nil, false
	}
	return o.Msg, true
}

// HasMsg returns a boolean if a field has been set.
func (o *OperationResponseGridVOSdWanGroupBrief) HasMsg() bool {
	if o != nil && !IsNil(o.Msg) {
		return true
	}

	return false
}

// SetMsg gets a reference to the given string and assigns it to the Msg field.
func (o *OperationResponseGridVOSdWanGroupBrief) SetMsg(v string) {
	o.Msg = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *OperationResponseGridVOSdWanGroupBrief) GetResult() GridVOSdWanGroupBrief {
	if o == nil || IsNil(o.Result) {
		var ret GridVOSdWanGroupBrief
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperationResponseGridVOSdWanGroupBrief) GetResultOk() (*GridVOSdWanGroupBrief, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *OperationResponseGridVOSdWanGroupBrief) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given GridVOSdWanGroupBrief and assigns it to the Result field.
func (o *OperationResponseGridVOSdWanGroupBrief) SetResult(v GridVOSdWanGroupBrief) {
	o.Result = &v
}

func (o OperationResponseGridVOSdWanGroupBrief) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperationResponseGridVOSdWanGroupBrief) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ErrorCode) {
		toSerialize["errorCode"] = o.ErrorCode
	}
	if !IsNil(o.Msg) {
		toSerialize["msg"] = o.Msg
	}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullableOperationResponseGridVOSdWanGroupBrief struct {
	value *OperationResponseGridVOSdWanGroupBrief
	isSet bool
}

func (v NullableOperationResponseGridVOSdWanGroupBrief) Get() *OperationResponseGridVOSdWanGroupBrief {
	return v.value
}

func (v *NullableOperationResponseGridVOSdWanGroupBrief) Set(val *OperationResponseGridVOSdWanGroupBrief) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationResponseGridVOSdWanGroupBrief) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationResponseGridVOSdWanGroupBrief) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationResponseGridVOSdWanGroupBrief(val *OperationResponseGridVOSdWanGroupBrief) *NullableOperationResponseGridVOSdWanGroupBrief {
	return &NullableOperationResponseGridVOSdWanGroupBrief{value: val, isSet: true}
}

func (v NullableOperationResponseGridVOSdWanGroupBrief) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationResponseGridVOSdWanGroupBrief) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


