/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
)

// checks if the CurrencyCandidatesOpenApiVO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CurrencyCandidatesOpenApiVO{}

// CurrencyCandidatesOpenApiVO struct for CurrencyCandidatesOpenApiVO
type CurrencyCandidatesOpenApiVO struct {
	// All currency Short Code list. For the values of Currency Short Code, refer to section 5.4.2 of the Open API Access Guide.
	CurrencyList []string `json:"currencyList,omitempty"`
	// The currency selected for the site
	SelectedCurrency *string `json:"selectedCurrency,omitempty"`
}

// NewCurrencyCandidatesOpenApiVO instantiates a new CurrencyCandidatesOpenApiVO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCurrencyCandidatesOpenApiVO() *CurrencyCandidatesOpenApiVO {
	this := CurrencyCandidatesOpenApiVO{}
	return &this
}

// NewCurrencyCandidatesOpenApiVOWithDefaults instantiates a new CurrencyCandidatesOpenApiVO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCurrencyCandidatesOpenApiVOWithDefaults() *CurrencyCandidatesOpenApiVO {
	this := CurrencyCandidatesOpenApiVO{}
	return &this
}

// GetCurrencyList returns the CurrencyList field value if set, zero value otherwise.
func (o *CurrencyCandidatesOpenApiVO) GetCurrencyList() []string {
	if o == nil || IsNil(o.CurrencyList) {
		var ret []string
		return ret
	}
	return o.CurrencyList
}

// GetCurrencyListOk returns a tuple with the CurrencyList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CurrencyCandidatesOpenApiVO) GetCurrencyListOk() ([]string, bool) {
	if o == nil || IsNil(o.CurrencyList) {
		return nil, false
	}
	return o.CurrencyList, true
}

// HasCurrencyList returns a boolean if a field has been set.
func (o *CurrencyCandidatesOpenApiVO) HasCurrencyList() bool {
	if o != nil && !IsNil(o.CurrencyList) {
		return true
	}

	return false
}

// SetCurrencyList gets a reference to the given []string and assigns it to the CurrencyList field.
func (o *CurrencyCandidatesOpenApiVO) SetCurrencyList(v []string) {
	o.CurrencyList = v
}

// GetSelectedCurrency returns the SelectedCurrency field value if set, zero value otherwise.
func (o *CurrencyCandidatesOpenApiVO) GetSelectedCurrency() string {
	if o == nil || IsNil(o.SelectedCurrency) {
		var ret string
		return ret
	}
	return *o.SelectedCurrency
}

// GetSelectedCurrencyOk returns a tuple with the SelectedCurrency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CurrencyCandidatesOpenApiVO) GetSelectedCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.SelectedCurrency) {
		return nil, false
	}
	return o.SelectedCurrency, true
}

// HasSelectedCurrency returns a boolean if a field has been set.
func (o *CurrencyCandidatesOpenApiVO) HasSelectedCurrency() bool {
	if o != nil && !IsNil(o.SelectedCurrency) {
		return true
	}

	return false
}

// SetSelectedCurrency gets a reference to the given string and assigns it to the SelectedCurrency field.
func (o *CurrencyCandidatesOpenApiVO) SetSelectedCurrency(v string) {
	o.SelectedCurrency = &v
}

func (o CurrencyCandidatesOpenApiVO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CurrencyCandidatesOpenApiVO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CurrencyList) {
		toSerialize["currencyList"] = o.CurrencyList
	}
	if !IsNil(o.SelectedCurrency) {
		toSerialize["selectedCurrency"] = o.SelectedCurrency
	}
	return toSerialize, nil
}

type NullableCurrencyCandidatesOpenApiVO struct {
	value *CurrencyCandidatesOpenApiVO
	isSet bool
}

func (v NullableCurrencyCandidatesOpenApiVO) Get() *CurrencyCandidatesOpenApiVO {
	return v.value
}

func (v *NullableCurrencyCandidatesOpenApiVO) Set(val *CurrencyCandidatesOpenApiVO) {
	v.value = val
	v.isSet = true
}

func (v NullableCurrencyCandidatesOpenApiVO) IsSet() bool {
	return v.isSet
}

func (v *NullableCurrencyCandidatesOpenApiVO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCurrencyCandidatesOpenApiVO(val *CurrencyCandidatesOpenApiVO) *NullableCurrencyCandidatesOpenApiVO {
	return &NullableCurrencyCandidatesOpenApiVO{value: val, isSet: true}
}

func (v NullableCurrencyCandidatesOpenApiVO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCurrencyCandidatesOpenApiVO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


