/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
	"os"
)

// checks if the UploadUpgradeFirmwareRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadUpgradeFirmwareRequest{}

// UploadUpgradeFirmwareRequest struct for UploadUpgradeFirmwareRequest
type UploadUpgradeFirmwareRequest struct {
	// Firmware file.
	File **os.File `json:"file,omitempty"`
}

// NewUploadUpgradeFirmwareRequest instantiates a new UploadUpgradeFirmwareRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadUpgradeFirmwareRequest() *UploadUpgradeFirmwareRequest {
	this := UploadUpgradeFirmwareRequest{}
	return &this
}

// NewUploadUpgradeFirmwareRequestWithDefaults instantiates a new UploadUpgradeFirmwareRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadUpgradeFirmwareRequestWithDefaults() *UploadUpgradeFirmwareRequest {
	this := UploadUpgradeFirmwareRequest{}
	return &this
}

// GetFile returns the File field value if set, zero value otherwise.
func (o *UploadUpgradeFirmwareRequest) GetFile() *os.File {
	if o == nil || IsNil(o.File) {
		var ret *os.File
		return ret
	}
	return *o.File
}

// GetFileOk returns a tuple with the File field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadUpgradeFirmwareRequest) GetFileOk() (**os.File, bool) {
	if o == nil || IsNil(o.File) {
		return nil, false
	}
	return o.File, true
}

// HasFile returns a boolean if a field has been set.
func (o *UploadUpgradeFirmwareRequest) HasFile() bool {
	if o != nil && !IsNil(o.File) {
		return true
	}

	return false
}

// SetFile gets a reference to the given *os.File and assigns it to the File field.
func (o *UploadUpgradeFirmwareRequest) SetFile(v *os.File) {
	o.File = &v
}

func (o UploadUpgradeFirmwareRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadUpgradeFirmwareRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.File) {
		toSerialize["file"] = o.File
	}
	return toSerialize, nil
}

type NullableUploadUpgradeFirmwareRequest struct {
	value *UploadUpgradeFirmwareRequest
	isSet bool
}

func (v NullableUploadUpgradeFirmwareRequest) Get() *UploadUpgradeFirmwareRequest {
	return v.value
}

func (v *NullableUploadUpgradeFirmwareRequest) Set(val *UploadUpgradeFirmwareRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadUpgradeFirmwareRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadUpgradeFirmwareRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadUpgradeFirmwareRequest(val *UploadUpgradeFirmwareRequest) *NullableUploadUpgradeFirmwareRequest {
	return &NullableUploadUpgradeFirmwareRequest{value: val, isSet: true}
}

func (v NullableUploadUpgradeFirmwareRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadUpgradeFirmwareRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


