/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EthLagPortAppDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EthLagPortAppDTO{}

// EthLagPortAppDTO struct for EthLagPortAppDTO
type EthLagPortAppDTO struct {
	// Description of port
	Description *string `json:"description,omitempty"`
	// Port duplex negotiation mode.Duplex should be a value as follows: 2:FULL,0:AUTO
	Duplex *int32 `json:"duplex,omitempty"`
	// Port flow control function switch.FlowControl should be a value as follows: 0:DISABLE;1:ENABLE
	FlowControl *int32 `json:"flowControl,omitempty"`
	// ID of LAG
	Lag string `json:"lag"`
	// Port speed negotiation mode. speed should be a value as follows: 0;10;100;1000;2500;10000.0 represents Auto, and all other values are in Mbps.
	Speed *int32 `json:"speed,omitempty"`
	// Port switch status.Status should be a value as follows:0:DISABLE;1:ENABLE
	Status *int32 `json:"status,omitempty"`
}

type _EthLagPortAppDTO EthLagPortAppDTO

// NewEthLagPortAppDTO instantiates a new EthLagPortAppDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEthLagPortAppDTO(lag string) *EthLagPortAppDTO {
	this := EthLagPortAppDTO{}
	this.Lag = lag
	return &this
}

// NewEthLagPortAppDTOWithDefaults instantiates a new EthLagPortAppDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEthLagPortAppDTOWithDefaults() *EthLagPortAppDTO {
	this := EthLagPortAppDTO{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *EthLagPortAppDTO) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EthLagPortAppDTO) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *EthLagPortAppDTO) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *EthLagPortAppDTO) SetDescription(v string) {
	o.Description = &v
}

// GetDuplex returns the Duplex field value if set, zero value otherwise.
func (o *EthLagPortAppDTO) GetDuplex() int32 {
	if o == nil || IsNil(o.Duplex) {
		var ret int32
		return ret
	}
	return *o.Duplex
}

// GetDuplexOk returns a tuple with the Duplex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EthLagPortAppDTO) GetDuplexOk() (*int32, bool) {
	if o == nil || IsNil(o.Duplex) {
		return nil, false
	}
	return o.Duplex, true
}

// HasDuplex returns a boolean if a field has been set.
func (o *EthLagPortAppDTO) HasDuplex() bool {
	if o != nil && !IsNil(o.Duplex) {
		return true
	}

	return false
}

// SetDuplex gets a reference to the given int32 and assigns it to the Duplex field.
func (o *EthLagPortAppDTO) SetDuplex(v int32) {
	o.Duplex = &v
}

// GetFlowControl returns the FlowControl field value if set, zero value otherwise.
func (o *EthLagPortAppDTO) GetFlowControl() int32 {
	if o == nil || IsNil(o.FlowControl) {
		var ret int32
		return ret
	}
	return *o.FlowControl
}

// GetFlowControlOk returns a tuple with the FlowControl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EthLagPortAppDTO) GetFlowControlOk() (*int32, bool) {
	if o == nil || IsNil(o.FlowControl) {
		return nil, false
	}
	return o.FlowControl, true
}

// HasFlowControl returns a boolean if a field has been set.
func (o *EthLagPortAppDTO) HasFlowControl() bool {
	if o != nil && !IsNil(o.FlowControl) {
		return true
	}

	return false
}

// SetFlowControl gets a reference to the given int32 and assigns it to the FlowControl field.
func (o *EthLagPortAppDTO) SetFlowControl(v int32) {
	o.FlowControl = &v
}

// GetLag returns the Lag field value
func (o *EthLagPortAppDTO) GetLag() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Lag
}

// GetLagOk returns a tuple with the Lag field value
// and a boolean to check if the value has been set.
func (o *EthLagPortAppDTO) GetLagOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lag, true
}

// SetLag sets field value
func (o *EthLagPortAppDTO) SetLag(v string) {
	o.Lag = v
}

// GetSpeed returns the Speed field value if set, zero value otherwise.
func (o *EthLagPortAppDTO) GetSpeed() int32 {
	if o == nil || IsNil(o.Speed) {
		var ret int32
		return ret
	}
	return *o.Speed
}

// GetSpeedOk returns a tuple with the Speed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EthLagPortAppDTO) GetSpeedOk() (*int32, bool) {
	if o == nil || IsNil(o.Speed) {
		return nil, false
	}
	return o.Speed, true
}

// HasSpeed returns a boolean if a field has been set.
func (o *EthLagPortAppDTO) HasSpeed() bool {
	if o != nil && !IsNil(o.Speed) {
		return true
	}

	return false
}

// SetSpeed gets a reference to the given int32 and assigns it to the Speed field.
func (o *EthLagPortAppDTO) SetSpeed(v int32) {
	o.Speed = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *EthLagPortAppDTO) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EthLagPortAppDTO) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *EthLagPortAppDTO) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *EthLagPortAppDTO) SetStatus(v int32) {
	o.Status = &v
}

func (o EthLagPortAppDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EthLagPortAppDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Duplex) {
		toSerialize["duplex"] = o.Duplex
	}
	if !IsNil(o.FlowControl) {
		toSerialize["flowControl"] = o.FlowControl
	}
	toSerialize["lag"] = o.Lag
	if !IsNil(o.Speed) {
		toSerialize["speed"] = o.Speed
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

func (o *EthLagPortAppDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"lag",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEthLagPortAppDTO := _EthLagPortAppDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEthLagPortAppDTO)

	if err != nil {
		return err
	}

	*o = EthLagPortAppDTO(varEthLagPortAppDTO)

	return err
}

type NullableEthLagPortAppDTO struct {
	value *EthLagPortAppDTO
	isSet bool
}

func (v NullableEthLagPortAppDTO) Get() *EthLagPortAppDTO {
	return v.value
}

func (v *NullableEthLagPortAppDTO) Set(val *EthLagPortAppDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableEthLagPortAppDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableEthLagPortAppDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEthLagPortAppDTO(val *EthLagPortAppDTO) *NullableEthLagPortAppDTO {
	return &NullableEthLagPortAppDTO{value: val, isSet: true}
}

func (v NullableEthLagPortAppDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEthLagPortAppDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


