/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
)

// checks if the EasyManagedSwitchGeneralConfigDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EasyManagedSwitchGeneralConfigDetail{}

// EasyManagedSwitchGeneralConfigDetail struct for EasyManagedSwitchGeneralConfigDetail
type EasyManagedSwitchGeneralConfigDetail struct {
	// Parameter [jumboEnable] should be true or false.
	JumboEnable *bool `json:"jumboEnable,omitempty"`
	// LED setting should be a value as follows: 0:off; 1:on; 2:Use Site Settings
	LedSetting *int32 `json:"ledSetting,omitempty"`
	Location *DeviceLocationDetailVO `json:"location,omitempty"`
	// Device name should contain 1 to 32 characters.
	Name *string `json:"name,omitempty"`
	// Power alert status.
	PowerAlertEnable *bool `json:"powerAlertEnable,omitempty"`
	// Parameter [remember] should be true or false.
	Remember *bool `json:"remember,omitempty"`
	// Parameter [supportPowerAlert] should be true or false.
	SupportPowerAlert *bool `json:"supportPowerAlert,omitempty"`
	// Tag IDs
	TagIds []string `json:"tagIds,omitempty"`
}

// NewEasyManagedSwitchGeneralConfigDetail instantiates a new EasyManagedSwitchGeneralConfigDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEasyManagedSwitchGeneralConfigDetail() *EasyManagedSwitchGeneralConfigDetail {
	this := EasyManagedSwitchGeneralConfigDetail{}
	return &this
}

// NewEasyManagedSwitchGeneralConfigDetailWithDefaults instantiates a new EasyManagedSwitchGeneralConfigDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEasyManagedSwitchGeneralConfigDetailWithDefaults() *EasyManagedSwitchGeneralConfigDetail {
	this := EasyManagedSwitchGeneralConfigDetail{}
	return &this
}

// GetJumboEnable returns the JumboEnable field value if set, zero value otherwise.
func (o *EasyManagedSwitchGeneralConfigDetail) GetJumboEnable() bool {
	if o == nil || IsNil(o.JumboEnable) {
		var ret bool
		return ret
	}
	return *o.JumboEnable
}

// GetJumboEnableOk returns a tuple with the JumboEnable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EasyManagedSwitchGeneralConfigDetail) GetJumboEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.JumboEnable) {
		return nil, false
	}
	return o.JumboEnable, true
}

// HasJumboEnable returns a boolean if a field has been set.
func (o *EasyManagedSwitchGeneralConfigDetail) HasJumboEnable() bool {
	if o != nil && !IsNil(o.JumboEnable) {
		return true
	}

	return false
}

// SetJumboEnable gets a reference to the given bool and assigns it to the JumboEnable field.
func (o *EasyManagedSwitchGeneralConfigDetail) SetJumboEnable(v bool) {
	o.JumboEnable = &v
}

// GetLedSetting returns the LedSetting field value if set, zero value otherwise.
func (o *EasyManagedSwitchGeneralConfigDetail) GetLedSetting() int32 {
	if o == nil || IsNil(o.LedSetting) {
		var ret int32
		return ret
	}
	return *o.LedSetting
}

// GetLedSettingOk returns a tuple with the LedSetting field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EasyManagedSwitchGeneralConfigDetail) GetLedSettingOk() (*int32, bool) {
	if o == nil || IsNil(o.LedSetting) {
		return nil, false
	}
	return o.LedSetting, true
}

// HasLedSetting returns a boolean if a field has been set.
func (o *EasyManagedSwitchGeneralConfigDetail) HasLedSetting() bool {
	if o != nil && !IsNil(o.LedSetting) {
		return true
	}

	return false
}

// SetLedSetting gets a reference to the given int32 and assigns it to the LedSetting field.
func (o *EasyManagedSwitchGeneralConfigDetail) SetLedSetting(v int32) {
	o.LedSetting = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *EasyManagedSwitchGeneralConfigDetail) GetLocation() DeviceLocationDetailVO {
	if o == nil || IsNil(o.Location) {
		var ret DeviceLocationDetailVO
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EasyManagedSwitchGeneralConfigDetail) GetLocationOk() (*DeviceLocationDetailVO, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *EasyManagedSwitchGeneralConfigDetail) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given DeviceLocationDetailVO and assigns it to the Location field.
func (o *EasyManagedSwitchGeneralConfigDetail) SetLocation(v DeviceLocationDetailVO) {
	o.Location = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *EasyManagedSwitchGeneralConfigDetail) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EasyManagedSwitchGeneralConfigDetail) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *EasyManagedSwitchGeneralConfigDetail) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *EasyManagedSwitchGeneralConfigDetail) SetName(v string) {
	o.Name = &v
}

// GetPowerAlertEnable returns the PowerAlertEnable field value if set, zero value otherwise.
func (o *EasyManagedSwitchGeneralConfigDetail) GetPowerAlertEnable() bool {
	if o == nil || IsNil(o.PowerAlertEnable) {
		var ret bool
		return ret
	}
	return *o.PowerAlertEnable
}

// GetPowerAlertEnableOk returns a tuple with the PowerAlertEnable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EasyManagedSwitchGeneralConfigDetail) GetPowerAlertEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.PowerAlertEnable) {
		return nil, false
	}
	return o.PowerAlertEnable, true
}

// HasPowerAlertEnable returns a boolean if a field has been set.
func (o *EasyManagedSwitchGeneralConfigDetail) HasPowerAlertEnable() bool {
	if o != nil && !IsNil(o.PowerAlertEnable) {
		return true
	}

	return false
}

// SetPowerAlertEnable gets a reference to the given bool and assigns it to the PowerAlertEnable field.
func (o *EasyManagedSwitchGeneralConfigDetail) SetPowerAlertEnable(v bool) {
	o.PowerAlertEnable = &v
}

// GetRemember returns the Remember field value if set, zero value otherwise.
func (o *EasyManagedSwitchGeneralConfigDetail) GetRemember() bool {
	if o == nil || IsNil(o.Remember) {
		var ret bool
		return ret
	}
	return *o.Remember
}

// GetRememberOk returns a tuple with the Remember field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EasyManagedSwitchGeneralConfigDetail) GetRememberOk() (*bool, bool) {
	if o == nil || IsNil(o.Remember) {
		return nil, false
	}
	return o.Remember, true
}

// HasRemember returns a boolean if a field has been set.
func (o *EasyManagedSwitchGeneralConfigDetail) HasRemember() bool {
	if o != nil && !IsNil(o.Remember) {
		return true
	}

	return false
}

// SetRemember gets a reference to the given bool and assigns it to the Remember field.
func (o *EasyManagedSwitchGeneralConfigDetail) SetRemember(v bool) {
	o.Remember = &v
}

// GetSupportPowerAlert returns the SupportPowerAlert field value if set, zero value otherwise.
func (o *EasyManagedSwitchGeneralConfigDetail) GetSupportPowerAlert() bool {
	if o == nil || IsNil(o.SupportPowerAlert) {
		var ret bool
		return ret
	}
	return *o.SupportPowerAlert
}

// GetSupportPowerAlertOk returns a tuple with the SupportPowerAlert field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EasyManagedSwitchGeneralConfigDetail) GetSupportPowerAlertOk() (*bool, bool) {
	if o == nil || IsNil(o.SupportPowerAlert) {
		return nil, false
	}
	return o.SupportPowerAlert, true
}

// HasSupportPowerAlert returns a boolean if a field has been set.
func (o *EasyManagedSwitchGeneralConfigDetail) HasSupportPowerAlert() bool {
	if o != nil && !IsNil(o.SupportPowerAlert) {
		return true
	}

	return false
}

// SetSupportPowerAlert gets a reference to the given bool and assigns it to the SupportPowerAlert field.
func (o *EasyManagedSwitchGeneralConfigDetail) SetSupportPowerAlert(v bool) {
	o.SupportPowerAlert = &v
}

// GetTagIds returns the TagIds field value if set, zero value otherwise.
func (o *EasyManagedSwitchGeneralConfigDetail) GetTagIds() []string {
	if o == nil || IsNil(o.TagIds) {
		var ret []string
		return ret
	}
	return o.TagIds
}

// GetTagIdsOk returns a tuple with the TagIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EasyManagedSwitchGeneralConfigDetail) GetTagIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.TagIds) {
		return nil, false
	}
	return o.TagIds, true
}

// HasTagIds returns a boolean if a field has been set.
func (o *EasyManagedSwitchGeneralConfigDetail) HasTagIds() bool {
	if o != nil && !IsNil(o.TagIds) {
		return true
	}

	return false
}

// SetTagIds gets a reference to the given []string and assigns it to the TagIds field.
func (o *EasyManagedSwitchGeneralConfigDetail) SetTagIds(v []string) {
	o.TagIds = v
}

func (o EasyManagedSwitchGeneralConfigDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EasyManagedSwitchGeneralConfigDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.JumboEnable) {
		toSerialize["jumboEnable"] = o.JumboEnable
	}
	if !IsNil(o.LedSetting) {
		toSerialize["ledSetting"] = o.LedSetting
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.PowerAlertEnable) {
		toSerialize["powerAlertEnable"] = o.PowerAlertEnable
	}
	if !IsNil(o.Remember) {
		toSerialize["remember"] = o.Remember
	}
	if !IsNil(o.SupportPowerAlert) {
		toSerialize["supportPowerAlert"] = o.SupportPowerAlert
	}
	if !IsNil(o.TagIds) {
		toSerialize["tagIds"] = o.TagIds
	}
	return toSerialize, nil
}

type NullableEasyManagedSwitchGeneralConfigDetail struct {
	value *EasyManagedSwitchGeneralConfigDetail
	isSet bool
}

func (v NullableEasyManagedSwitchGeneralConfigDetail) Get() *EasyManagedSwitchGeneralConfigDetail {
	return v.value
}

func (v *NullableEasyManagedSwitchGeneralConfigDetail) Set(val *EasyManagedSwitchGeneralConfigDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableEasyManagedSwitchGeneralConfigDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableEasyManagedSwitchGeneralConfigDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEasyManagedSwitchGeneralConfigDetail(val *EasyManagedSwitchGeneralConfigDetail) *NullableEasyManagedSwitchGeneralConfigDetail {
	return &NullableEasyManagedSwitchGeneralConfigDetail{value: val, isSet: true}
}

func (v NullableEasyManagedSwitchGeneralConfigDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEasyManagedSwitchGeneralConfigDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


