/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OswNetworkOpenApi type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OswNetworkOpenApi{}

// OswNetworkOpenApi struct for OswNetworkOpenApi
type OswNetworkOpenApi struct {
	DhcpRelay *OswDhcpRelayOpenApiVO `json:"dhcpRelay,omitempty"`
	DhcpServer *OswDhcpServerOpenApiVO `json:"dhcpServer,omitempty"`
	// Network ID
	Id string `json:"id"`
	Ip *OswIpSettingOpenApiVO `json:"ip,omitempty"`
	Ipv6 *OswIpv6SettingOpenApiVO `json:"ipv6,omitempty"`
	// Enable IPV6 or not.
	Ipv6Enable *bool `json:"ipv6Enable,omitempty"`
	// DHCP mode. 0: None, mode 1: DHCP Server, mode 2: DHCP Relay
	Mode int32 `json:"mode"`
	// Indicate the vlan is management vlan or not.
	Mvlan bool `json:"mvlan"`
	// Switch network name.
	Name *string `json:"name,omitempty"`
	// Enable status of the network vlan.
	Status *bool `json:"status,omitempty"`
	// VLAN ID.
	Vlan int32 `json:"vlan"`
	// VRF ID
	VrfId *string `json:"vrfId,omitempty"`
}

type _OswNetworkOpenApi OswNetworkOpenApi

// NewOswNetworkOpenApi instantiates a new OswNetworkOpenApi object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOswNetworkOpenApi(id string, mode int32, mvlan bool, vlan int32) *OswNetworkOpenApi {
	this := OswNetworkOpenApi{}
	this.Id = id
	this.Mode = mode
	this.Mvlan = mvlan
	this.Vlan = vlan
	return &this
}

// NewOswNetworkOpenApiWithDefaults instantiates a new OswNetworkOpenApi object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOswNetworkOpenApiWithDefaults() *OswNetworkOpenApi {
	this := OswNetworkOpenApi{}
	return &this
}

// GetDhcpRelay returns the DhcpRelay field value if set, zero value otherwise.
func (o *OswNetworkOpenApi) GetDhcpRelay() OswDhcpRelayOpenApiVO {
	if o == nil || IsNil(o.DhcpRelay) {
		var ret OswDhcpRelayOpenApiVO
		return ret
	}
	return *o.DhcpRelay
}

// GetDhcpRelayOk returns a tuple with the DhcpRelay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OswNetworkOpenApi) GetDhcpRelayOk() (*OswDhcpRelayOpenApiVO, bool) {
	if o == nil || IsNil(o.DhcpRelay) {
		return nil, false
	}
	return o.DhcpRelay, true
}

// HasDhcpRelay returns a boolean if a field has been set.
func (o *OswNetworkOpenApi) HasDhcpRelay() bool {
	if o != nil && !IsNil(o.DhcpRelay) {
		return true
	}

	return false
}

// SetDhcpRelay gets a reference to the given OswDhcpRelayOpenApiVO and assigns it to the DhcpRelay field.
func (o *OswNetworkOpenApi) SetDhcpRelay(v OswDhcpRelayOpenApiVO) {
	o.DhcpRelay = &v
}

// GetDhcpServer returns the DhcpServer field value if set, zero value otherwise.
func (o *OswNetworkOpenApi) GetDhcpServer() OswDhcpServerOpenApiVO {
	if o == nil || IsNil(o.DhcpServer) {
		var ret OswDhcpServerOpenApiVO
		return ret
	}
	return *o.DhcpServer
}

// GetDhcpServerOk returns a tuple with the DhcpServer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OswNetworkOpenApi) GetDhcpServerOk() (*OswDhcpServerOpenApiVO, bool) {
	if o == nil || IsNil(o.DhcpServer) {
		return nil, false
	}
	return o.DhcpServer, true
}

// HasDhcpServer returns a boolean if a field has been set.
func (o *OswNetworkOpenApi) HasDhcpServer() bool {
	if o != nil && !IsNil(o.DhcpServer) {
		return true
	}

	return false
}

// SetDhcpServer gets a reference to the given OswDhcpServerOpenApiVO and assigns it to the DhcpServer field.
func (o *OswNetworkOpenApi) SetDhcpServer(v OswDhcpServerOpenApiVO) {
	o.DhcpServer = &v
}

// GetId returns the Id field value
func (o *OswNetworkOpenApi) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OswNetworkOpenApi) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OswNetworkOpenApi) SetId(v string) {
	o.Id = v
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *OswNetworkOpenApi) GetIp() OswIpSettingOpenApiVO {
	if o == nil || IsNil(o.Ip) {
		var ret OswIpSettingOpenApiVO
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OswNetworkOpenApi) GetIpOk() (*OswIpSettingOpenApiVO, bool) {
	if o == nil || IsNil(o.Ip) {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *OswNetworkOpenApi) HasIp() bool {
	if o != nil && !IsNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given OswIpSettingOpenApiVO and assigns it to the Ip field.
func (o *OswNetworkOpenApi) SetIp(v OswIpSettingOpenApiVO) {
	o.Ip = &v
}

// GetIpv6 returns the Ipv6 field value if set, zero value otherwise.
func (o *OswNetworkOpenApi) GetIpv6() OswIpv6SettingOpenApiVO {
	if o == nil || IsNil(o.Ipv6) {
		var ret OswIpv6SettingOpenApiVO
		return ret
	}
	return *o.Ipv6
}

// GetIpv6Ok returns a tuple with the Ipv6 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OswNetworkOpenApi) GetIpv6Ok() (*OswIpv6SettingOpenApiVO, bool) {
	if o == nil || IsNil(o.Ipv6) {
		return nil, false
	}
	return o.Ipv6, true
}

// HasIpv6 returns a boolean if a field has been set.
func (o *OswNetworkOpenApi) HasIpv6() bool {
	if o != nil && !IsNil(o.Ipv6) {
		return true
	}

	return false
}

// SetIpv6 gets a reference to the given OswIpv6SettingOpenApiVO and assigns it to the Ipv6 field.
func (o *OswNetworkOpenApi) SetIpv6(v OswIpv6SettingOpenApiVO) {
	o.Ipv6 = &v
}

// GetIpv6Enable returns the Ipv6Enable field value if set, zero value otherwise.
func (o *OswNetworkOpenApi) GetIpv6Enable() bool {
	if o == nil || IsNil(o.Ipv6Enable) {
		var ret bool
		return ret
	}
	return *o.Ipv6Enable
}

// GetIpv6EnableOk returns a tuple with the Ipv6Enable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OswNetworkOpenApi) GetIpv6EnableOk() (*bool, bool) {
	if o == nil || IsNil(o.Ipv6Enable) {
		return nil, false
	}
	return o.Ipv6Enable, true
}

// HasIpv6Enable returns a boolean if a field has been set.
func (o *OswNetworkOpenApi) HasIpv6Enable() bool {
	if o != nil && !IsNil(o.Ipv6Enable) {
		return true
	}

	return false
}

// SetIpv6Enable gets a reference to the given bool and assigns it to the Ipv6Enable field.
func (o *OswNetworkOpenApi) SetIpv6Enable(v bool) {
	o.Ipv6Enable = &v
}

// GetMode returns the Mode field value
func (o *OswNetworkOpenApi) GetMode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *OswNetworkOpenApi) GetModeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *OswNetworkOpenApi) SetMode(v int32) {
	o.Mode = v
}

// GetMvlan returns the Mvlan field value
func (o *OswNetworkOpenApi) GetMvlan() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Mvlan
}

// GetMvlanOk returns a tuple with the Mvlan field value
// and a boolean to check if the value has been set.
func (o *OswNetworkOpenApi) GetMvlanOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mvlan, true
}

// SetMvlan sets field value
func (o *OswNetworkOpenApi) SetMvlan(v bool) {
	o.Mvlan = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *OswNetworkOpenApi) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OswNetworkOpenApi) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *OswNetworkOpenApi) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *OswNetworkOpenApi) SetName(v string) {
	o.Name = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *OswNetworkOpenApi) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OswNetworkOpenApi) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *OswNetworkOpenApi) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *OswNetworkOpenApi) SetStatus(v bool) {
	o.Status = &v
}

// GetVlan returns the Vlan field value
func (o *OswNetworkOpenApi) GetVlan() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Vlan
}

// GetVlanOk returns a tuple with the Vlan field value
// and a boolean to check if the value has been set.
func (o *OswNetworkOpenApi) GetVlanOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Vlan, true
}

// SetVlan sets field value
func (o *OswNetworkOpenApi) SetVlan(v int32) {
	o.Vlan = v
}

// GetVrfId returns the VrfId field value if set, zero value otherwise.
func (o *OswNetworkOpenApi) GetVrfId() string {
	if o == nil || IsNil(o.VrfId) {
		var ret string
		return ret
	}
	return *o.VrfId
}

// GetVrfIdOk returns a tuple with the VrfId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OswNetworkOpenApi) GetVrfIdOk() (*string, bool) {
	if o == nil || IsNil(o.VrfId) {
		return nil, false
	}
	return o.VrfId, true
}

// HasVrfId returns a boolean if a field has been set.
func (o *OswNetworkOpenApi) HasVrfId() bool {
	if o != nil && !IsNil(o.VrfId) {
		return true
	}

	return false
}

// SetVrfId gets a reference to the given string and assigns it to the VrfId field.
func (o *OswNetworkOpenApi) SetVrfId(v string) {
	o.VrfId = &v
}

func (o OswNetworkOpenApi) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OswNetworkOpenApi) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DhcpRelay) {
		toSerialize["dhcpRelay"] = o.DhcpRelay
	}
	if !IsNil(o.DhcpServer) {
		toSerialize["dhcpServer"] = o.DhcpServer
	}
	toSerialize["id"] = o.Id
	if !IsNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}
	if !IsNil(o.Ipv6) {
		toSerialize["ipv6"] = o.Ipv6
	}
	if !IsNil(o.Ipv6Enable) {
		toSerialize["ipv6Enable"] = o.Ipv6Enable
	}
	toSerialize["mode"] = o.Mode
	toSerialize["mvlan"] = o.Mvlan
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	toSerialize["vlan"] = o.Vlan
	if !IsNil(o.VrfId) {
		toSerialize["vrfId"] = o.VrfId
	}
	return toSerialize, nil
}

func (o *OswNetworkOpenApi) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"mode",
		"mvlan",
		"vlan",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOswNetworkOpenApi := _OswNetworkOpenApi{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOswNetworkOpenApi)

	if err != nil {
		return err
	}

	*o = OswNetworkOpenApi(varOswNetworkOpenApi)

	return err
}

type NullableOswNetworkOpenApi struct {
	value *OswNetworkOpenApi
	isSet bool
}

func (v NullableOswNetworkOpenApi) Get() *OswNetworkOpenApi {
	return v.value
}

func (v *NullableOswNetworkOpenApi) Set(val *OswNetworkOpenApi) {
	v.value = val
	v.isSet = true
}

func (v NullableOswNetworkOpenApi) IsSet() bool {
	return v.isSet
}

func (v *NullableOswNetworkOpenApi) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOswNetworkOpenApi(val *OswNetworkOpenApi) *NullableOswNetworkOpenApi {
	return &NullableOswNetworkOpenApi{value: val, isSet: true}
}

func (v NullableOswNetworkOpenApi) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOswNetworkOpenApi) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


