/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
)

// checks if the VoucherDurationDistributionOpenApiVO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VoucherDurationDistributionOpenApiVO{}

// VoucherDurationDistributionOpenApiVO struct for VoucherDurationDistributionOpenApiVO
type VoucherDurationDistributionOpenApiVO struct {
	// Duration of single voucher, unit: minutes
	Duration *int64 `json:"duration,omitempty"`
	// The duration type of the voucher. It should be a value as follows: 0: Client duration, each client expires after the duration is used. 1: Voucher duration, after reaching the voucher duration, clients using the voucher will expire
	DurationType *int32 `json:"durationType,omitempty"`
	// Total duration of vouchers, unit: minutes
	TotalDuration *int64 `json:"totalDuration,omitempty"`
	// Used count of vouchers
	UsedCount *int32 `json:"usedCount,omitempty"`
}

// NewVoucherDurationDistributionOpenApiVO instantiates a new VoucherDurationDistributionOpenApiVO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVoucherDurationDistributionOpenApiVO() *VoucherDurationDistributionOpenApiVO {
	this := VoucherDurationDistributionOpenApiVO{}
	return &this
}

// NewVoucherDurationDistributionOpenApiVOWithDefaults instantiates a new VoucherDurationDistributionOpenApiVO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVoucherDurationDistributionOpenApiVOWithDefaults() *VoucherDurationDistributionOpenApiVO {
	this := VoucherDurationDistributionOpenApiVO{}
	return &this
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *VoucherDurationDistributionOpenApiVO) GetDuration() int64 {
	if o == nil || IsNil(o.Duration) {
		var ret int64
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoucherDurationDistributionOpenApiVO) GetDurationOk() (*int64, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *VoucherDurationDistributionOpenApiVO) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given int64 and assigns it to the Duration field.
func (o *VoucherDurationDistributionOpenApiVO) SetDuration(v int64) {
	o.Duration = &v
}

// GetDurationType returns the DurationType field value if set, zero value otherwise.
func (o *VoucherDurationDistributionOpenApiVO) GetDurationType() int32 {
	if o == nil || IsNil(o.DurationType) {
		var ret int32
		return ret
	}
	return *o.DurationType
}

// GetDurationTypeOk returns a tuple with the DurationType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoucherDurationDistributionOpenApiVO) GetDurationTypeOk() (*int32, bool) {
	if o == nil || IsNil(o.DurationType) {
		return nil, false
	}
	return o.DurationType, true
}

// HasDurationType returns a boolean if a field has been set.
func (o *VoucherDurationDistributionOpenApiVO) HasDurationType() bool {
	if o != nil && !IsNil(o.DurationType) {
		return true
	}

	return false
}

// SetDurationType gets a reference to the given int32 and assigns it to the DurationType field.
func (o *VoucherDurationDistributionOpenApiVO) SetDurationType(v int32) {
	o.DurationType = &v
}

// GetTotalDuration returns the TotalDuration field value if set, zero value otherwise.
func (o *VoucherDurationDistributionOpenApiVO) GetTotalDuration() int64 {
	if o == nil || IsNil(o.TotalDuration) {
		var ret int64
		return ret
	}
	return *o.TotalDuration
}

// GetTotalDurationOk returns a tuple with the TotalDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoucherDurationDistributionOpenApiVO) GetTotalDurationOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalDuration) {
		return nil, false
	}
	return o.TotalDuration, true
}

// HasTotalDuration returns a boolean if a field has been set.
func (o *VoucherDurationDistributionOpenApiVO) HasTotalDuration() bool {
	if o != nil && !IsNil(o.TotalDuration) {
		return true
	}

	return false
}

// SetTotalDuration gets a reference to the given int64 and assigns it to the TotalDuration field.
func (o *VoucherDurationDistributionOpenApiVO) SetTotalDuration(v int64) {
	o.TotalDuration = &v
}

// GetUsedCount returns the UsedCount field value if set, zero value otherwise.
func (o *VoucherDurationDistributionOpenApiVO) GetUsedCount() int32 {
	if o == nil || IsNil(o.UsedCount) {
		var ret int32
		return ret
	}
	return *o.UsedCount
}

// GetUsedCountOk returns a tuple with the UsedCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoucherDurationDistributionOpenApiVO) GetUsedCountOk() (*int32, bool) {
	if o == nil || IsNil(o.UsedCount) {
		return nil, false
	}
	return o.UsedCount, true
}

// HasUsedCount returns a boolean if a field has been set.
func (o *VoucherDurationDistributionOpenApiVO) HasUsedCount() bool {
	if o != nil && !IsNil(o.UsedCount) {
		return true
	}

	return false
}

// SetUsedCount gets a reference to the given int32 and assigns it to the UsedCount field.
func (o *VoucherDurationDistributionOpenApiVO) SetUsedCount(v int32) {
	o.UsedCount = &v
}

func (o VoucherDurationDistributionOpenApiVO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VoucherDurationDistributionOpenApiVO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	if !IsNil(o.DurationType) {
		toSerialize["durationType"] = o.DurationType
	}
	if !IsNil(o.TotalDuration) {
		toSerialize["totalDuration"] = o.TotalDuration
	}
	if !IsNil(o.UsedCount) {
		toSerialize["usedCount"] = o.UsedCount
	}
	return toSerialize, nil
}

type NullableVoucherDurationDistributionOpenApiVO struct {
	value *VoucherDurationDistributionOpenApiVO
	isSet bool
}

func (v NullableVoucherDurationDistributionOpenApiVO) Get() *VoucherDurationDistributionOpenApiVO {
	return v.value
}

func (v *NullableVoucherDurationDistributionOpenApiVO) Set(val *VoucherDurationDistributionOpenApiVO) {
	v.value = val
	v.isSet = true
}

func (v NullableVoucherDurationDistributionOpenApiVO) IsSet() bool {
	return v.isSet
}

func (v *NullableVoucherDurationDistributionOpenApiVO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVoucherDurationDistributionOpenApiVO(val *VoucherDurationDistributionOpenApiVO) *NullableVoucherDurationDistributionOpenApiVO {
	return &NullableVoucherDurationDistributionOpenApiVO{value: val, isSet: true}
}

func (v NullableVoucherDurationDistributionOpenApiVO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVoucherDurationDistributionOpenApiVO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


