/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
)

// checks if the Top5ThreatNumOpenApiVO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Top5ThreatNumOpenApiVO{}

// Top5ThreatNumOpenApiVO struct for Top5ThreatNumOpenApiVO
type Top5ThreatNumOpenApiVO struct {
	// Classification List.
	Classification []ClassificationOpenApiVO `json:"classification,omitempty"`
	// Geo List.
	Geo []GeoOpenApiVO `json:"geo,omitempty"`
}

// NewTop5ThreatNumOpenApiVO instantiates a new Top5ThreatNumOpenApiVO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTop5ThreatNumOpenApiVO() *Top5ThreatNumOpenApiVO {
	this := Top5ThreatNumOpenApiVO{}
	return &this
}

// NewTop5ThreatNumOpenApiVOWithDefaults instantiates a new Top5ThreatNumOpenApiVO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTop5ThreatNumOpenApiVOWithDefaults() *Top5ThreatNumOpenApiVO {
	this := Top5ThreatNumOpenApiVO{}
	return &this
}

// GetClassification returns the Classification field value if set, zero value otherwise.
func (o *Top5ThreatNumOpenApiVO) GetClassification() []ClassificationOpenApiVO {
	if o == nil || IsNil(o.Classification) {
		var ret []ClassificationOpenApiVO
		return ret
	}
	return o.Classification
}

// GetClassificationOk returns a tuple with the Classification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Top5ThreatNumOpenApiVO) GetClassificationOk() ([]ClassificationOpenApiVO, bool) {
	if o == nil || IsNil(o.Classification) {
		return nil, false
	}
	return o.Classification, true
}

// HasClassification returns a boolean if a field has been set.
func (o *Top5ThreatNumOpenApiVO) HasClassification() bool {
	if o != nil && !IsNil(o.Classification) {
		return true
	}

	return false
}

// SetClassification gets a reference to the given []ClassificationOpenApiVO and assigns it to the Classification field.
func (o *Top5ThreatNumOpenApiVO) SetClassification(v []ClassificationOpenApiVO) {
	o.Classification = v
}

// GetGeo returns the Geo field value if set, zero value otherwise.
func (o *Top5ThreatNumOpenApiVO) GetGeo() []GeoOpenApiVO {
	if o == nil || IsNil(o.Geo) {
		var ret []GeoOpenApiVO
		return ret
	}
	return o.Geo
}

// GetGeoOk returns a tuple with the Geo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Top5ThreatNumOpenApiVO) GetGeoOk() ([]GeoOpenApiVO, bool) {
	if o == nil || IsNil(o.Geo) {
		return nil, false
	}
	return o.Geo, true
}

// HasGeo returns a boolean if a field has been set.
func (o *Top5ThreatNumOpenApiVO) HasGeo() bool {
	if o != nil && !IsNil(o.Geo) {
		return true
	}

	return false
}

// SetGeo gets a reference to the given []GeoOpenApiVO and assigns it to the Geo field.
func (o *Top5ThreatNumOpenApiVO) SetGeo(v []GeoOpenApiVO) {
	o.Geo = v
}

func (o Top5ThreatNumOpenApiVO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Top5ThreatNumOpenApiVO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Classification) {
		toSerialize["classification"] = o.Classification
	}
	if !IsNil(o.Geo) {
		toSerialize["geo"] = o.Geo
	}
	return toSerialize, nil
}

type NullableTop5ThreatNumOpenApiVO struct {
	value *Top5ThreatNumOpenApiVO
	isSet bool
}

func (v NullableTop5ThreatNumOpenApiVO) Get() *Top5ThreatNumOpenApiVO {
	return v.value
}

func (v *NullableTop5ThreatNumOpenApiVO) Set(val *Top5ThreatNumOpenApiVO) {
	v.value = val
	v.isSet = true
}

func (v NullableTop5ThreatNumOpenApiVO) IsSet() bool {
	return v.isSet
}

func (v *NullableTop5ThreatNumOpenApiVO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTop5ThreatNumOpenApiVO(val *Top5ThreatNumOpenApiVO) *NullableTop5ThreatNumOpenApiVO {
	return &NullableTop5ThreatNumOpenApiVO{value: val, isSet: true}
}

func (v NullableTop5ThreatNumOpenApiVO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTop5ThreatNumOpenApiVO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


