/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateTimeRangeProfileOpenApiVO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTimeRangeProfileOpenApiVO{}

// CreateTimeRangeProfileOpenApiVO struct for CreateTimeRangeProfileOpenApiVO
type CreateTimeRangeProfileOpenApiVO struct {
	CustomDayMode *CustomDayModeOpenApiVO `json:"customDayMode,omitempty"`
	// Time range profile day mode; It should be a value as follows: 0: Every Day, 1: Weekday, 2: Weekend, 3: Customized
	DayMode int32 `json:"dayMode"`
	// Time range profile name should contain 1 to 64 characters.
	Name string `json:"name" validate:"regexp=^[^ ]$|^[^ ].{0,62}[^ ]$"`
	// Time range profile schedule time config
	TimeList []ScheduleTimeOpenApiVO `json:"timeList"`
}

type _CreateTimeRangeProfileOpenApiVO CreateTimeRangeProfileOpenApiVO

// NewCreateTimeRangeProfileOpenApiVO instantiates a new CreateTimeRangeProfileOpenApiVO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTimeRangeProfileOpenApiVO(dayMode int32, name string, timeList []ScheduleTimeOpenApiVO) *CreateTimeRangeProfileOpenApiVO {
	this := CreateTimeRangeProfileOpenApiVO{}
	this.DayMode = dayMode
	this.Name = name
	this.TimeList = timeList
	return &this
}

// NewCreateTimeRangeProfileOpenApiVOWithDefaults instantiates a new CreateTimeRangeProfileOpenApiVO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTimeRangeProfileOpenApiVOWithDefaults() *CreateTimeRangeProfileOpenApiVO {
	this := CreateTimeRangeProfileOpenApiVO{}
	return &this
}

// GetCustomDayMode returns the CustomDayMode field value if set, zero value otherwise.
func (o *CreateTimeRangeProfileOpenApiVO) GetCustomDayMode() CustomDayModeOpenApiVO {
	if o == nil || IsNil(o.CustomDayMode) {
		var ret CustomDayModeOpenApiVO
		return ret
	}
	return *o.CustomDayMode
}

// GetCustomDayModeOk returns a tuple with the CustomDayMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTimeRangeProfileOpenApiVO) GetCustomDayModeOk() (*CustomDayModeOpenApiVO, bool) {
	if o == nil || IsNil(o.CustomDayMode) {
		return nil, false
	}
	return o.CustomDayMode, true
}

// HasCustomDayMode returns a boolean if a field has been set.
func (o *CreateTimeRangeProfileOpenApiVO) HasCustomDayMode() bool {
	if o != nil && !IsNil(o.CustomDayMode) {
		return true
	}

	return false
}

// SetCustomDayMode gets a reference to the given CustomDayModeOpenApiVO and assigns it to the CustomDayMode field.
func (o *CreateTimeRangeProfileOpenApiVO) SetCustomDayMode(v CustomDayModeOpenApiVO) {
	o.CustomDayMode = &v
}

// GetDayMode returns the DayMode field value
func (o *CreateTimeRangeProfileOpenApiVO) GetDayMode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DayMode
}

// GetDayModeOk returns a tuple with the DayMode field value
// and a boolean to check if the value has been set.
func (o *CreateTimeRangeProfileOpenApiVO) GetDayModeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DayMode, true
}

// SetDayMode sets field value
func (o *CreateTimeRangeProfileOpenApiVO) SetDayMode(v int32) {
	o.DayMode = v
}

// GetName returns the Name field value
func (o *CreateTimeRangeProfileOpenApiVO) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateTimeRangeProfileOpenApiVO) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateTimeRangeProfileOpenApiVO) SetName(v string) {
	o.Name = v
}

// GetTimeList returns the TimeList field value
func (o *CreateTimeRangeProfileOpenApiVO) GetTimeList() []ScheduleTimeOpenApiVO {
	if o == nil {
		var ret []ScheduleTimeOpenApiVO
		return ret
	}

	return o.TimeList
}

// GetTimeListOk returns a tuple with the TimeList field value
// and a boolean to check if the value has been set.
func (o *CreateTimeRangeProfileOpenApiVO) GetTimeListOk() ([]ScheduleTimeOpenApiVO, bool) {
	if o == nil {
		return nil, false
	}
	return o.TimeList, true
}

// SetTimeList sets field value
func (o *CreateTimeRangeProfileOpenApiVO) SetTimeList(v []ScheduleTimeOpenApiVO) {
	o.TimeList = v
}

func (o CreateTimeRangeProfileOpenApiVO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTimeRangeProfileOpenApiVO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomDayMode) {
		toSerialize["customDayMode"] = o.CustomDayMode
	}
	toSerialize["dayMode"] = o.DayMode
	toSerialize["name"] = o.Name
	toSerialize["timeList"] = o.TimeList
	return toSerialize, nil
}

func (o *CreateTimeRangeProfileOpenApiVO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dayMode",
		"name",
		"timeList",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateTimeRangeProfileOpenApiVO := _CreateTimeRangeProfileOpenApiVO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateTimeRangeProfileOpenApiVO)

	if err != nil {
		return err
	}

	*o = CreateTimeRangeProfileOpenApiVO(varCreateTimeRangeProfileOpenApiVO)

	return err
}

type NullableCreateTimeRangeProfileOpenApiVO struct {
	value *CreateTimeRangeProfileOpenApiVO
	isSet bool
}

func (v NullableCreateTimeRangeProfileOpenApiVO) Get() *CreateTimeRangeProfileOpenApiVO {
	return v.value
}

func (v *NullableCreateTimeRangeProfileOpenApiVO) Set(val *CreateTimeRangeProfileOpenApiVO) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTimeRangeProfileOpenApiVO) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTimeRangeProfileOpenApiVO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTimeRangeProfileOpenApiVO(val *CreateTimeRangeProfileOpenApiVO) *NullableCreateTimeRangeProfileOpenApiVO {
	return &NullableCreateTimeRangeProfileOpenApiVO{value: val, isSet: true}
}

func (v NullableCreateTimeRangeProfileOpenApiVO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTimeRangeProfileOpenApiVO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


