/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
)

// checks if the OperationResponseVirtualWanIdUsedOpenApiVO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperationResponseVirtualWanIdUsedOpenApiVO{}

// OperationResponseVirtualWanIdUsedOpenApiVO struct for OperationResponseVirtualWanIdUsedOpenApiVO
type OperationResponseVirtualWanIdUsedOpenApiVO struct {
	ErrorCode *int32 `json:"errorCode,omitempty"`
	Msg *string `json:"msg,omitempty"`
	Result *VirtualWanIdUsedOpenApiVO `json:"result,omitempty"`
}

// NewOperationResponseVirtualWanIdUsedOpenApiVO instantiates a new OperationResponseVirtualWanIdUsedOpenApiVO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperationResponseVirtualWanIdUsedOpenApiVO() *OperationResponseVirtualWanIdUsedOpenApiVO {
	this := OperationResponseVirtualWanIdUsedOpenApiVO{}
	return &this
}

// NewOperationResponseVirtualWanIdUsedOpenApiVOWithDefaults instantiates a new OperationResponseVirtualWanIdUsedOpenApiVO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperationResponseVirtualWanIdUsedOpenApiVOWithDefaults() *OperationResponseVirtualWanIdUsedOpenApiVO {
	this := OperationResponseVirtualWanIdUsedOpenApiVO{}
	return &this
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise.
func (o *OperationResponseVirtualWanIdUsedOpenApiVO) GetErrorCode() int32 {
	if o == nil || IsNil(o.ErrorCode) {
		var ret int32
		return ret
	}
	return *o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperationResponseVirtualWanIdUsedOpenApiVO) GetErrorCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.ErrorCode) {
		return nil, false
	}
	return o.ErrorCode, true
}

// HasErrorCode returns a boolean if a field has been set.
func (o *OperationResponseVirtualWanIdUsedOpenApiVO) HasErrorCode() bool {
	if o != nil && !IsNil(o.ErrorCode) {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given int32 and assigns it to the ErrorCode field.
func (o *OperationResponseVirtualWanIdUsedOpenApiVO) SetErrorCode(v int32) {
	o.ErrorCode = &v
}

// GetMsg returns the Msg field value if set, zero value otherwise.
func (o *OperationResponseVirtualWanIdUsedOpenApiVO) GetMsg() string {
	if o == nil || IsNil(o.Msg) {
		var ret string
		return ret
	}
	return *o.Msg
}

// GetMsgOk returns a tuple with the Msg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperationResponseVirtualWanIdUsedOpenApiVO) GetMsgOk() (*string, bool) {
	if o == nil || IsNil(o.Msg) {
		return nil, false
	}
	return o.Msg, true
}

// HasMsg returns a boolean if a field has been set.
func (o *OperationResponseVirtualWanIdUsedOpenApiVO) HasMsg() bool {
	if o != nil && !IsNil(o.Msg) {
		return true
	}

	return false
}

// SetMsg gets a reference to the given string and assigns it to the Msg field.
func (o *OperationResponseVirtualWanIdUsedOpenApiVO) SetMsg(v string) {
	o.Msg = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *OperationResponseVirtualWanIdUsedOpenApiVO) GetResult() VirtualWanIdUsedOpenApiVO {
	if o == nil || IsNil(o.Result) {
		var ret VirtualWanIdUsedOpenApiVO
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperationResponseVirtualWanIdUsedOpenApiVO) GetResultOk() (*VirtualWanIdUsedOpenApiVO, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *OperationResponseVirtualWanIdUsedOpenApiVO) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given VirtualWanIdUsedOpenApiVO and assigns it to the Result field.
func (o *OperationResponseVirtualWanIdUsedOpenApiVO) SetResult(v VirtualWanIdUsedOpenApiVO) {
	o.Result = &v
}

func (o OperationResponseVirtualWanIdUsedOpenApiVO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperationResponseVirtualWanIdUsedOpenApiVO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ErrorCode) {
		toSerialize["errorCode"] = o.ErrorCode
	}
	if !IsNil(o.Msg) {
		toSerialize["msg"] = o.Msg
	}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullableOperationResponseVirtualWanIdUsedOpenApiVO struct {
	value *OperationResponseVirtualWanIdUsedOpenApiVO
	isSet bool
}

func (v NullableOperationResponseVirtualWanIdUsedOpenApiVO) Get() *OperationResponseVirtualWanIdUsedOpenApiVO {
	return v.value
}

func (v *NullableOperationResponseVirtualWanIdUsedOpenApiVO) Set(val *OperationResponseVirtualWanIdUsedOpenApiVO) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationResponseVirtualWanIdUsedOpenApiVO) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationResponseVirtualWanIdUsedOpenApiVO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationResponseVirtualWanIdUsedOpenApiVO(val *OperationResponseVirtualWanIdUsedOpenApiVO) *NullableOperationResponseVirtualWanIdUsedOpenApiVO {
	return &NullableOperationResponseVirtualWanIdUsedOpenApiVO{value: val, isSet: true}
}

func (v NullableOperationResponseVirtualWanIdUsedOpenApiVO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationResponseVirtualWanIdUsedOpenApiVO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


