/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SessionLimitRuleTemplateOpenApiVO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionLimitRuleTemplateOpenApiVO{}

// SessionLimitRuleTemplateOpenApiVO struct for SessionLimitRuleTemplateOpenApiVO
type SessionLimitRuleTemplateOpenApiVO struct {
	// IP of the session limit rule.
	Ip *string `json:"ip,omitempty"`
	// Max sessions should be within the range of 1–999999.
	MaxSession int32 `json:"maxSession"`
	// Name should contain 1 to 64 characters.
	Name string `json:"name"`
	// Source IDs of the session limit rule, only for network and IP group type.Network can be created using 'Create LAN network template' interface, and network ID can be obtained from 'Get LAN network template list' interface. IP group can be created using 'Create a new group profile template' interface, and IP group ID can be obtained from 'Get group profile template list' interface.
	SourceIds []string `json:"sourceIds,omitempty"`
	// Source type should be a value as follows: 0: network; 1: IP group; 2: IP.
	SourceType int32 `json:"sourceType"`
	// Status of the session limit rule.
	Status bool `json:"status"`
}

type _SessionLimitRuleTemplateOpenApiVO SessionLimitRuleTemplateOpenApiVO

// NewSessionLimitRuleTemplateOpenApiVO instantiates a new SessionLimitRuleTemplateOpenApiVO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionLimitRuleTemplateOpenApiVO(maxSession int32, name string, sourceType int32, status bool) *SessionLimitRuleTemplateOpenApiVO {
	this := SessionLimitRuleTemplateOpenApiVO{}
	this.MaxSession = maxSession
	this.Name = name
	this.SourceType = sourceType
	this.Status = status
	return &this
}

// NewSessionLimitRuleTemplateOpenApiVOWithDefaults instantiates a new SessionLimitRuleTemplateOpenApiVO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionLimitRuleTemplateOpenApiVOWithDefaults() *SessionLimitRuleTemplateOpenApiVO {
	this := SessionLimitRuleTemplateOpenApiVO{}
	return &this
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *SessionLimitRuleTemplateOpenApiVO) GetIp() string {
	if o == nil || IsNil(o.Ip) {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionLimitRuleTemplateOpenApiVO) GetIpOk() (*string, bool) {
	if o == nil || IsNil(o.Ip) {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *SessionLimitRuleTemplateOpenApiVO) HasIp() bool {
	if o != nil && !IsNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *SessionLimitRuleTemplateOpenApiVO) SetIp(v string) {
	o.Ip = &v
}

// GetMaxSession returns the MaxSession field value
func (o *SessionLimitRuleTemplateOpenApiVO) GetMaxSession() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxSession
}

// GetMaxSessionOk returns a tuple with the MaxSession field value
// and a boolean to check if the value has been set.
func (o *SessionLimitRuleTemplateOpenApiVO) GetMaxSessionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxSession, true
}

// SetMaxSession sets field value
func (o *SessionLimitRuleTemplateOpenApiVO) SetMaxSession(v int32) {
	o.MaxSession = v
}

// GetName returns the Name field value
func (o *SessionLimitRuleTemplateOpenApiVO) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SessionLimitRuleTemplateOpenApiVO) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SessionLimitRuleTemplateOpenApiVO) SetName(v string) {
	o.Name = v
}

// GetSourceIds returns the SourceIds field value if set, zero value otherwise.
func (o *SessionLimitRuleTemplateOpenApiVO) GetSourceIds() []string {
	if o == nil || IsNil(o.SourceIds) {
		var ret []string
		return ret
	}
	return o.SourceIds
}

// GetSourceIdsOk returns a tuple with the SourceIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionLimitRuleTemplateOpenApiVO) GetSourceIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.SourceIds) {
		return nil, false
	}
	return o.SourceIds, true
}

// HasSourceIds returns a boolean if a field has been set.
func (o *SessionLimitRuleTemplateOpenApiVO) HasSourceIds() bool {
	if o != nil && !IsNil(o.SourceIds) {
		return true
	}

	return false
}

// SetSourceIds gets a reference to the given []string and assigns it to the SourceIds field.
func (o *SessionLimitRuleTemplateOpenApiVO) SetSourceIds(v []string) {
	o.SourceIds = v
}

// GetSourceType returns the SourceType field value
func (o *SessionLimitRuleTemplateOpenApiVO) GetSourceType() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SourceType
}

// GetSourceTypeOk returns a tuple with the SourceType field value
// and a boolean to check if the value has been set.
func (o *SessionLimitRuleTemplateOpenApiVO) GetSourceTypeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceType, true
}

// SetSourceType sets field value
func (o *SessionLimitRuleTemplateOpenApiVO) SetSourceType(v int32) {
	o.SourceType = v
}

// GetStatus returns the Status field value
func (o *SessionLimitRuleTemplateOpenApiVO) GetStatus() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SessionLimitRuleTemplateOpenApiVO) GetStatusOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SessionLimitRuleTemplateOpenApiVO) SetStatus(v bool) {
	o.Status = v
}

func (o SessionLimitRuleTemplateOpenApiVO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionLimitRuleTemplateOpenApiVO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}
	toSerialize["maxSession"] = o.MaxSession
	toSerialize["name"] = o.Name
	if !IsNil(o.SourceIds) {
		toSerialize["sourceIds"] = o.SourceIds
	}
	toSerialize["sourceType"] = o.SourceType
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *SessionLimitRuleTemplateOpenApiVO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"maxSession",
		"name",
		"sourceType",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSessionLimitRuleTemplateOpenApiVO := _SessionLimitRuleTemplateOpenApiVO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSessionLimitRuleTemplateOpenApiVO)

	if err != nil {
		return err
	}

	*o = SessionLimitRuleTemplateOpenApiVO(varSessionLimitRuleTemplateOpenApiVO)

	return err
}

type NullableSessionLimitRuleTemplateOpenApiVO struct {
	value *SessionLimitRuleTemplateOpenApiVO
	isSet bool
}

func (v NullableSessionLimitRuleTemplateOpenApiVO) Get() *SessionLimitRuleTemplateOpenApiVO {
	return v.value
}

func (v *NullableSessionLimitRuleTemplateOpenApiVO) Set(val *SessionLimitRuleTemplateOpenApiVO) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionLimitRuleTemplateOpenApiVO) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionLimitRuleTemplateOpenApiVO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionLimitRuleTemplateOpenApiVO(val *SessionLimitRuleTemplateOpenApiVO) *NullableSessionLimitRuleTemplateOpenApiVO {
	return &NullableSessionLimitRuleTemplateOpenApiVO{value: val, isSet: true}
}

func (v NullableSessionLimitRuleTemplateOpenApiVO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionLimitRuleTemplateOpenApiVO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


