/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
)

// checks if the LocalUserOpenApiVO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LocalUserOpenApiVO{}

// LocalUserOpenApiVO struct for LocalUserOpenApiVO
type LocalUserOpenApiVO struct {
	// Is the localuser effective for all portals, including all newly created portals
	ApplyToAllPortals *bool `json:"applyToAllPortals,omitempty"`
	// MAC binding type should be a value as follows: 0: no binding; 1: static binding; 2: dynamic binding.
	BindingType *int32 `json:"bindingType,omitempty"`
	DailyLimit *AuthTimeOpenApiVO `json:"dailyLimit,omitempty"`
	// Whether to enable localuser daily time limit
	DailyLimitEnable *bool `json:"dailyLimitEnable,omitempty"`
	// Daily time left, unit is ms, required when parameter [dailyLimitEnable] is true
	DailyLimitLeftMs *int64 `json:"dailyLimitLeftMs,omitempty"`
	// Daily time limit, unit is ms, required when parameter [dailyLimitEnable] is true
	DailyLimitMs *int64 `json:"dailyLimitMs,omitempty"`
	// Local user enable status
	Enable *bool `json:"enable,omitempty"`
	// Expiration time, unit: ms
	ExpirationTime *int64 `json:"expirationTime,omitempty"`
	// Local user ID
	Id *string `json:"id,omitempty"`
	// local user logout. enable local user logout.
	Logout *bool `json:"logout,omitempty"`
	// Mac address,the value is only available when the macType is static binding or dynamic binding.
	MacAddress *string `json:"macAddress,omitempty"`
	// The maximum number of users online at the same time when the MAC binding type is No Binding. It cannot be modified after initialization. Value of Maximum Users should be within the range of 1-2048.
	MaxUsers *int32 `json:"maxUsers,omitempty"`
	// Name
	Name *string `json:"name,omitempty" validate:"regexp=^$|^[^ \\\\+\\\\-\\\\@\\\\=]$|^[^ \\\\+\\\\-\\\\@\\\\=].{0,126}[^ ]$"`
	// Whether the current time has exceeded the expirationTime
	Overtime *bool `json:"overtime,omitempty"`
	// Password should contain 1 to 128 characters
	Password *string `json:"password,omitempty"`
	// Phone number should contain 1 to 20 characters.
	Phone *string `json:"phone,omitempty"`
	// Bound portal names.
	Portals []string `json:"portals,omitempty"`
	RateLimit *RateLimitOpenApiVO `json:"rateLimit,omitempty"`
	// Is there any remaining traffic.
	TrafficLeft *bool `json:"trafficLeft,omitempty"`
	// Traffic limit in MB. The value should be within the range of 1–10485760.
	TrafficLimit *int64 `json:"trafficLimit,omitempty"`
	// Whether to enable traffic limit.
	TrafficLimitEnable *bool `json:"trafficLimitEnable,omitempty"`
	// Frequency of traffic limit should be a value as follows: 0: total; 1: daily; 2: weekly; 3: monthly.
	TrafficLimitFrequency *int32 `json:"trafficLimitFrequency,omitempty"`
	// Used traffic(MB).
	TrafficUsed *int64 `json:"trafficUsed,omitempty"`
	// Used quantity.
	Used *int32 `json:"used,omitempty"`
	// User name should contain 1 to 128 characters
	UserName *string `json:"userName,omitempty" validate:"regexp=^[\\\\041-\\\\0176]$|^[\\\\041-\\\\0176][\\\\040-\\\\0176]{0,126}[\\\\041-\\\\0176]$"`
}

// NewLocalUserOpenApiVO instantiates a new LocalUserOpenApiVO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocalUserOpenApiVO() *LocalUserOpenApiVO {
	this := LocalUserOpenApiVO{}
	return &this
}

// NewLocalUserOpenApiVOWithDefaults instantiates a new LocalUserOpenApiVO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocalUserOpenApiVOWithDefaults() *LocalUserOpenApiVO {
	this := LocalUserOpenApiVO{}
	return &this
}

// GetApplyToAllPortals returns the ApplyToAllPortals field value if set, zero value otherwise.
func (o *LocalUserOpenApiVO) GetApplyToAllPortals() bool {
	if o == nil || IsNil(o.ApplyToAllPortals) {
		var ret bool
		return ret
	}
	return *o.ApplyToAllPortals
}

// GetApplyToAllPortalsOk returns a tuple with the ApplyToAllPortals field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalUserOpenApiVO) GetApplyToAllPortalsOk() (*bool, bool) {
	if o == nil || IsNil(o.ApplyToAllPortals) {
		return nil, false
	}
	return o.ApplyToAllPortals, true
}

// HasApplyToAllPortals returns a boolean if a field has been set.
func (o *LocalUserOpenApiVO) HasApplyToAllPortals() bool {
	if o != nil && !IsNil(o.ApplyToAllPortals) {
		return true
	}

	return false
}

// SetApplyToAllPortals gets a reference to the given bool and assigns it to the ApplyToAllPortals field.
func (o *LocalUserOpenApiVO) SetApplyToAllPortals(v bool) {
	o.ApplyToAllPortals = &v
}

// GetBindingType returns the BindingType field value if set, zero value otherwise.
func (o *LocalUserOpenApiVO) GetBindingType() int32 {
	if o == nil || IsNil(o.BindingType) {
		var ret int32
		return ret
	}
	return *o.BindingType
}

// GetBindingTypeOk returns a tuple with the BindingType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalUserOpenApiVO) GetBindingTypeOk() (*int32, bool) {
	if o == nil || IsNil(o.BindingType) {
		return nil, false
	}
	return o.BindingType, true
}

// HasBindingType returns a boolean if a field has been set.
func (o *LocalUserOpenApiVO) HasBindingType() bool {
	if o != nil && !IsNil(o.BindingType) {
		return true
	}

	return false
}

// SetBindingType gets a reference to the given int32 and assigns it to the BindingType field.
func (o *LocalUserOpenApiVO) SetBindingType(v int32) {
	o.BindingType = &v
}

// GetDailyLimit returns the DailyLimit field value if set, zero value otherwise.
func (o *LocalUserOpenApiVO) GetDailyLimit() AuthTimeOpenApiVO {
	if o == nil || IsNil(o.DailyLimit) {
		var ret AuthTimeOpenApiVO
		return ret
	}
	return *o.DailyLimit
}

// GetDailyLimitOk returns a tuple with the DailyLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalUserOpenApiVO) GetDailyLimitOk() (*AuthTimeOpenApiVO, bool) {
	if o == nil || IsNil(o.DailyLimit) {
		return nil, false
	}
	return o.DailyLimit, true
}

// HasDailyLimit returns a boolean if a field has been set.
func (o *LocalUserOpenApiVO) HasDailyLimit() bool {
	if o != nil && !IsNil(o.DailyLimit) {
		return true
	}

	return false
}

// SetDailyLimit gets a reference to the given AuthTimeOpenApiVO and assigns it to the DailyLimit field.
func (o *LocalUserOpenApiVO) SetDailyLimit(v AuthTimeOpenApiVO) {
	o.DailyLimit = &v
}

// GetDailyLimitEnable returns the DailyLimitEnable field value if set, zero value otherwise.
func (o *LocalUserOpenApiVO) GetDailyLimitEnable() bool {
	if o == nil || IsNil(o.DailyLimitEnable) {
		var ret bool
		return ret
	}
	return *o.DailyLimitEnable
}

// GetDailyLimitEnableOk returns a tuple with the DailyLimitEnable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalUserOpenApiVO) GetDailyLimitEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.DailyLimitEnable) {
		return nil, false
	}
	return o.DailyLimitEnable, true
}

// HasDailyLimitEnable returns a boolean if a field has been set.
func (o *LocalUserOpenApiVO) HasDailyLimitEnable() bool {
	if o != nil && !IsNil(o.DailyLimitEnable) {
		return true
	}

	return false
}

// SetDailyLimitEnable gets a reference to the given bool and assigns it to the DailyLimitEnable field.
func (o *LocalUserOpenApiVO) SetDailyLimitEnable(v bool) {
	o.DailyLimitEnable = &v
}

// GetDailyLimitLeftMs returns the DailyLimitLeftMs field value if set, zero value otherwise.
func (o *LocalUserOpenApiVO) GetDailyLimitLeftMs() int64 {
	if o == nil || IsNil(o.DailyLimitLeftMs) {
		var ret int64
		return ret
	}
	return *o.DailyLimitLeftMs
}

// GetDailyLimitLeftMsOk returns a tuple with the DailyLimitLeftMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalUserOpenApiVO) GetDailyLimitLeftMsOk() (*int64, bool) {
	if o == nil || IsNil(o.DailyLimitLeftMs) {
		return nil, false
	}
	return o.DailyLimitLeftMs, true
}

// HasDailyLimitLeftMs returns a boolean if a field has been set.
func (o *LocalUserOpenApiVO) HasDailyLimitLeftMs() bool {
	if o != nil && !IsNil(o.DailyLimitLeftMs) {
		return true
	}

	return false
}

// SetDailyLimitLeftMs gets a reference to the given int64 and assigns it to the DailyLimitLeftMs field.
func (o *LocalUserOpenApiVO) SetDailyLimitLeftMs(v int64) {
	o.DailyLimitLeftMs = &v
}

// GetDailyLimitMs returns the DailyLimitMs field value if set, zero value otherwise.
func (o *LocalUserOpenApiVO) GetDailyLimitMs() int64 {
	if o == nil || IsNil(o.DailyLimitMs) {
		var ret int64
		return ret
	}
	return *o.DailyLimitMs
}

// GetDailyLimitMsOk returns a tuple with the DailyLimitMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalUserOpenApiVO) GetDailyLimitMsOk() (*int64, bool) {
	if o == nil || IsNil(o.DailyLimitMs) {
		return nil, false
	}
	return o.DailyLimitMs, true
}

// HasDailyLimitMs returns a boolean if a field has been set.
func (o *LocalUserOpenApiVO) HasDailyLimitMs() bool {
	if o != nil && !IsNil(o.DailyLimitMs) {
		return true
	}

	return false
}

// SetDailyLimitMs gets a reference to the given int64 and assigns it to the DailyLimitMs field.
func (o *LocalUserOpenApiVO) SetDailyLimitMs(v int64) {
	o.DailyLimitMs = &v
}

// GetEnable returns the Enable field value if set, zero value otherwise.
func (o *LocalUserOpenApiVO) GetEnable() bool {
	if o == nil || IsNil(o.Enable) {
		var ret bool
		return ret
	}
	return *o.Enable
}

// GetEnableOk returns a tuple with the Enable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalUserOpenApiVO) GetEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.Enable) {
		return nil, false
	}
	return o.Enable, true
}

// HasEnable returns a boolean if a field has been set.
func (o *LocalUserOpenApiVO) HasEnable() bool {
	if o != nil && !IsNil(o.Enable) {
		return true
	}

	return false
}

// SetEnable gets a reference to the given bool and assigns it to the Enable field.
func (o *LocalUserOpenApiVO) SetEnable(v bool) {
	o.Enable = &v
}

// GetExpirationTime returns the ExpirationTime field value if set, zero value otherwise.
func (o *LocalUserOpenApiVO) GetExpirationTime() int64 {
	if o == nil || IsNil(o.ExpirationTime) {
		var ret int64
		return ret
	}
	return *o.ExpirationTime
}

// GetExpirationTimeOk returns a tuple with the ExpirationTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalUserOpenApiVO) GetExpirationTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.ExpirationTime) {
		return nil, false
	}
	return o.ExpirationTime, true
}

// HasExpirationTime returns a boolean if a field has been set.
func (o *LocalUserOpenApiVO) HasExpirationTime() bool {
	if o != nil && !IsNil(o.ExpirationTime) {
		return true
	}

	return false
}

// SetExpirationTime gets a reference to the given int64 and assigns it to the ExpirationTime field.
func (o *LocalUserOpenApiVO) SetExpirationTime(v int64) {
	o.ExpirationTime = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *LocalUserOpenApiVO) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalUserOpenApiVO) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *LocalUserOpenApiVO) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *LocalUserOpenApiVO) SetId(v string) {
	o.Id = &v
}

// GetLogout returns the Logout field value if set, zero value otherwise.
func (o *LocalUserOpenApiVO) GetLogout() bool {
	if o == nil || IsNil(o.Logout) {
		var ret bool
		return ret
	}
	return *o.Logout
}

// GetLogoutOk returns a tuple with the Logout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalUserOpenApiVO) GetLogoutOk() (*bool, bool) {
	if o == nil || IsNil(o.Logout) {
		return nil, false
	}
	return o.Logout, true
}

// HasLogout returns a boolean if a field has been set.
func (o *LocalUserOpenApiVO) HasLogout() bool {
	if o != nil && !IsNil(o.Logout) {
		return true
	}

	return false
}

// SetLogout gets a reference to the given bool and assigns it to the Logout field.
func (o *LocalUserOpenApiVO) SetLogout(v bool) {
	o.Logout = &v
}

// GetMacAddress returns the MacAddress field value if set, zero value otherwise.
func (o *LocalUserOpenApiVO) GetMacAddress() string {
	if o == nil || IsNil(o.MacAddress) {
		var ret string
		return ret
	}
	return *o.MacAddress
}

// GetMacAddressOk returns a tuple with the MacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalUserOpenApiVO) GetMacAddressOk() (*string, bool) {
	if o == nil || IsNil(o.MacAddress) {
		return nil, false
	}
	return o.MacAddress, true
}

// HasMacAddress returns a boolean if a field has been set.
func (o *LocalUserOpenApiVO) HasMacAddress() bool {
	if o != nil && !IsNil(o.MacAddress) {
		return true
	}

	return false
}

// SetMacAddress gets a reference to the given string and assigns it to the MacAddress field.
func (o *LocalUserOpenApiVO) SetMacAddress(v string) {
	o.MacAddress = &v
}

// GetMaxUsers returns the MaxUsers field value if set, zero value otherwise.
func (o *LocalUserOpenApiVO) GetMaxUsers() int32 {
	if o == nil || IsNil(o.MaxUsers) {
		var ret int32
		return ret
	}
	return *o.MaxUsers
}

// GetMaxUsersOk returns a tuple with the MaxUsers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalUserOpenApiVO) GetMaxUsersOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxUsers) {
		return nil, false
	}
	return o.MaxUsers, true
}

// HasMaxUsers returns a boolean if a field has been set.
func (o *LocalUserOpenApiVO) HasMaxUsers() bool {
	if o != nil && !IsNil(o.MaxUsers) {
		return true
	}

	return false
}

// SetMaxUsers gets a reference to the given int32 and assigns it to the MaxUsers field.
func (o *LocalUserOpenApiVO) SetMaxUsers(v int32) {
	o.MaxUsers = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *LocalUserOpenApiVO) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalUserOpenApiVO) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *LocalUserOpenApiVO) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *LocalUserOpenApiVO) SetName(v string) {
	o.Name = &v
}

// GetOvertime returns the Overtime field value if set, zero value otherwise.
func (o *LocalUserOpenApiVO) GetOvertime() bool {
	if o == nil || IsNil(o.Overtime) {
		var ret bool
		return ret
	}
	return *o.Overtime
}

// GetOvertimeOk returns a tuple with the Overtime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalUserOpenApiVO) GetOvertimeOk() (*bool, bool) {
	if o == nil || IsNil(o.Overtime) {
		return nil, false
	}
	return o.Overtime, true
}

// HasOvertime returns a boolean if a field has been set.
func (o *LocalUserOpenApiVO) HasOvertime() bool {
	if o != nil && !IsNil(o.Overtime) {
		return true
	}

	return false
}

// SetOvertime gets a reference to the given bool and assigns it to the Overtime field.
func (o *LocalUserOpenApiVO) SetOvertime(v bool) {
	o.Overtime = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *LocalUserOpenApiVO) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalUserOpenApiVO) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *LocalUserOpenApiVO) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *LocalUserOpenApiVO) SetPassword(v string) {
	o.Password = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *LocalUserOpenApiVO) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalUserOpenApiVO) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *LocalUserOpenApiVO) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *LocalUserOpenApiVO) SetPhone(v string) {
	o.Phone = &v
}

// GetPortals returns the Portals field value if set, zero value otherwise.
func (o *LocalUserOpenApiVO) GetPortals() []string {
	if o == nil || IsNil(o.Portals) {
		var ret []string
		return ret
	}
	return o.Portals
}

// GetPortalsOk returns a tuple with the Portals field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalUserOpenApiVO) GetPortalsOk() ([]string, bool) {
	if o == nil || IsNil(o.Portals) {
		return nil, false
	}
	return o.Portals, true
}

// HasPortals returns a boolean if a field has been set.
func (o *LocalUserOpenApiVO) HasPortals() bool {
	if o != nil && !IsNil(o.Portals) {
		return true
	}

	return false
}

// SetPortals gets a reference to the given []string and assigns it to the Portals field.
func (o *LocalUserOpenApiVO) SetPortals(v []string) {
	o.Portals = v
}

// GetRateLimit returns the RateLimit field value if set, zero value otherwise.
func (o *LocalUserOpenApiVO) GetRateLimit() RateLimitOpenApiVO {
	if o == nil || IsNil(o.RateLimit) {
		var ret RateLimitOpenApiVO
		return ret
	}
	return *o.RateLimit
}

// GetRateLimitOk returns a tuple with the RateLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalUserOpenApiVO) GetRateLimitOk() (*RateLimitOpenApiVO, bool) {
	if o == nil || IsNil(o.RateLimit) {
		return nil, false
	}
	return o.RateLimit, true
}

// HasRateLimit returns a boolean if a field has been set.
func (o *LocalUserOpenApiVO) HasRateLimit() bool {
	if o != nil && !IsNil(o.RateLimit) {
		return true
	}

	return false
}

// SetRateLimit gets a reference to the given RateLimitOpenApiVO and assigns it to the RateLimit field.
func (o *LocalUserOpenApiVO) SetRateLimit(v RateLimitOpenApiVO) {
	o.RateLimit = &v
}

// GetTrafficLeft returns the TrafficLeft field value if set, zero value otherwise.
func (o *LocalUserOpenApiVO) GetTrafficLeft() bool {
	if o == nil || IsNil(o.TrafficLeft) {
		var ret bool
		return ret
	}
	return *o.TrafficLeft
}

// GetTrafficLeftOk returns a tuple with the TrafficLeft field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalUserOpenApiVO) GetTrafficLeftOk() (*bool, bool) {
	if o == nil || IsNil(o.TrafficLeft) {
		return nil, false
	}
	return o.TrafficLeft, true
}

// HasTrafficLeft returns a boolean if a field has been set.
func (o *LocalUserOpenApiVO) HasTrafficLeft() bool {
	if o != nil && !IsNil(o.TrafficLeft) {
		return true
	}

	return false
}

// SetTrafficLeft gets a reference to the given bool and assigns it to the TrafficLeft field.
func (o *LocalUserOpenApiVO) SetTrafficLeft(v bool) {
	o.TrafficLeft = &v
}

// GetTrafficLimit returns the TrafficLimit field value if set, zero value otherwise.
func (o *LocalUserOpenApiVO) GetTrafficLimit() int64 {
	if o == nil || IsNil(o.TrafficLimit) {
		var ret int64
		return ret
	}
	return *o.TrafficLimit
}

// GetTrafficLimitOk returns a tuple with the TrafficLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalUserOpenApiVO) GetTrafficLimitOk() (*int64, bool) {
	if o == nil || IsNil(o.TrafficLimit) {
		return nil, false
	}
	return o.TrafficLimit, true
}

// HasTrafficLimit returns a boolean if a field has been set.
func (o *LocalUserOpenApiVO) HasTrafficLimit() bool {
	if o != nil && !IsNil(o.TrafficLimit) {
		return true
	}

	return false
}

// SetTrafficLimit gets a reference to the given int64 and assigns it to the TrafficLimit field.
func (o *LocalUserOpenApiVO) SetTrafficLimit(v int64) {
	o.TrafficLimit = &v
}

// GetTrafficLimitEnable returns the TrafficLimitEnable field value if set, zero value otherwise.
func (o *LocalUserOpenApiVO) GetTrafficLimitEnable() bool {
	if o == nil || IsNil(o.TrafficLimitEnable) {
		var ret bool
		return ret
	}
	return *o.TrafficLimitEnable
}

// GetTrafficLimitEnableOk returns a tuple with the TrafficLimitEnable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalUserOpenApiVO) GetTrafficLimitEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.TrafficLimitEnable) {
		return nil, false
	}
	return o.TrafficLimitEnable, true
}

// HasTrafficLimitEnable returns a boolean if a field has been set.
func (o *LocalUserOpenApiVO) HasTrafficLimitEnable() bool {
	if o != nil && !IsNil(o.TrafficLimitEnable) {
		return true
	}

	return false
}

// SetTrafficLimitEnable gets a reference to the given bool and assigns it to the TrafficLimitEnable field.
func (o *LocalUserOpenApiVO) SetTrafficLimitEnable(v bool) {
	o.TrafficLimitEnable = &v
}

// GetTrafficLimitFrequency returns the TrafficLimitFrequency field value if set, zero value otherwise.
func (o *LocalUserOpenApiVO) GetTrafficLimitFrequency() int32 {
	if o == nil || IsNil(o.TrafficLimitFrequency) {
		var ret int32
		return ret
	}
	return *o.TrafficLimitFrequency
}

// GetTrafficLimitFrequencyOk returns a tuple with the TrafficLimitFrequency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalUserOpenApiVO) GetTrafficLimitFrequencyOk() (*int32, bool) {
	if o == nil || IsNil(o.TrafficLimitFrequency) {
		return nil, false
	}
	return o.TrafficLimitFrequency, true
}

// HasTrafficLimitFrequency returns a boolean if a field has been set.
func (o *LocalUserOpenApiVO) HasTrafficLimitFrequency() bool {
	if o != nil && !IsNil(o.TrafficLimitFrequency) {
		return true
	}

	return false
}

// SetTrafficLimitFrequency gets a reference to the given int32 and assigns it to the TrafficLimitFrequency field.
func (o *LocalUserOpenApiVO) SetTrafficLimitFrequency(v int32) {
	o.TrafficLimitFrequency = &v
}

// GetTrafficUsed returns the TrafficUsed field value if set, zero value otherwise.
func (o *LocalUserOpenApiVO) GetTrafficUsed() int64 {
	if o == nil || IsNil(o.TrafficUsed) {
		var ret int64
		return ret
	}
	return *o.TrafficUsed
}

// GetTrafficUsedOk returns a tuple with the TrafficUsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalUserOpenApiVO) GetTrafficUsedOk() (*int64, bool) {
	if o == nil || IsNil(o.TrafficUsed) {
		return nil, false
	}
	return o.TrafficUsed, true
}

// HasTrafficUsed returns a boolean if a field has been set.
func (o *LocalUserOpenApiVO) HasTrafficUsed() bool {
	if o != nil && !IsNil(o.TrafficUsed) {
		return true
	}

	return false
}

// SetTrafficUsed gets a reference to the given int64 and assigns it to the TrafficUsed field.
func (o *LocalUserOpenApiVO) SetTrafficUsed(v int64) {
	o.TrafficUsed = &v
}

// GetUsed returns the Used field value if set, zero value otherwise.
func (o *LocalUserOpenApiVO) GetUsed() int32 {
	if o == nil || IsNil(o.Used) {
		var ret int32
		return ret
	}
	return *o.Used
}

// GetUsedOk returns a tuple with the Used field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalUserOpenApiVO) GetUsedOk() (*int32, bool) {
	if o == nil || IsNil(o.Used) {
		return nil, false
	}
	return o.Used, true
}

// HasUsed returns a boolean if a field has been set.
func (o *LocalUserOpenApiVO) HasUsed() bool {
	if o != nil && !IsNil(o.Used) {
		return true
	}

	return false
}

// SetUsed gets a reference to the given int32 and assigns it to the Used field.
func (o *LocalUserOpenApiVO) SetUsed(v int32) {
	o.Used = &v
}

// GetUserName returns the UserName field value if set, zero value otherwise.
func (o *LocalUserOpenApiVO) GetUserName() string {
	if o == nil || IsNil(o.UserName) {
		var ret string
		return ret
	}
	return *o.UserName
}

// GetUserNameOk returns a tuple with the UserName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalUserOpenApiVO) GetUserNameOk() (*string, bool) {
	if o == nil || IsNil(o.UserName) {
		return nil, false
	}
	return o.UserName, true
}

// HasUserName returns a boolean if a field has been set.
func (o *LocalUserOpenApiVO) HasUserName() bool {
	if o != nil && !IsNil(o.UserName) {
		return true
	}

	return false
}

// SetUserName gets a reference to the given string and assigns it to the UserName field.
func (o *LocalUserOpenApiVO) SetUserName(v string) {
	o.UserName = &v
}

func (o LocalUserOpenApiVO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LocalUserOpenApiVO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApplyToAllPortals) {
		toSerialize["applyToAllPortals"] = o.ApplyToAllPortals
	}
	if !IsNil(o.BindingType) {
		toSerialize["bindingType"] = o.BindingType
	}
	if !IsNil(o.DailyLimit) {
		toSerialize["dailyLimit"] = o.DailyLimit
	}
	if !IsNil(o.DailyLimitEnable) {
		toSerialize["dailyLimitEnable"] = o.DailyLimitEnable
	}
	if !IsNil(o.DailyLimitLeftMs) {
		toSerialize["dailyLimitLeftMs"] = o.DailyLimitLeftMs
	}
	if !IsNil(o.DailyLimitMs) {
		toSerialize["dailyLimitMs"] = o.DailyLimitMs
	}
	if !IsNil(o.Enable) {
		toSerialize["enable"] = o.Enable
	}
	if !IsNil(o.ExpirationTime) {
		toSerialize["expirationTime"] = o.ExpirationTime
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Logout) {
		toSerialize["logout"] = o.Logout
	}
	if !IsNil(o.MacAddress) {
		toSerialize["macAddress"] = o.MacAddress
	}
	if !IsNil(o.MaxUsers) {
		toSerialize["maxUsers"] = o.MaxUsers
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Overtime) {
		toSerialize["overtime"] = o.Overtime
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	if !IsNil(o.Portals) {
		toSerialize["portals"] = o.Portals
	}
	if !IsNil(o.RateLimit) {
		toSerialize["rateLimit"] = o.RateLimit
	}
	if !IsNil(o.TrafficLeft) {
		toSerialize["trafficLeft"] = o.TrafficLeft
	}
	if !IsNil(o.TrafficLimit) {
		toSerialize["trafficLimit"] = o.TrafficLimit
	}
	if !IsNil(o.TrafficLimitEnable) {
		toSerialize["trafficLimitEnable"] = o.TrafficLimitEnable
	}
	if !IsNil(o.TrafficLimitFrequency) {
		toSerialize["trafficLimitFrequency"] = o.TrafficLimitFrequency
	}
	if !IsNil(o.TrafficUsed) {
		toSerialize["trafficUsed"] = o.TrafficUsed
	}
	if !IsNil(o.Used) {
		toSerialize["used"] = o.Used
	}
	if !IsNil(o.UserName) {
		toSerialize["userName"] = o.UserName
	}
	return toSerialize, nil
}

type NullableLocalUserOpenApiVO struct {
	value *LocalUserOpenApiVO
	isSet bool
}

func (v NullableLocalUserOpenApiVO) Get() *LocalUserOpenApiVO {
	return v.value
}

func (v *NullableLocalUserOpenApiVO) Set(val *LocalUserOpenApiVO) {
	v.value = val
	v.isSet = true
}

func (v NullableLocalUserOpenApiVO) IsSet() bool {
	return v.isSet
}

func (v *NullableLocalUserOpenApiVO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocalUserOpenApiVO(val *LocalUserOpenApiVO) *NullableLocalUserOpenApiVO {
	return &NullableLocalUserOpenApiVO{value: val, isSet: true}
}

func (v NullableLocalUserOpenApiVO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocalUserOpenApiVO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


