/*
Omada Open API

Omada Open API

API version: v0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omada

import (
	"encoding/json"
)

// checks if the TopologyBriefDevice type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TopologyBriefDevice{}

// TopologyBriefDevice Brief device information.
type TopologyBriefDevice struct {
	// Device healthScore.
	HealthScore *int32 `json:"healthScore,omitempty"`
	// Odu device in ippt mode or not.
	Ippt *bool `json:"ippt,omitempty"`
	// Device mac.
	Mac *string `json:"mac,omitempty"`
	// Device model.
	Model *string `json:"model,omitempty"`
	// Device modelVersion.
	ModelVersion *string `json:"modelVersion,omitempty"`
	// Device name.
	Name *string `json:"name,omitempty"`
	// Device type.
	Type *string `json:"type,omitempty"`
}

// NewTopologyBriefDevice instantiates a new TopologyBriefDevice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTopologyBriefDevice() *TopologyBriefDevice {
	this := TopologyBriefDevice{}
	return &this
}

// NewTopologyBriefDeviceWithDefaults instantiates a new TopologyBriefDevice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTopologyBriefDeviceWithDefaults() *TopologyBriefDevice {
	this := TopologyBriefDevice{}
	return &this
}

// GetHealthScore returns the HealthScore field value if set, zero value otherwise.
func (o *TopologyBriefDevice) GetHealthScore() int32 {
	if o == nil || IsNil(o.HealthScore) {
		var ret int32
		return ret
	}
	return *o.HealthScore
}

// GetHealthScoreOk returns a tuple with the HealthScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopologyBriefDevice) GetHealthScoreOk() (*int32, bool) {
	if o == nil || IsNil(o.HealthScore) {
		return nil, false
	}
	return o.HealthScore, true
}

// HasHealthScore returns a boolean if a field has been set.
func (o *TopologyBriefDevice) HasHealthScore() bool {
	if o != nil && !IsNil(o.HealthScore) {
		return true
	}

	return false
}

// SetHealthScore gets a reference to the given int32 and assigns it to the HealthScore field.
func (o *TopologyBriefDevice) SetHealthScore(v int32) {
	o.HealthScore = &v
}

// GetIppt returns the Ippt field value if set, zero value otherwise.
func (o *TopologyBriefDevice) GetIppt() bool {
	if o == nil || IsNil(o.Ippt) {
		var ret bool
		return ret
	}
	return *o.Ippt
}

// GetIpptOk returns a tuple with the Ippt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopologyBriefDevice) GetIpptOk() (*bool, bool) {
	if o == nil || IsNil(o.Ippt) {
		return nil, false
	}
	return o.Ippt, true
}

// HasIppt returns a boolean if a field has been set.
func (o *TopologyBriefDevice) HasIppt() bool {
	if o != nil && !IsNil(o.Ippt) {
		return true
	}

	return false
}

// SetIppt gets a reference to the given bool and assigns it to the Ippt field.
func (o *TopologyBriefDevice) SetIppt(v bool) {
	o.Ippt = &v
}

// GetMac returns the Mac field value if set, zero value otherwise.
func (o *TopologyBriefDevice) GetMac() string {
	if o == nil || IsNil(o.Mac) {
		var ret string
		return ret
	}
	return *o.Mac
}

// GetMacOk returns a tuple with the Mac field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopologyBriefDevice) GetMacOk() (*string, bool) {
	if o == nil || IsNil(o.Mac) {
		return nil, false
	}
	return o.Mac, true
}

// HasMac returns a boolean if a field has been set.
func (o *TopologyBriefDevice) HasMac() bool {
	if o != nil && !IsNil(o.Mac) {
		return true
	}

	return false
}

// SetMac gets a reference to the given string and assigns it to the Mac field.
func (o *TopologyBriefDevice) SetMac(v string) {
	o.Mac = &v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *TopologyBriefDevice) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopologyBriefDevice) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *TopologyBriefDevice) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *TopologyBriefDevice) SetModel(v string) {
	o.Model = &v
}

// GetModelVersion returns the ModelVersion field value if set, zero value otherwise.
func (o *TopologyBriefDevice) GetModelVersion() string {
	if o == nil || IsNil(o.ModelVersion) {
		var ret string
		return ret
	}
	return *o.ModelVersion
}

// GetModelVersionOk returns a tuple with the ModelVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopologyBriefDevice) GetModelVersionOk() (*string, bool) {
	if o == nil || IsNil(o.ModelVersion) {
		return nil, false
	}
	return o.ModelVersion, true
}

// HasModelVersion returns a boolean if a field has been set.
func (o *TopologyBriefDevice) HasModelVersion() bool {
	if o != nil && !IsNil(o.ModelVersion) {
		return true
	}

	return false
}

// SetModelVersion gets a reference to the given string and assigns it to the ModelVersion field.
func (o *TopologyBriefDevice) SetModelVersion(v string) {
	o.ModelVersion = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TopologyBriefDevice) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopologyBriefDevice) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TopologyBriefDevice) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TopologyBriefDevice) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *TopologyBriefDevice) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopologyBriefDevice) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *TopologyBriefDevice) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *TopologyBriefDevice) SetType(v string) {
	o.Type = &v
}

func (o TopologyBriefDevice) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TopologyBriefDevice) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HealthScore) {
		toSerialize["healthScore"] = o.HealthScore
	}
	if !IsNil(o.Ippt) {
		toSerialize["ippt"] = o.Ippt
	}
	if !IsNil(o.Mac) {
		toSerialize["mac"] = o.Mac
	}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.ModelVersion) {
		toSerialize["modelVersion"] = o.ModelVersion
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableTopologyBriefDevice struct {
	value *TopologyBriefDevice
	isSet bool
}

func (v NullableTopologyBriefDevice) Get() *TopologyBriefDevice {
	return v.value
}

func (v *NullableTopologyBriefDevice) Set(val *TopologyBriefDevice) {
	v.value = val
	v.isSet = true
}

func (v NullableTopologyBriefDevice) IsSet() bool {
	return v.isSet
}

func (v *NullableTopologyBriefDevice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTopologyBriefDevice(val *TopologyBriefDevice) *NullableTopologyBriefDevice {
	return &NullableTopologyBriefDevice{value: val, isSet: true}
}

func (v NullableTopologyBriefDevice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTopologyBriefDevice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


