name: Create version PR

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  version-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Install tools
        run: go install tool

      - name: Create or update release PR
        run: | 
          changeset gh pr open \
            --owner ${{ github.event.repository.owner }} \
            --repo ${{ github.event.repository.name }}